### ISSUE TITLE
Long titles in IA import fail on slug creation

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1086]
Attempting to import https://archive.org/details/geographicalhist02alce_0 fails with this error:

```

I, [2018-06-11T13:57:17.667146 #97451]  INFO -- : Completed 500 Internal Server Error in 22ms
F, [2018-06-11T13:57:17.669379 #97451] FATAL -- : 
ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'slug' at row 1: INSERT INTO `works` (`author`, `created_on`, `description`, `ocr_correction`, `owner_user_id`, `physical_description`, `slug`, `title`) VALUES ('Alcedo, Antonio de, 1735-1812; Thompson, George Alexander', '2018-06-11 18:57:17', 'Vol. 4-5 have imprint: London, Printed for the author, and published by Carpenter and SonIncludes bibliographical references (v. 5, p. xxv-xxxv)Palau y Dulcet (2nd ed.)Sabin', 1, 3, '', 'the-geographical-and-historical-dictionary-of-america-and-the-west-indies-containing-an-entire-translation-of-the-spanish-work-of-colonel-don-antonio-de-alcedo-captain-of-the-royal-spanish-guards-and-member-of-the-royal-7b712ebc-7aea-4e9c-ad67-6cc0cc2ea8e7', 'The geographical and historical dictionary of America and the West Indies : containing an entire translation of the Spanish work of Colonel Don Antonio de Alcedo, Captain of the Royal Spanish guards, and member of the Royal Academy of History : with la...')):
  app/models/ia_work.rb:83:in `convert_to_work'
  app/controllers/ia_controller.rb:26:in `convert'
```

**Comment by bencomp** [comment]
Different but related: #1055

**Comment by benwbrum** [comment]
TODO: Test and see if we've already fixed this.

**Comment by saracarl** [comment]
fixed.
