### ISSUE TITLE
Assign categories gives 500 error on Alcedo

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1156]
Saving any of the first four pages in Alcedo results in a 500 error.  The logfiles indicate that we have an unexpected null value somewhere:

```

I, [2018-08-02T05:09:00.533119 #8279]  INFO -- : TRANSCRIPTION	2018-08-02 05:09:00 -0500
TRANSCRIPTION	User	ID: 3	Email: benwbrum@gmail.com	Display Name: benwbrum
TRANSCRIPTION	Collection	ID: 23	Title:LatAm Digital Edition and Gazetteer	Owner Email: benwbrum@gmail.com
TRANSCRIPTION	Work	ID: 627	Title: The geographical and historical dictionary of America and the West Indies [volume 1]
TRANSCRIPTION	Page	ID: 8764	Position: 1	Title:Untitled Page 1
TRANSCRIPTION	Source Text:
BEGIN_SOURCE_TEXT
THE

GEOGRAPHICAL AND HISTORICAL

DICTIONARY

OF

AMERICA AND THE WEST INDIES.

ABA

[Aaronsburgh lies at the head of Penn’s
Creek, Northumberland county, Pennsylvania ;
about SO miles w. from Lewisburgh, and 40 w. by
n. from Sunbury. Lat. 40° 52' 30" n. Long. 77°
SI' SO" O).]

==[[ABACACTIS, or Abacaris,]]==, a settlement of
Indians, of this name, in the [[province of the Ama-
zonas]], and in the part or territory possessed by the
Portuguese. It is a reduccion of the religious
order of the Carmelites of this nation, situate on
the shores of a lake of the same name. It lies
between this lake and a river, which is also so
called, and which is a large arm of the Madeira,
which, passing through this territory, afterwards
returns to that from whence it flowed, forming the
[[island of Topinambes]].

[==[[Abaco|ABACO]]==, one of the largest and most northern
of the [[Bahama islands]], situate upon the s. e. end
of the Little Bahama bank. The Hole in the
Rock, or (as it is most commonly called) the
Hole in the Wall, is the most southern point of
the island, and bears about 18 leagues north from
the island of New Providence, about 9 or 10
leagues in a n. w. direction from Egg Island,
and about 10 or 12 in a n. e. direction from
the Berry islands. About 10 leagues to the n. of
the Hole in the Wall, on the e. side of the island,
is Little Harbour, the entrance to which is be-
tween the main land of Abaco and Ledyard’s Key,

VOL. I. ^

ABA

and within which there is good anchorage. There
is also an anchorage to the w. of the Hole in the
Wall.

The island of Abaco is at present uninhabited.
In 1788 it contained about 50 settlers and 200
Negroes. The lands granted by the crown, pre-
vious to May 1803, amounted to 14,058 acres, for
the purpose of cultivation ; but the settlers who
occupied it have since removed. It contains great
quantities of the various kinds of woods which
are common to almost all the Bahama islands.

To the northward of Abaco, is a long chain of
small islands or keys, (including Elbow Key,
Man of War Key, Great Guana Key, the Gala-
pagos, &c. &c.) reaching, in a n. w. direction,
almost to the Matanilla reefs on the Florida
stream ; from whence the Little Bahama bank ex-
tends, in a southerly direction, to the west point
of the island of the Grand Bahama. [Lat. 2C°
22' n. Long. 77° 14' zo. See Bahamas.^

[ABACOOCHE, or Coosee, a large river, ris-
ing in the s. w. territory, passing into Georgia,
through the Cherokee into the Creek country,
where it unites with the Oakfuskee, and forms the
Alibama.]

ABACQUA, a settlement of the province and
government of Buenos Ayres, situate on the shore
of the river Parana, near the spot where it enters
the Paraguay, to the e. of the city of Corrientes,

B


END_SOURCE_TEXT


I, [2018-08-02T05:09:00.646450 #8279]  INFO -- : TRANSCRIPTION	2018-08-02 05:09:00 -0500	SUCCESS	
I, [2018-08-02T05:09:00.683139 #8279]  INFO -- : Redirected to https://fromthepage.lib.utexas.edu/transcribe/assign_categories?collection_id=latam-digital-edition-and-gazetteer&page_id=8764
E, [2018-08-02T05:09:00.731165 #8279] ERROR -- : Mysql2::Error: Duplicate entry '7f757ba2-729e-41ce-833f-4892b4c695e8' for key 'index_visits_on_visit_token': INSERT INTO `visits` (`browser`, `device_type`, `ip`, `landing_page`, `latitude`, `longitude`, `os`, `referrer`, `referring_domain`, `started_at`, `user_agent`, `user_id`, `visit_token`, `visitor_token`) VALUES ('Firefox', 'Desktop', '74.135.16.164', 'https://fromthepage.lib.utexas.edu/transcribe/save_transcription', 0, 0, 'Ubuntu', 'https://fromthepage.lib.utexas.edu/benwbrum/latam-digital-edition-and-gazetteer/alcedo-thompson-1/transcribe/8764', 'fromthepage.lib.utexas.edu', '2018-08-02 10:09:00', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 3, '7f757ba2-729e-41ce-833f-4892b4c695e8', 'e6b06a7d-be07-4453-a4c9-d8c167b264a6')
I, [2018-08-02T05:09:00.738346 #8279]  INFO -- : Completed 302 Found in 652ms (ActiveRecord: 62.8ms)
I, [2018-08-02T05:09:01.142365 #8279]  INFO -- : Started GET "/transcribe/assign_categories?collection_id=latam-digital-edition-and-gazetteer&page_id=8764" for 74.135.16.164 at 2018-08-02 05:09:01 -0500
I, [2018-08-02T05:09:01.143685 #8279]  INFO -- : Processing by TranscribeController#assign_categories as HTML
I, [2018-08-02T05:09:01.143760 #8279]  INFO -- :   Parameters: {"collection_id"=>"latam-digital-edition-and-gazetteer", "page_id"=>"8764"}
I, [2018-08-02T05:09:01.589138 #8279]  INFO -- :   Rendered inline template (0.6ms)
I, [2018-08-02T05:09:01.659607 #8279]  INFO -- :   Rendered shared/_page_tabs.html.slim (49.6ms)
I, [2018-08-02T05:09:01.705265 #8279]  INFO -- :   Rendered transcribe/assign_categories.html.slim within layouts/application (95.5ms)
I, [2018-08-02T05:09:01.705511 #8279]  INFO -- : Completed 500 Internal Server Error in 562ms
F, [2018-08-02T05:09:01.707358 #8279] FATAL -- : 
ActionView::Template::Error (undefined method `html_safe' for nil:NilClass):
    13:     -update_article_url = url_for({ :controller => 'article', :action => 'article_category', :article_id => article.id })
    14:     .page-uncategorized
    15:       h4.page-uncategorized_subject(data-prefix="Subject: " *language_attrs(@collection)) =="&ldquo;#{article.title}&rdquo;"
    16:       code= highlight(excerpt(@page.source_text, article.title, separator: ' ', radius: 6), article.title)
    17:       select(data-assign-categories="#{update_article_url}" size="1" aria-label="Assign categories" multiple)
    18:         -@collection.categories.walk_tree do |c, level|
    19:           -selected = true if article.categories.include?(c)
  app/views/transcribe/assign_categories.html.slim:16:in `block in _app_views_transcribe_assign_categories_html_slim___3953204742073521869_70300962566180'
  app/views/transcribe/assign_categories.html.slim:11:in `each'
  app/views/transcribe/assign_categories.html.slim:11:in `_app_views_transcribe_assign_categories_html_slim___3953204742073521869_70300962566180'
  app/controllers/transcribe_controller.rb:182:in `block in assign_categories'
  app/controllers/transcribe_controller.rb:180:in `assign_categories'

```

I have requested a database dump from UT.

**Comment by jackweinbender** [comment]
Ok. I've looked into this more closely and I've been able to reproduce/confirm all oft eh above except the first bullet point (I haven't experienced any funny stuff if just the verbatim text has a newline).

I think there are actually two parts to this we need to address:

1. When an article doesn't explicitly list its title but includes a line break, the line break is being included in the title. SO [[Foo\nBar]] and [[FooBar]] are getting saved as two different subjects, which I think is unexpected behavior. So, we are probably going to need to figure out a way to standardize those somehow; which means we'll probably have to also think about how to distinguish between titles that include a newline, but break on a space, like [[Austin,\nTX]] and those that break mid-word [[Water\nloo, TX]].

2. Highlighting and excerpting. I think we'll just need to write some custom helper functions. Both the Rails helpers, which are great, do some form of text sanitation, which is (I think) part of what's causing our searches to break.

Rather than trying to match-up the verbatim text, I wonder if we can just write a smart-ish regex that will get us there: Something that includes the brackets to avoid the false positives but can deal with newlines appropriately.
