### ISSUE TITLE
Long topics/subjects break Internet Archive imports

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1338]
NYBG is seeing a 500 error when importing this work from the Internet Archive:  https://archive.org/details/johnstillwellsc00scha

This error is caused by a column width problem in the intermediate `ia_works` table:
```
  SQL (4.6ms)  INSERT INTO `ia_works` (`book_id`, `collection`, `created_at`, `creator`, `description`, `detail_url`, `djvu_file`, `ia_path`, `image_count`, `notes`, `scandata_file`, `server`, `subject`, `title`, `updated_at`, `user_id`, `zip_file`) VALUES ('johnstillwellsc00scha', 'biodiversitynybgtorreyNY_Botanical_Garden', '2019-05-10 14:23:28', 'Schanck, John Stillwell, 1817-1898', 'Correspondence from John Stillwell Schanck to John Torrey, dated March 12, 1855 and March 17, 1857. Schanck begins his first letter with a long, flowery description of the recent fire in Princeton\'s Nassau Hall; he goes on to tell Torrey he misses him and passes on some gossip. He does this in his second letter as well, then speculates on who will take over Torrey\'s vacated chemistry chair at Princeton. He also makes reference to the recent Supreme Court decision in Dred Scott v. Sandford.', 'https://archive.org/details/johnstillwellsc00scha', 'johnstillwellsc00scha_djvu.xml', '/13/items/johnstillwellsc00scha', '10', '', 'johnstillwellsc00scha_scandata.xml', 'ia600909.us.archive.org', 'Trials, litigation, etcSchanck, John Stillwell, 1817-1898 -- CorrespondenceTorrey, John, 1796-1873 -- CorrespondenceAlexander, Stephen, 1806-1883Bailey, Jacob Whitman, 1811-1857Guyot, A. (Arnold), 1807-1884Holton, Isaac F. (Isaac Farwell)Scott, Dred, 1809-1858 -- Trials, litigation, etcNassau Hall (Princeton, N.J.)College of New Jersey (Princeton, N.J.)', 'John Stillwell Schanck and John Torrey correspondence, 1855-1857', '2019-05-10 14:23:28', 2, 'johnstillwellsc00scha_jp2.zip')
Mysql2::Error: Data too long for column 'subject' at row 1: INSERT INTO `ia_works` (`book_id`, `collection`, `created_at`, `creator`, `description`, `detail_url`, `djvu_file`, `ia_path`, `image_count`, `notes`, `scandata_file`, `server`, `subject`, `title`, `updated_at`, `user_id`, `zip_file`) VALUES ('johnstillwellsc00scha', 'biodiversitynybgtorreyNY_Botanical_Garden', '2019-05-10 14:23:28', 'Schanck, John Stillwell, 1817-1898', 'Correspondence from John Stillwell Schanck to John Torrey, dated March 12, 1855 and March 17, 1857. Schanck begins his first letter with a long, flowery description of the recent fire in Princeton\'s Nassau Hall; he goes on to tell Torrey he misses him and passes on some gossip. He does this in his second letter as well, then speculates on who will take over Torrey\'s vacated chemistry chair at Princeton. He also makes reference to the recent Supreme Court decision in Dred Scott v. Sandford.', 'https://archive.org/details/johnstillwellsc00scha', 'johnstillwellsc00scha_djvu.xml', '/13/items/johnstillwellsc00scha', '10', '', 'johnstillwellsc00scha_scandata.xml', 'ia600909.us.archive.org', 'Trials, litigation, etcSchanck, John Stillwell, 1817-1898 -- CorrespondenceTorrey, John, 1796-1873 -- CorrespondenceAlexander, Stephen, 1806-1883Bailey, Jacob Whitman, 1811-1857Guyot, A. (Arnold), 1807-1884Holton, Isaac F. (Isaac Farwell)Scott, Dred, 1809-1858 -- Trials, litigation, etcNassau Hall (Princeton, N.J.)College of New Jersey (Princeton, N.J.)', 'John Stillwell Schanck and John Torrey correspondence, 1855-1857', '2019-05-10 14:23:28', 2, 'johnstillwellsc00scha_jp2.zip')
   (0.5ms)  ROLLBACK
Completed 500 Internal Server Error in 815ms

Mysql2::Error - Data too long for column 'subject' at row 1:
  app/models/ia_work.rb:140:in `ingest_work'
  app/controllers/ia_controller.rb:127:in `import_work'
```

Since the `subject` column is not used once the IA work is converted to a FromThePage work, this problematic code can be eliminated entirely.

**Comment by benwbrum** [comment]
This appears to work correctly now.
