### ISSUE TITLE
Long notes break with no error message.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1491]
An end user at a customer site reports than when he adds the following note, the browser just spins:
```
This page has a scanning error. The same text transcribed as page 2 appears here, in a shape that resembles the missing paper from page 3. Perhaps the page was torn and misfed wrong side up. That piece was not re-transcribed, only the addressing page which appears underneath the scrap.
```
Reproducing this locally, I see this in the logs:
```
  SQL (31.2ms)  INSERT INTO `notes` (`body`, `collection_id`, `created_at`, `page_id`, `title`, `updated_at`, `user_id`, `work_id`) VALUES ('This page has a scanning error. The same text transcribed as page 2 appears here, in a shape that resembles the missing paper from page 3. Perhaps the page was torn and misfed wrong side up. That piece was not re-transcribed, only the addressing page which appears underneath the scrap.', 1, '2019-08-30 15:41:00', 6086, 'This page has a scanning error. The same text transcribed as page 2 appears here, in a shape that resembles the missing paper from page 3. Perhaps the page was torn and misfed wrong side up. That piece was not re-transcribed, only the addressing page which appears underneath the scrap.', '2019-08-30 15:41:00', 2, 17)
Mysql2::Error: Data too long for column 'title' at row 1: INSERT INTO `notes` (`body`, `collection_id`, `created_at`, `page_id`, `title`, `updated_at`, `user_id`, `work_id`) VALUES ('This page has a scanning error. The same text transcribed as page 2 appears here, in a shape that resembles the missing paper from page 3. Perhaps the page was torn and misfed wrong side up. That piece was not re-transcribed, only the addressing page which appears underneath the scrap.', 1, '2019-08-30 15:41:00', 6086, 'This page has a scanning error. The same text transcribed as page 2 appears here, in a shape that resembles the missing paper from page 3. Perhaps the page was torn and misfed wrong side up. That piece was not re-transcribed, only the addressing page which appears underneath the scrap.', '2019-08-30 15:41:00', 2, 17)
   (0.5ms)  ROLLBACK
Completed 500 Internal Server Error in 621ms

Mysql2::Error - Data too long for column 'title' at row 1:
  app/controllers/notes_controller.rb:20:in `block in create'
  app/controllers/notes_controller.rb:17:in `create'

```

There are two problems here:
* *Errors in notes are invisible to users:*  If there is a server error, the user does not get any feedback because the note is posted via AJAX and we don't do anything with the response.  Our JS that posts the note should look for error codes in the response and display an error to the user.
* *Long notes don't work:*  I don't think we actually use the `title` field of the notes table anywhere in the app, but apparently we copy the body of the note into the title, breaking on long notes.  At minimum, we should 
  * Verify that note.title is not used elsewhere
  * Truncate the text copied into the title to 255 characters, so that long notes no longer explode

**Comment by diegoviola** [comment]
> Long notes don't work: I don't think we actually use the title field of the notes table anywhere in the app[...]

The `spec/features/document_sets_spec.rb:174` breaks when when `@note.title = @note.body` is removed from `NotesController#create`. I'm not exactly sure why that happens yet.
