### ISSUE TITLE
expunge failing 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1498]
When trying to expunge the Utah State Archives trial account, I get a:

I, [2019-09-06T13:31:02.775960 #26587]  INFO -- : Started PATCH "/admin/expunge_user" for 70.112.51.192 at 2019-09-06 13:31:02 +0000
I, [2019-09-06T13:31:02.780247 #26587]  INFO -- : Processing by AdminController#expunge_user as */*
I, [2019-09-06T13:31:02.780395 #26587]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"EbcgtZ7cYghj9KuM76HMo/mFa7U5JpO7BmWm5UU96s4=", "user_id"=>"213791", "button"=>""}
I, [2019-09-06T13:31:02.821294 #26587]  INFO -- : Completed 500 Internal Server Error in 41ms
F, [2019-09-06T13:31:02.822945 #26587] FATAL -- : 
NoMethodError (undefined method `title' for nil:NilClass):
  app/models/page_version.rb:34:in `expunge'
  app/models/user.rb:189:in `block in expunge'
  app/models/user.rb:189:in `expunge'
  app/controllers/admin_controller.rb:98:in `expunge_user'

**Comment by benwbrum** [comment]
This also failed when I tried to delete a spam account that had uploaded a job ad.  Apparently expunge doesn't delete collections, so I had to log in as the owner, delete their collection, then log out and expunge them.
