### ISSUE TITLE
Install issue on db:migrate

### ISSUE THREAD

**Issue by pointoneseven** [benwbrum/fromthepage#1664]
Platform: Ubuntu 18.04
Ruby: 2.3, 2.4, 2.5, 2.7

Process to recreate: 

- Installing build-essental, other prerequisites, etc.
- Clone repository, run bundle install (after removing Gemfile.lock)
- running 'rake db:migrate' generates the following error: 

```
rake db:migrate
WARNING: Nokogiri was built against LibXML version 2.9.8, but has dynamically loaded 2.9.4
rake aborted!
TypeError: ActiveSupport::Duration can't be coerced into Integer
/usr/local/bundle/gems/activesupport-4.1.2/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/usr/local/bundle/gems/activesupport-4.1.2/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/usr/local/bundle/gems/activesupport-4.1.2/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:124:in `<module:Devise>'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:11:in `<top (required)>'
/home/fromthepage/config/application.rb:7:in `<top (required)>'
/home/fromthepage/Rakefile:5:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```
Searching around for similar issues showed a possible solution, dropping the Ruby version. I am seeing the same result on multiple versions.

**Comment by saracarl** [comment]
@pointoneseven -- would you try the "rails6" branch?  It uses a much more recent version of ruby & rails.

**Comment by pointoneseven** [comment]
That seems to have done the trick. Thank you!
