### ISSUE TITLE
exporting activity spreadsheet fails with 500 error

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1704]
ncdcr is getting the following 500 error when attempting to download activity spreadsheet for the following collections:

https://fromthepage.com/ncdcr-ncarchives/african-american-education

https://fromthepage.com/ncdcr-ncarchives/wwi-diaries

https://fromthepage.com/ncdcr-ncarchives/wwi-letters

I, [2020-04-17T14:30:29.477034 #3990]  INFO -- : Completed 500 Internal Server E
rror in 601ms
F, [2020-04-17T14:30:29.565082 #3990] FATAL -- : 
NoMethodError (undefined method `title' for nil:NilClass):
  app/controllers/collection_controller.rb:410:in `block in activity_download'
  app/controllers/collection_controller.rb:390:in `activity_download'

**Comment by saracarl** [comment]
This doesn't happen for every collection, so it's likely a data problem, not a code problem (per se).

**Comment by saracarl** [comment]
This is the line that is failing:

https://github.com/benwbrum/fromthepage/blob/fromthepage.com/app/controllers/collection_controller.rb#L410

So there is a deed that doesn't have a page and isn't an article edit.  When I look at the deed list, I see two deeds that are "collection joined" deeds.  I suspect this is the problem.  To confirm this I'm going to filter out `DeedType::COLLECTION_JOINED` deeds and see if that resolves the problem.

**Comment by saracarl** [comment]
So filtering out the collection joined deeds from this section of code, like so:

```
      else 
        unless d.deed_type == DeedType::COLLECTION_JOINED
          pagedeeds = [
            d.page.title,
            collection_transcribe_page_url(d.page.collection.owner, d.page.collection, d.page.work, d.page),
            d.work.title,
            collection_read_work_url(d.work.collection.owner, d.work.collection, d.work),
            note,
          ] 
          record += pagedeeds
          record += ['','']
        end
      end
```

resolved the 500 error in the download.  Surprisingly, it kept the collection joined deeds in the downloaded spreadsheet, which means I don't have to figure out if we want them and how to include them.  

Next step:  commit & PR.
