### ISSUE TITLE
fix failing tests due to Notes changes

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1790]
```
  1) document sets checks notes on a public doc set/private collection
     Failure/Error: fill_in 'Write a new note...', with: "Test private note"
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/document_sets_spec.rb:177:in `block (2 levels) in <top (required)>'
  2) editor actions Legacy Group adds a note
     Failure/Error: fill_in 'Write a new note...', with: "Test note"
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/editor_actions_spec.rb:263:in `block (3 levels) in <top (required)>'
  3) editor actions Legacy Group Allows owner to delete note
     Failure/Error: expect(page).to have_content "Test note"
       expected to find text "Test note" in "ProjectsDashboardSigned In AsMargaret ReedOwner DashboardCollaborator DashboardYour ProfileSign OutCS PierceMS_641-6421Page 1 of 21OverviewTranscribeVersionsHelpSettingsFullscreenImage at the leftImage at the leftImage at the rightImage at the topImage at the bottom Always show in fullscreenMark as blankNeeds ReviewSave ChangesOpenSeadragon is not available unless JavaScript is enabled.Preview Autolink Test TranscriptionEdit transcriptionSave ChangesTranscription Conventions Spelling: Use original spelling if possible. Capitalization: Modernize for readability Punctuation: Add modern periods, but don't add punctuation like commas and apostrophes. Line Breaks: Hit return once after each line ends. Two returns indicate a new paragraph, which is usually indentation following the preceding sentence in the original. The times at the end of each entry should get their own paragraph, since the software does not support indentation in the transcriptions. Illegible text: Indicate illegible readings in single square brackets: [Dr?] A single newline indicates a line-break in the original document, and will not appear as a break in the text in some views or exports. Two newlines indicate a paragraph, and will appear as a paragraph break in all views.\"Autolink\" will suggest subjects certain words could be linked to or you can use double braces to link subjects. [[Jane Doe]] will link the text \"Jane Doe\" to the subject Jane Doe, while [[Jane Doe|Jane]] will link the text \"Jane\" to the subject Jane Doe. We recommend that linking be left to an editor after the initial transcription is made. More help....Notes and QuestionsNobody has written a note for this page yet Note bodySave NoteCollection FooterDocumentationBlogAboutTerms & ConditionsPrivacy PolicyContact Us© 2020 FromThePage. All rights reserved."
     # ./spec/features/editor_actions_spec.rb:273:in `block (3 levels) in <top (required)>'
  4) editor actions Legacy Group tries to save transcription with unsaved note
     Failure/Error: fill_in('0mWrite a new note...', with: "Test two")
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/editor_actions_spec.rb:282:in `block (3 levels) in <top (required)>'
  5) editor actions Legacy Group deletes a note
     Failure/Error: title = test_page.notes.last.id
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/features/editor_actions_spec.rb:301:in `block (3 levels) in <top (required)>'
  6) editor actions Legacy Group uses page arrows with unsaved transcription
     Failure/Error: fill_in('Write a new note...', with: "Test two")
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/editor_actions_spec.rb:321:in `block (3 levels) in <top (required)>'
  7) editor actions Legacy Group adds an abusive note
     Failure/Error: fill_in 'Write a new note...', with: "Visit <a href=\"www.spam.com\">our store!</a>"
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/editor_actions_spec.rb:404:in `block (3 levels) in <top (required)>'
  8) collection settings js tasks uses page arrows with unsaved transcription
     Failure/Error: fill_in('Write a new note...', with: "Test two")
     
     Capybara::ElementNotFound:
       Unable to find visible field "Write a new note..." that is not disabled
     # ./spec/features/field_based_spec.rb:123:in `block (2 levels) in <top (required)>'
```

**Comment by saracarl** [comment]
and this one:
```
13) notifications adds a response note (with email)
      Failure/Error: fill_in('Write a new note...', with: "Note by user")
      
      Capybara::ElementNotFound:
        Unable to find visible field "Write a new note..." that is not disabled
      # ./spec/features/notifications_spec.rb:32:in `block (2 levels) in <top (required)>'
```
