### ISSUE TITLE
Form feed character causes XML processing error; saving transcription fails

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1875]
One of our users quite consistently tries to save transcriptions with a [form feed character][ff] in them. This causes the transcription to not be saved and errors to be produced.

[ff]: https://en.wikipedia.org/wiki/Page_break#Form_feed

### Start of request
```
I, [2020-07-25T08:14:50.259046 #8333]  INFO -- : Started PATCH "/transcribe/save_transcription" for 86.93.153.185 at 2020-07-25 08:14:50 +0000
I, [2020-07-25T08:14:50.260513 #8333]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2020-07-25T08:14:50.260936 #8333]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"I5Ju4956DSQfFWvAgU/o0495mJvfjIj89BK4Z5/oT7k=", "page_id"=>"4169", "page"=>{"mark_blank"=>"0", "needs_review"=>"0", "source_text"=>"\fIl
 tappeto
```

### Start of raw text
```
TRANSCRIPTION   Source Text:
BEGIN_SOURCE_TEXT
^LIl tappeto
```

### Start of stacktrace
```
E, [2020-07-25T08:14:50.292635 #8333] ERROR -- : TRANSCRIPTION  2020-07-25 08:14:50 +0000       ERROR   EXCEPTION       #<RuntimeError: Illegal character "\f" in raw string "^LIl tappeto">
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/text.rb:139:in `block in check'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/text.rb:135:in `each'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/text.rb:135:in `check'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/text.rb:121:in `initialize'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/parsers/treeparser.rb:47:in `new'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/parsers/treeparser.rb:47:in `parse'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/document.rb:288:in `build'
/opt/rh/rh-ruby23/root/usr/share/ruby/rexml/document.rb:45:in `initialize'
/opt/fromthepage/app/models/xml_source_processor.rb:343:in `new'
/opt/fromthepage/app/models/xml_source_processor.rb:343:in `update_links_and_xml'
/opt/fromthepage/app/models/xml_source_processor.rb:114:in `wiki_to_xml'
/opt/fromthepage/app/models/xml_source_processor.rb:86:in `process_source'
/home/ubgit/.gem/ruby/gems/activesupport-4.1.2/lib/active_support/callbacks.rb:424:in `block in make_lambda'
```

## Analysis
I do not know for sure how this user gets the form feed character into the text, though I assume that they copy and paste the transcription from software that automatically inserts the character at the start of the text. I would like to tell them to clean the text before submitting, but the character is invisible. I think FromThePage should be more accepting of users and more strict in its handling of user-submitted content.

FromThePage internally (and when exporting) uses XML 1.0 to store transcriptions and translations. XML 1.0 doesn't allow control characters at all (XML 1.1 allows most control characters when they are character-encoded), but FromThePage doesn't check for or filter such characters before passing the constructed XML string to the XML processing library.
The method `valid_xml_from_source(source)` does convert `&` to `&amp;`, but should in my opinion also remove control characters (and perhaps do some more checking) before saying the return value is valid XML.

I will create a PR to at least remove the form feed character.

**Comment by benwbrum** [comment]
We have also recently been running into form feed characters in the initial text of PDF documents uploaded into the system.  Our current theory is that there is no text layer in the OCR, but the project owner has checked "Use OCR Layer Text".  Apparently this causes `\f` to be included in the initial page version created by `ingestor.rake`, but the bad character is only detected when a user attempts to transcribe the page.  (Note that we are not sure that this is the root cause at all;  this is just a theory.)

I'd like to remove all form-feed characters from existing data in a migration, but the approach you suggest--if I understand it correctly--of scrubbing them at transcription time seems more thorough.

**Comment by bencomp** [comment]
That is a very plausible theory! I haven't checked whether it is the case here, as I have no access to the collection (unless I masquerade as a collection owner).

Either way, you understand my intention correctly :)

**Comment by saracarl** [comment]
So here's what shows up when this happens:

![ftp_error](https://user-images.githubusercontent.com/708566/89205295-1f3de600-d57d-11ea-9bfa-89b17a459c30.jpg)

We need to strip out \f   (form feeds) after every save.  

We are getting tons of these errors and transcribers are getting frustrated.
