### ISSUE TITLE
500 error in user profile possible [regression]

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1898]
```I, [2020-07-29T18:17:59.268518 #19034]  INFO -- :   Rendering user/profile.html.slim within layouts/application
I, [2020-07-29T18:17:59.329121 #19034]  INFO -- :   Rendered user/profile.html.slim within layouts/application (Duration: 59.8ms | Allocations: 8368)
I, [2020-07-29T18:17:59.331112 #19034]  INFO -- : Completed 500  in 128ms (ActiveRecord: 76.2ms | Allocations: 14480)
F, [2020-07-29T18:17:59.340837 #19034] FATAL -- :   
ActionView::Template::Error (undefined method `title' for nil:NilClass):
    39:         -note_text = truncate(strip_tags(note.body), :length => 200)
    40:         tr
    41:           td.nowrap =note.created_at.localtime.strftime("%b %d, %Y, %l:%M %p")
    42:           td.overflow =link_to note.page.title, collection_display_page_path(note.page.collection.owner, note.page.collection, note.page.work, note.page)
    43:           td =link_to note_text, collection_display_page_path(note.page.collection.owner, note.page.collection, note.page.work, note.page, anchor: "note-#{note.id}")
    44: 
    45:     br
  
app/views/user/profile.html.slim:42
app/views/user/profile.html.slim:38
app/controllers/application_controller.rb:29:in `switch_locale'
```

Possibly related to #1897

**Comment by saracarl** [comment]
Ok, a third one that seems related to the `switch_local` issue:

```I, [2020-07-29T18:12:01.398059 #19016]  INFO -- :   Rendered export/tei.html.erb (Duration: 1294.2ms | Allocations: 543535)
I, [2020-07-29T18:12:01.404159 #19016]  INFO -- :   Rendering export/tei.html.erb
I, [2020-07-29T18:12:01.405277 #19016]  INFO -- :   Rendered export/tei.html.erb (Duration: 0.6ms | Allocations: 160)
I, [2020-07-29T18:12:01.406966 #19016]  INFO -- : Completed 500  in 1426ms (ActiveRecord: 808.2ms | Allocations: 560521)
F, [2020-07-29T18:12:01.428346 #19016] FATAL -- :   
ActionView::Template::Error (missing attribute: guest):
    31: 
    32:       <% @user_contributions.each do |user| %>
    33:         <respStmt xml:id="U<%= user[:user_id]%>">
    34:           <persName><%= user[:real_name] || user.display_name %></persName>
    35:           <% if user[:edit_count] == 1 %>
    36:             <resp>
    37:               made one edit on
  
app/models/user.rb:143:in `display_name'
app/views/export/tei.html.erb:34
app/views/export/tei.html.erb:32:in `each'
app/views/export/tei.html.erb:32
app/helpers/export_helper.rb:35:in `work_to_tei'
app/controllers/export_controller.rb:79:in `tei'
app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by benwbrum** [comment]
Full error:
```
I, [2020-07-29T18:17:59.201056 #19034]  INFO -- : Started GET "/heidimarie" for 17.58.100.130 at 2020-07-29 18:17:59 +0000
I, [2020-07-29T18:17:59.202689 #19034]  INFO -- : Processing by UserController#profile as HTML
I, [2020-07-29T18:17:59.202926 #19034]  INFO -- :   Parameters: {"user_id"=>"heidimarie"}
I, [2020-07-29T18:17:59.204146 #19034]  INFO -- : [ahoy] Visit excluded
I, [2020-07-29T18:17:59.268518 #19034]  INFO -- :   Rendering user/profile.html.slim within layouts/application
I, [2020-07-29T18:17:59.329121 #19034]  INFO -- :   Rendered user/profile.html.slim within layouts/application (Duration: 59.8ms | Allocations: 8368)
I, [2020-07-29T18:17:59.331112 #19034]  INFO -- : Completed 500  in 128ms (ActiveRecord: 76.2ms | Allocations: 14480)
F, [2020-07-29T18:17:59.340837 #19034] FATAL -- :   
ActionView::Template::Error (undefined method `title' for nil:NilClass):
    39:         -note_text = truncate(strip_tags(note.body), :length => 200)
    40:         tr
    41:           td.nowrap =note.created_at.localtime.strftime("%b %d, %Y, %l:%M %p")
    42:           td.overflow =link_to note.page.title, collection_display_page_path(note.page.collection.owner, note.page.collection, note.page.work, note.page)
    43:           td =link_to note_text, collection_display_page_path(note.page.collection.owner, note.page.collection, note.page.work, note.page, anchor: "note-#{note.id}")
    44: 
    45:     br
  
app/views/user/profile.html.slim:42
app/views/user/profile.html.slim:38
app/controllers/application_controller.rb:29:in `switch_locale'
```


This can be duplicated at https://fromthepage.com/heidimarie
