### ISSUE TITLE
missing attribute guest when exporting TEI, possible [regression]

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1902]
```I, [2020-07-29T18:12:01.398059 #19016]  INFO -- :   Rendered export/tei.html.erb (Duration: 1294.2ms | Allocations: 543535)
I, [2020-07-29T18:12:01.404159 #19016]  INFO -- :   Rendering export/tei.html.erb
I, [2020-07-29T18:12:01.405277 #19016]  INFO -- :   Rendered export/tei.html.erb (Duration: 0.6ms | Allocations: 160)
I, [2020-07-29T18:12:01.406966 #19016]  INFO -- : Completed 500  in 1426ms (ActiveRecord: 808.2ms | Allocations: 560521)
F, [2020-07-29T18:12:01.428346 #19016] FATAL -- :   
ActionView::Template::Error (missing attribute: guest):
    31: 
    32:       <% @user_contributions.each do |user| %>
    33:         <respStmt xml:id="U<%= user[:user_id]%>">
    34:           <persName><%= user[:real_name] || user.display_name %></persName>
    35:           <% if user[:edit_count] == 1 %>
    36:             <resp>
    37:               made one edit on
  
app/models/user.rb:143:in `display_name'
app/views/export/tei.html.erb:34
app/views/export/tei.html.erb:32:in `each'
app/views/export/tei.html.erb:32
app/helpers/export_helper.rb:35:in `work_to_tei'
app/controllers/export_controller.rb:79:in `tei'
app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by benwbrum** [comment]
This starts with
```
I, [2020-07-29T18:11:59.978597 #19016]  INFO -- : Started GET "/export/tei?work_id=39171" for 67.171.231.106 at 2020-07-29 18:11:59 +0000
I, [2020-07-29T18:11:59.980462 #19016]  INFO -- : Processing by ExportController#tei as HTML
I, [2020-07-29T18:11:59.980761 #19016]  INFO -- :   Parameters: {"work_id"=>"39171"}
I, [2020-07-29T18:12:00.103106 #19016]  INFO -- :   Rendering export/tei.html.erb
```
