### ISSUE TITLE
Owner homepage performance with large numbers of document sets

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1978]
While there are no glaringly slow queries executed when displaying https://fromthepage.com/lva, the overall page performance is slow because we query to see whether the user is allowed to see each document set owned by the owner.  If we instead got a list of all authorized document set IDs for the user in a single query and moved the display logic to check against that, we'd eliminate hundreds of queries.

This is the query that's running hundreds of times:
```
app/models/user.rb:115:in `collaborator?'
app/models/document_set.rb:38:in `show_to?'
app/models/user.rb:184:in `block in visible_collections_and_document_sets'
app/models/user.rb:184:in `select'
app/models/user.rb:184:in `visible_collections_and_document_sets'
app/controllers/user_controller.rb:70:in `profile'
app/controllers/application_controller.rb:29:in `switch_locale'
SELECT 1 AS one FROM `users` INNER JOIN `document_set_collaborators` ON `users`.`id` = `document_set_collaborators`.`user_id` WHERE `document_set_collaborators`.`document_set_id` = 453 AND `users`.`id` = 2 LIMIT 1; 
```

**Comment by benwbrum** [comment]
Pre-refactoring, `/lva` takes 13 seconds:

event | duration (ms) | from start (ms) | query time (ms)
-- | -- | -- | --
GET http://localhost:3000/lva | 1604.9 | +0.0 |  
Executing action: profile | 10240.9 | +26.0 | 483 sql | 586.7
Rendering: user/profile.html.slim | 15.7 | +10196.1 |  
Rendering: user/_owner_profile.html.slim | 1385.1 | +10207.9 | 4 sql | 3.7
Rendering: shared/_profile_picture.html.slim | 7.9 | +10230.1 |  
Rendering: deed/_deeds.html.slim | 57.1 | +11596.9 | 2 sql | 24.3

**Comment by benwbrum** [comment]
Post-refactoring takes 3 seconds:
GET http://localhost:3000/lva | 210.4 | +0.0 |  
Executing action: profile | 715.7 | +32.0 | 31 sql | 67.2
Rendering: user/profile.html.slim | 3.0 | +388.4 |  
Rendering: user/_owner_profile.html.slim | 1666.8 | +389.3 | 5 sql | 2.2
Rendering: deed/_deeds.html.slim | 69.9 | +2035.1 | 2 sql | 1.8
Rendering: shared/_breadcrumbs.html.slim | 3.4 | +2196.6

<br class="Apple-interchange-newline">
