### ISSUE TITLE
SSL Cert errors importing from CONTENTdm

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2040]
University of Ohio writes:

> I get this error "SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)" when trying to add new items through the "Import from CONTENTdm" dialog usign our vanity URL https://media.library.ohio.edu.
> 
> When I switch to "cdm15808.contentdm.oclc.org" it works. I've tried if from different collections (on our CDM and on FTP) with the same result.
> 
> This has been happening for some time--but it took me a while to bring it to you, sorry.
> 
> OCLC says "We have reviewed your CONTENTdm setup and we can confirm that your custom SSL certificate is valid and correct. We're pretty sure this error/issue is not caused by our setup. We're wondering if from-the-page does not have an updated cert store -- if they don't they can't recognize the cert. This seems like troubleshooting that has to be done with FromThePage (resource) to get a better error message.

![certificate-errorJPG](https://user-images.githubusercontent.com/199961/91744529-4210e980-eb7f-11ea-802a-8972b7cb66b1.JPG)

**Comment by benwbrum** [comment]
This appears to happen when we resolve the vanity URL to the `cdmNNNNN` URL through the top-level collection manifest, and does not happen when accessing the URL on a browser or via the app from my dev environment.  It does happen from a production rails console:

```
[11] pry(ContentdmTranslator):1> thing_to_get = "#{host}/iiif/info/manifest.json"
=> "https://media.library.ohio.edu/iiif/info/manifest.json"
[12] pry(ContentdmTranslator):1> URI.open("#{host}/iiif/info/manifest.json")
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
Caused by OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
```

**Comment by benwbrum** [comment]
Running in a production shell (outside the Rails framework) also fails:
```
fromthepage@fromthepage:~/deployment/current$ curl 'https://media.library.ohio.edu/iiif/info/manifest.json'
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by benwbrum** [comment]
Turning off curl certificate verification in production resolves successfully:
```
fromthepage@fromthepage:~/deployment/current$ curl --insecure 'https://media.library.ohio.edu/iiif/info/manifest.json'
{"@context":"http://iiif.io/api/presentation/2/context.json","@id":"https://cdm15808.contentdm.oclc.org/iiif/info/manifest.json","@type":"sc:Collection","collections":[{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/archives/manifest.json","@type":"sc:Collection","label":"Ohio University Archives-General"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll14/manifest.json","@type":"sc:Collection","label":"Athens Mental Health Center Collection"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll6/manifest.json","@type":"sc:Collection","label":"Civil War Correspondence"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll1/manifest.json","@type":"sc:Collection","label":"Frederick and Kazuko Harris Library Collection"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll9/manifest.json","@type":"sc:Collection","label":"Barnett Hook Papers and Needlework"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll19/manifest.json","@type":"sc:Collection","label":"Manuscript and Printed Leaves"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/wepeters/manifest.json","@type":"sc:Collection","label":"William E. Peters Papers"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll4/manifest.json","@type":"sc:Collection","label":"Rare Books"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll15/manifest.json","@type":"sc:Collection","label":"Cornelius Ryan Collection of World War II Papers"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/scripps/manifest.json","@type":"sc:Collection","label":"E.W. Scripps Papers"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/studentnewspapers/manifest.json","@type":"sc:Collection","label":"Ohio University Student Newspapers"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/speccoll/manifest.json","@type":"sc:Collection","label":"Special Collections-General"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll17/manifest.json","@type":"sc:Collection","label":"George Voinovich Collections"},{"@id":"https://cdm15808.contentdm.oclc.org/iiif/info/p15808coll16/manifest.json","@type":"sc:Collection","label":"Alwin Nikolais and Murray Louis Papers"}]}
```

**Comment by saracarl** [comment]
Resolved.  Had to remove bad certificates from the /etc/ssl/certs/ directory and then rebuild with a update-ca-certificates  (where "bad" was expired certs in the chain.)
