### ISSUE TITLE
500 error on read_all_works: wrong argument number (Logs P1)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2061]
From logs:

```

production.log-I, [2020-09-18T06:25:48.115635 #18893]  INFO -- : Started GET "/display/read_all_works/" for 45.140.53.11 at 2020-09-18 06:25:48 +0000
production.log-I, [2020-09-18T06:25:48.117665 #18893]  INFO -- : Processing by DisplayController#read_all_works as HTML
production.log:I, [2020-09-18T06:25:48.134981 #18893]  INFO -- : Completed 500  in 17ms (ActiveRecord: 3.7ms | Allocations: 4095)
production.log-F, [2020-09-18T06:25:48.141878 #18893] FATAL -- :   
production.log-ArgumentError (wrong number of arguments (given 2, expected 1)):
production.log-  
production.log-app/controllers/display_controller.rb:56:in `read_all_works'
production.log-app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by saracarl** [comment]
We believe this only occurs when someone is "url hacking" (editing the URL by hand).  The URL that results in this 500 error is:
http://fromthepage.com/display/read_all_works
which you could get if you deleted the end of:
https://fromthepage.com/display/read_all_works?article_id=10632

We don't see any other way to get to this URL in the application.

**Comment by saracarl** [comment]
This seems to be a bot, so closing the issue.
