### ISSUE TITLE
Nil error on user profile (.admin)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2065]
Logs
```

production.log-I, [2020-09-18T08:50:28.228924 #3657]  INFO -- : Started GET "/mdsca" for 207.188.150.112 at 2020-09-18 08:50:28 +0000
production.log-I, [2020-09-18T08:50:28.231510 #3657]  INFO -- : Processing by UserController#profile as HTML
production.log-I, [2020-09-18T08:50:28.231918 #3657]  INFO -- :   Parameters: {"user_id"=>"mdsca"}
production.log:I, [2020-09-18T08:50:28.255631 #3657]  INFO -- : Completed 500  in 23ms (ActiveRecord: 5.1ms | Allocations: 5264)
production.log-F, [2020-09-18T08:50:28.263984 #3657] FATAL -- :   
production.log-NoMethodError (undefined method `admin' for nil:NilClass):
production.log-  
production.log-app/controllers/user_controller.rb:69:in `profile'
production.log-app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by benwbrum** [comment]
Another instance:
```

production.log-I, [2020-09-18T09:00:52.208427 #4998]  INFO -- : Processing by UserController#profile as HTML
production.log-I, [2020-09-18T09:00:52.208800 #4998]  INFO -- :   Parameters: {"user_id"=>"mo"}
production.log:I, [2020-09-18T09:00:52.227894 #4998]  INFO -- : Completed 500  in 19ms (ActiveRecord: 5.0ms | Allocations: 5255)
production.log-F, [2020-09-18T09:00:52.233695 #4998] FATAL -- :   
production.log-NoMethodError (undefined method `admin' for nil:NilClass):
production.log-  
production.log-app/controllers/user_controller.rb:69:in `profile'
production.log-app/controllers/application_controller.rb:29:in `switch_locale'
```
