### ISSUE TITLE
500 error creating new accounts (Logs P1)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2068]
Logs:
```

production.log.1-I, [2020-09-17T13:21:09.154973 #25249]  INFO -- : Started POST "/users" for 129.55.200.20 at 2020-09-17 13:21:09 +0000
production.log.1-I, [2020-09-17T13:21:09.157541 #25249]  INFO -- : Processing by RegistrationsController#create as HTML
production.log.1-I, [2020-09-17T13:21:09.157968 #25249]  INFO -- :   Parameters: {"authenticity_token"=>"4NMwOyq7QsARW8WX08vsJiffGwKXyf1zbr3yQl+H+7n34/GET+xQri1kKbV2GsyGKWUPq7Q9BgBt6fIkQGFlew==", "user"=>{"login"=>"jenswan88", "email"=>"jenswanson@comcast.net", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "real_name"=>"Jennifer Swanson", "owner"=>"false", "paid_date"=>"", "activity_email"=>"1"}, "g-recaptcha-response"=>"03AGdBq24_y9UVe5nvMeH_o1CePt9zIY3u5CWXDBQbGIACzqXmde0At5x-RzVOCIIuj0BKuBpFD6n7b8ZDKxUaSfHbEXF-Smt9rqWa17d4VHVj9oG_M22MeHDQMPA0SOvgqpBA3XM18kt347kn46gL0e6vASJ_Yx4GM-y4c2YkpkETCPcXt_WLGa3lddXgCss2dzyICJhCZtxWXQ9819t0KRkkIubNSlHCX4_NoeJ7xEBz_dWaN9-CtmOOvS3gJYZZ5sOvwuxmm55MpBQwl6pyLzS4p8P9mF0CzN08BTz2VexlpOE8u3DgtxEf8lWkoab9pWg7l8UmaFz3YpKZl8X0DR0Gg17U7KwiGlT9R0KjwUjCUp27gRv0kdUEsydgBFqAU7LLfiDpXuJQZg84PON_V8hhRjeLshJoLRlO8bsvfzljMP1pYK500kpuA7wqHdZbeRm7VjFDjdOS", "button"=>""}
production.log.1-I, [2020-09-17T13:21:09.338462 #25249]  INFO -- : Redirected to https://fromthepage.com/megwinslow/sla-transcribe-a-thon/2014-020-003-012v/display/1350290
production.log.1-E, [2020-09-17T13:21:09.352023 #25249] ERROR -- : Bad record ID exception for params=<ActionController::Parameters {"authenticity_token"=>"4NMwOyq7QsARW8WX08vsJiffGwKXyf1zbr3yQl+H+7n34/GET+xQri1kKbV2GsyGKWUPq7Q9BgBt6fIkQGFlew==", "user"=><ActionController::Parameters {"login"=>"jenswan88", "email"=>"jenswanson@comcast.net", "password"=>"FILTERED", "password_confirmation"=>"FILTERED", "real_name"=>"Jennifer Swanson", "owner"=>"false", "paid_date"=>"", "activity_email"=>"1"} permitted: false>, "g-recaptcha-response"=>"03AGdBq24_y9UVe5nvMeH_o1CePt9zIY3u5CWXDBQbGIACzqXmde0At5x-RzVOCIIuj0BKuBpFD6n7b8ZDKxUaSfHbEXF-Smt9rqWa17d4VHVj9oG_M22MeHDQMPA0SOvgqpBA3XM18kt347kn46gL0e6vASJ_Yx4GM-y4c2YkpkETCPcXt_WLGa3lddXgCss2dzyICJhCZtxWXQ9819t0KRkkIubNSlHCX4_NoeJ7xEBz_dWaN9-CtmOOvS3gJYZZ5sOvwuxmm55MpBQwl6pyLzS4p8P9mF0CzN08BTz2VexlpOE8u3DgtxEf8lWkoab9pWg7l8UmaFz3YpKZl8X0DR0Gg17U7KwiGlT9R0KjwUjCUp27gRv0kdUEsydgBFqAU7LLfiDpXuJQZg84PON_V8hhRjeLshJoLRlO8bsvfzljMP1pYK500kpuA7wqHdZbeRm7VjFDjdOS", "button"=>"", "controller"=>"registrations", "action"=>"create"} permitted: false>
production.log.1-I, [2020-09-17T13:21:09.353479 #25249]  INFO -- : Redirected to 
production.log.1:I, [2020-09-17T13:21:09.356756 #25249]  INFO -- : Completed 500  in 198ms (ActiveRecord: 36.3ms | Allocations: 65894)
production.log.1-F, [2020-09-17T13:21:09.373843 #25249] FATAL -- :   
production.log.1-AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
production.log.1-  
production.log.1-app/controllers/application_controller.rb:170:in `bad_record_id'
production.log.1-I, [2020-09-17T13:21:10.519112 #25249]  INFO -- : Started GET "/favicon.ico" for 129.55.200.20 at 2020-09-17 13:21:10 +0000
production.log.1-I, [2020-09-17T13:21:10.523550 #25249]  INFO -- : Processing by UserController#profile as 
production.log.1-I, [2020-09-17T13:21:10.524240 #25249]  INFO -- :   Parameters: {"user_id"=>"favicon"}
production.log.1-E, [2020-09-17T13:21:10.541307 #25249] ERROR -- : Bad record ID exception for params=<ActionController::Parameters {"controller"=>"user", "action"=>"profile", "user_id"=>"favicon", "format"=>"ico"} permitted: false>
production.log.1-I, [2020-09-17T13:21:10.542710 #25249]  INFO -- : Redirected to https://fromthepage.com/404
production.log.1-I, [2020-09-17T13:21:10.545986 #25249]  INFO -- : Completed 302 Found in 21ms (ActiveRecord: 2.6ms | Allocations: 3513)
production.log.1-I, [2020-09-17T13:21:10.547536 #25249]  INFO -- : Oink Action: user#profile
production.log.1-I, [2020-09-17T13:21:10.548286 #25249]  INFO -- : Memory usage: 803244 | PID: 25249
production.log.1-I, [2020-09-17T13:21:10.548842 #25249]  INFO -- : Instantiation Breakdown: Total: 9 | User: 2 | FriendlyId::Slug: 2 | Visit: 2 | Notification: 1 | Ahoy::Event: 1 | Deed: 1
production.log.1-I, [2020-09-17T13:21:10.549324 #25249]  INFO -- : Oink Log Entry Complete
```

**Comment by benwbrum** [comment]
Another example
```

production.log.2.gz:I, [2020-09-16T20:21:15.193892 #414]  INFO -- : Redirected to https://fromthepage.com/megwinslow/sla-transcribe-a-thon/2014-020-003-012v
production.log.2.gz:E, [2020-09-16T20:21:15.208487 #414] ERROR -- : Bad record ID exception for params=<ActionController::Parameters {"authenticity_token"=>"oYOClbI6CGC9wT2LMQ2RDjBbZPgqeZvjIlC2XMALPHo7Ue9cpCksLPEMlbmxKFGDI/ud8rjzTBE/sIOLsZYO8A==", "user"=><ActionController::Parameters {"login"=>"kgambrell", "email"=>"gambrell9899@gmail.com", "password"=>"FILTERED", "password_confirmation"=>"FILTERED", "real_name"=>"KGambrell", "owner"=>"false", "paid_date"=>"", "activity_email"=>"1"} permitted: false>, "g-recaptcha-response"=>"03AGdBq24JsXYBGgqFi3xw7EPaBPFNHNZKig86WdLd9zlfeIIsAlxU7MeebOx79nIquzMBq3pzoF-J1AQFISElUM08rf2yom6mU4P-AxEpbp7uJCJz2s4e-vdStLTQsIP1Z4FTcXvzrVaD6_ERXA1BRy1v-e0dKaP-e9C13whgMGYS-PTEtdLTFpercImsUazKov8eAh0_Z-5drPK9DPex6zjjYmtZG16eGa84JF_PeFCBNpgUq5lmKmvJNk2WbzOlJAZLHUpPneWdkOtoezI7-qLuhBCH6YE5gCEqA-vb_75QUM2pufZXYpZMI8VGjzkDgwjhUQq-bA8CPEA1zdRG5a16YbDYTMC4bzyZSnHy43Chw_qtEkvDATJF6bIOiPYVLL5EsPuVMqEi1KhRoKu1r_BsD4W5nTTEI5RO4s7JJeXlKsyZLW61u9ja25cxcbsyzaREk5XVe3NvnDpWSV8YIljVbtivy2amiPnoN1iwXWsazJXEzB42-tRPgS42lzrOKycAe33x4VxTGths3sGre22cdWFE5_ggUw", "button"=>"", "controller"=>"registrations", "action"=>"create"} permitted: false>
production.log.2.gz:I, [2020-09-16T20:21:15.209295 #414]  INFO -- : Redirected to 
production.log.2.gz:I, [2020-09-16T20:21:15.212638 #414]  INFO -- : Completed 500  in 344ms (ActiveRecord: 39.6ms | Allocations: 65739)
production.log.2.gz:F, [2020-09-16T20:21:15.228104 #414] FATAL -- :   
production.log.2.gz:AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
production.log.2.gz:  
production.log.2.gz:app/controllers/application_controller.rb:170:in `bad_record_id'
```

**Comment by saracarl** [comment]
Other than these 2 instances, we have not seen any other instances of this error.  No instances in the last week.  Can't reproduce.
