### ISSUE TITLE
Display page 500 error

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2069]
Logs
```

production.log.1-I, [2020-09-17T09:45:43.689184 #32063]  INFO -- : Started GET "/sma-archives/city-of-seattle-records/991089/display/704757" for 157.55.39.233 at 2020-09-17 09:45:43 +0000
production.log.1-I, [2020-09-17T09:45:43.692137 #32063]  INFO -- : Processing by DisplayController#display_page as */*
production.log.1-I, [2020-09-17T09:45:43.692482 #32063]  INFO -- :   Parameters: {"user_slug"=>"sma-archives", "collection_id"=>"city-of-seattle-records", "work_id"=>"991089", "page_id"=>"704757"}
production.log.1-I, [2020-09-17T09:45:43.694311 #32063]  INFO -- : [ahoy] Visit excluded
production.log.1-I, [2020-09-17T09:45:43.723010 #32063]  INFO -- :   Rendering display/display_page.html.slim within layouts/application
production.log.1-I, [2020-09-17T09:45:43.736733 #32063]  INFO -- :   Rendered shared/_page_tabs.html.slim (Duration: 12.6ms | Allocations: 7776)
production.log.1-I, [2020-09-17T09:45:43.737744 #32063]  INFO -- :   Rendered display/display_page.html.slim within layouts/application (Duration: 14.0ms | Allocations: 8313)
production.log.1:I, [2020-09-17T09:45:43.739531 #32063]  INFO -- : Completed 500  in 47ms (ActiveRecord: 6.0ms | Allocations: 16324)
production.log.1-F, [2020-09-17T09:45:43.752424 #32063] FATAL -- :   
production.log.1-ActionView::Template::Error (undefined method `value' for nil:NilClass):
production.log.1-    52:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
production.log.1-    53:   }]
production.log.1-    54: 
production.log.1-    55: -description = xml_to_html(@page.xml_text)
production.log.1-    56: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
production.log.1-    57: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} page" : "page #{selected_tab.downcase}"
production.log.1-    58: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
production.log.1-  
production.log.1-app/helpers/abstract_xml_helper.rb:59:in `block in xml_to_html'
production.log.1-app/helpers/abstract_xml_helper.rb:48:in `xml_to_html'
production.log.1-app/views/shared/_page_tabs.html.slim:55
production.log.1-app/views/display/display_page.html.slim:1
production.log.1-app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by benwbrum** [comment]
Closing as obsolete.
