### ISSUE TITLE
Nil exception showing subjects (Logs P3)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2070]
Logs:
```

production.log.1-I, [2020-09-17T10:57:59.827084 #7612]  INFO -- : Started GET "/digitalindy/indianapolis-public-library/subjects" for 17.58.100.130 at 2020-09-17 10:57:59 +0000
production.log.1-I, [2020-09-17T10:57:59.830652 #7612]  INFO -- : Processing by ArticleController#list as HTML
production.log.1-I, [2020-09-17T10:57:59.831143 #7612]  INFO -- :   Parameters: {"user_slug"=>"digitalindy", "collection_id"=>"indianapolis-public-library"}
production.log.1-I, [2020-09-17T10:57:59.833840 #7612]  INFO -- : [ahoy] Visit excluded
production.log.1:I, [2020-09-17T10:57:59.868742 #7612]  INFO -- : Completed 500  in 37ms (ActiveRecord: 6.2ms | Allocations: 7730)
production.log.1-F, [2020-09-17T10:57:59.882768 #7612] FATAL -- :   
production.log.1-NoMethodError (undefined method `categories' for nil:NilClass):
production.log.1-  
production.log.1-app/controllers/article_controller.rb:21:in `list'
production.log.1-app/controllers/application_controller.rb:29:in `switch_locale'
```

**Comment by benwbrum** [comment]
Another example:
```

production.log.1-I, [2020-09-17T18:36:55.507388 #30459]  INFO -- : Started GET "/gavin/william-wenham-letters/subjects" for 207.46.13.169 at 2020-09-17 18:36:55 +0000
production.log.1-I, [2020-09-17T18:36:55.509841 #30459]  INFO -- : Processing by ArticleController#list as */*
production.log.1-I, [2020-09-17T18:36:55.510123 #30459]  INFO -- :   Parameters: {"user_slug"=>"gavin", "collection_id"=>"william-wenham-letters"}
production.log.1-I, [2020-09-17T18:36:55.511800 #30459]  INFO -- : [ahoy] Visit excluded
production.log.1:I, [2020-09-17T18:36:55.534010 #30459]  INFO -- : Completed 500  in 24ms (ActiveRecord: 3.8ms | Allocations: 7733)
production.log.1-F, [2020-09-17T18:36:55.541406 #30459] FATAL -- :   
production.log.1-NoMethodError (undefined method `categories' for nil:NilClass):
production.log.1-  
production.log.1-app/controllers/article_controller.rb:21:in `list'
production.log.1-app/controllers/application_controller.rb:29:in `switch_locale'
```
