### ISSUE TITLE
trouble creating account

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2082]
> production.log.4.gz:I, [2020-09-15T01:31:24.049031 #11103]  INFO -- : Processing by RegistrationsController#create as HTML
> production.log.4.gz:I, [2020-09-15T01:31:24.049402 #11103]  INFO -- :   Parameters: {"authenticity_token"=>"NcQNJfqXqaNT9L0yrxQv83xwVdhtVz2mk473psFSaR9uUTt8tcMPV1r6CDL01j86Z0RqLD1q/PexMPIgIri7Sg==", "user"=>{"login"=>"nickallen", "email"=>"nick@brainboostmedia.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "real_name"=>"Nick Allen", "owner"=>"false", "paid_date"=>"", "activity_email"=>"1"}, "g-recaptcha-response"=>"03AGdBq26yYmoZXnYUmflCBbDkUnfBs7gyQDaB8_ferhxSPsK4GZb8JEVQqQq8NqqobL8hlSNkm9UgzqOjquqVTVpSxN7_nfbhvYLkZbMlnFL-2MbpW9ZF9tdQnPk-CXieIhsrlqazq3btAtHakLLT00BmkvVXEnO4WLKc1cv1kEoJHAcVo3FnhkfewsNCwG_M0q4b-An0nOfTQNWkWR8Kz8jM12F5etbNU77Db8r6sn0AA3tuSTCSDniGU48LHorvx5V4YWiSZTeoPfK1P2A4cG_47G6eZnEDCwmdgT_hIqOfGr8aMTMt9eMkD-RwpR1XHrDaEuF1ZoHA1UOKtK09CmYh-z2Ov6VhtoLJiAwvDAij-Ym5DxIrD9VsR87vqTKyLDcdSvoz3AydUGOwkl5NeImnVV6Z5Su8CQbiiXLBRbU0v_RiQx-M1b8bsju4HSpJax3nXRmkNOPUlu84PUktxNLx4IudeX3rb7lRiLXVesyyLvdaMfGUxKWbRVBsemUFXRK7_VfNWXc3", "button"=>""}
> production.log.4.gz:I, [2020-09-15T01:31:24.237212 #11103]  INFO -- : Redirected to https://www.fromthepage.com/
> production.log.4.gz:I, [2020-09-15T01:31:24.244019 #11103]  INFO -- : Completed 500  in 194ms (ActiveRecord: 37.7ms | Allocations: 65487)
> production.log.4.gz:F, [2020-09-15T01:31:24.256722 #11103] FATAL -- :   
> production.log.4.gz:NoMethodError (undefined method `properties' for nil:NilClass):
> production.log.4.gz:  
> production.log.4.gz:app/controllers/registrations_controller.rb:103:in `joined_from_collection'
> production.log.4.gz:app/controllers/registrations_controller.rb:49:in `create'
> production.log.4.gz:app/controllers/application_controller.rb:29:in `switch_locale'
> production.log.4.gz:I, [2020-09-15T01:31:24.321603 #11103]  INFO -- : Started GET "/jeffdown1/c-s-peirce-manuscripts/needs_transcription?page=8" for 54.159.141.2 at 2020-09-15 01:31:24 +0000
> production.log.4.gz:I, [2020-09-15T01:31:24.324040 #11103]  INFO -- : Processing by CollectionController#needs_transcription_pages as */*
> production.log.4.gz:I, [2020-09-15T01:31:24.324335 #11103]  INFO -- :   Parameters: {"page"=>"8", "user_slug"=>"jeffdown1", "collection_id"=>"c-s-peirce-manuscripts"}
> production.log.4.gz:I, [2020-09-15T01:31:24.326033 #11103]  INFO -- : [ahoy] Visit excluded
> production.log.4.gz:I, [2020-09-15T01:31:24.340681 #11103]  INFO -- :   Rendering collection/needs_transcription_pages.html.slim within layouts/application
>

**Comment by saracarl** [comment]
Can't reproduce this.
