### ISSUE TITLE
500 error saving field based transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2149]
A customer is getting a 500 error when trying to save a field based transcriptions.  

It's a private project, found at:  https://fromthepage.com/ohiouniversitylibraries/dance-posters-metadata/

Looking at the error in the logs, I see:

```
I, [2020-11-10T15:04:10.443492 #19941]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2020-11-10T15:04:10.444125 #19941]  INFO -- :   Parameters: {"authenticity_token"=>"PvA/hh2tIe4Mtreg6hw3bJsZHOvSmJxjuKg2Q8Pw5Arn3mR60+TC7pqjGTgWxW4JaKNulfPr8vExJfTu1DYX4A==", "page_id"=>"1601564", "pa
ge"=>{"mark_blank"=>"0", "needs_review"=>"0"}, "save"=>"", "fields"=>{"2593"=>{"Title"=>"The Broken Mirror"}, "2594"=>{"name of performance if known or name of hosting organization"=>{" poster, "=>{"venue
 or location (city, state or country)"=>{", "=>{"name of dance company only if name of performance or hosting organization is not known"=>{" poster, "=>{"performance date range"=>{", "=>{"year"=>""}}}}}}}
}}, "2595"=>{"Creator (artist)"=>""}, "2596"=>{"Creator (artist) if other"=>""}, "2597"=>{"Creator (photographer)"=>""}, "2598"=>{"Creator (photographer) if other"=>""}, "2599"=>{"Creator (choreographer)"
=>""}, "2600"=>{"Creator (choreographer) if other"=>""}, "2601"=>{"Dance company"=>""}, "2602"=>{"Dance company if other"=>""}, "2603"=>{"Dance title"=>""}, "2604"=>{"Dance title if other"=>""}, "2605"=>{
"Language"=>""}, "2606"=>{"Date created (YYYY)"=>""}, "2607"=>{"Rights information"=>""}, "2608"=>{"Description"=>""}, "2609"=>{"dimensions"=>{" "=>{"physical description & format (color, black and white,
 mounted poster etc.)"=>{". Dance collection, series 7: press and promotion, sub series 7.2: posters. "=>""}}}}, "2610"=>{"Poster with "=>{"content description (briefly describe prominent imagery or desig
n elements)"=>{" advertising "=>{"name of dance company"=>{" performance, "=>{"year"=>{". Poster reads: "=>{"text transcribed from poster in quotes, sections separated with a semicolon"=>{"."=>""}}}}}}}}}
}}
I, [2020-11-10T15:04:10.497808 #19941]  INFO -- : Completed 500  in 53ms (ActiveRecord: 10.4ms | Allocations: 17297)
F, [2020-11-10T15:04:10.512337 #19941] FATAL -- :   
NoMethodError (undefined method `scan' for #<ActionController::Parameters:0x00007f2fcccd3c20>):
  
app/models/page.rb:286:in `block (2 levels) in process_fields'
app/models/page.rb:285:in `block in process_fields'
app/models/page.rb:278:in `process_fields'
app/controllers/transcribe_controller.rb:111:in `save_transcription'
```

Which is in the `process_fields` method in the page model.  I think it's this line, but am not positive:

https://github.com/benwbrum/fromthepage/blob/04b8d98436ab8df9ffbd7a0363d4b73597c8e83e/app/models/page.rb#L286

**Comment by saracarl** [comment]
I tried changing the field named "Title" to "Poster Title" and that didn't make a difference, so I don't think it's the hypothesis that the field has the same name as a parameter.

We're going to have to pull down a database dump and step through this in a development environment to figure out what's going on.

**Comment by saracarl** [comment]
The problem here is that some of the field labels had square braces in them, i.e.:

_Poster with [content description (briefly describe prominent imagery or design elements)] advertising [name of dance company] performance, [year]. Poster reads: [text transcribed from poster in quotes, sections separated with a semicolon]._

Those square braces cause the CGI parameters (rails passes parameters with square braces to indicate nesting) to be messed up.
