### ISSUE TITLE
500 error displaying page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2155]
A transcriber is having trouble displaying this (already transcribed) page:
https://fromthepage.com/kstatelibraries/manuscript-cookbooks/ksul-uasc-mscc220/display/1490772

She gets a 500 error.  Logs below:

```
I, [2020-11-12T00:16:51.790803 #17129]  INFO -- : Started GET "/kstatelibraries/manuscript-cookbooks/ksul-uasc-mscc220/display/1490772" for 70.112.51.192 at 2020-11-12 00:16:51 +0000
I, [2020-11-12T00:16:51.793971 #17129]  INFO -- : Processing by DisplayController#display_page as HTML
I, [2020-11-12T00:16:51.794346 #17129]  INFO -- :   Parameters: {"user_slug"=>"kstatelibraries", "collection_id"=>"manuscript-cookbooks", "work_id"=>"ksul-uasc-mscc220", "page_id"=>"1490772"}
I, [2020-11-12T00:16:51.808697 #17108]  INFO -- :   Rendering display/display_page.html.slim within layouts/application
I, [2020-11-12T00:16:51.817768 #17129]  INFO -- :   Rendering display/display_page.html.slim within layouts/application
I, [2020-11-12T00:16:51.835171 #17129]  INFO -- :   Rendered shared/_page_tabs.html.slim (Duration: 16.3ms | Allocations: 9031)
I, [2020-11-12T00:16:51.836177 #17129]  INFO -- :   Rendered display/display_page.html.slim within layouts/application (Duration: 17.8ms | Allocations: 9575)
I, [2020-11-12T00:16:51.838265 #17129]  INFO -- : Completed 500  in 44ms (ActiveRecord: 4.5ms | Allocations: 18330)
F, [2020-11-12T00:16:51.849944 #17129] FATAL -- :   
ActionView::Template::Error (undefined method `value' for nil:NilClass):
    52:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
    53:   }]
    54: 
    55: -description = xml_to_html(@page.xml_text)
    56: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
    57: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} page" : "page #{selected_tab.downcase}"
    58: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
  
app/helpers/abstract_xml_helper.rb:59:in `block in xml_to_html'
app/helpers/abstract_xml_helper.rb:48:in `xml_to_html'
app/views/shared/_page_tabs.html.slim:55
app/views/display/display_page.html.slim:1

```

You can see the page and the transcript in this view, though:

https://fromthepage.com/kstatelibraries/manuscript-cookbooks/ksul-uasc-mscc220?page=65

**Comment by saracarl** [comment]
This is caused by a "-" by itself on a line of transcribed text.  (We're trying to handle it like it's a - at the end of a line.)

The problem line:
Cake – coffee\r\n\r\n-\r\nOrange juice

```
>> @page.source_text
=> "382\r\nDinner-\r\nTomato juice–\r\nChicken croquettes with cinnamon apples–\r\nsliced with green cherry or olives in center \r\nparsley garnish– Creamed potatoes–\r\nsweet potatoes page 68 - Creamed asparagus on toast \r\nPear and pineapple salad page 86 - with \r\nwafers or ginger fruit salad page 90-\r\nOrange mousse. Cake – coffee\r\n\r\n-\r\nOrange juice-\r\nNoddle ring with creamed chicken\r\nand mushrooms - 2 veg rolls & coffee\r\nGelatin salad\r\nPlum Pudding coffee\r\nQueeen of Trifles\r\n\r\nLunch for circle May 1st '44\r\nSpaghetti\r\nLeon ice box pie\r\nSandwiches coffee\r\n\r\n"
```

**Comment by saracarl** [comment]
We're going to fix it by hacking the page text itself in the DB, but we should fix the code so it handles this.

**Comment by benwbrum** [comment]
The specific problem is a single hyphen on its own line at the beginning of a paragraph.
