### ISSUE TITLE
500 error rendering pages with newline/hyphen combinations

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2170]
URL is this: https://fromthepage.com/yale/langston-hughes/1927-trip-south-memphis-new-orleans-havana-mobile-tuskegee-zora-new-york/display/1286625

Exception in the logs is this:
```
F, [2020-11-24T23:04:54.735653 #5776] FATAL -- :   
ActionView::Template::Error (undefined method `value' for nil:NilClass):
    52:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
    53:   }]
    54: 
    55: -description = xml_to_html(@page.xml_text)
    56: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
    57: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} page" : "page #{selected_tab.downcase}"
    58: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
  
app/helpers/abstract_xml_helper.rb:59:in `block in xml_to_html'
app/helpers/abstract_xml_helper.rb:48:in `xml_to_html'
app/views/shared/_page_tabs.html.slim:55
app/views/display/display_page.html.slim:1
app/controllers/application_controller.rb:29:in `switch_locale'
```

XML text is this:
```
<?xml version='1.0' encoding='UTF-8'?>    
      <page>
        <p>Wheeled Schools - W.J. Muddy<lb/>in "Better Crops with Plant<lb/>Food." <lb/>The more ignorant a<lb/>man is the more<lb/>difficult it is to <lb/>get him to learn.</p><p>Millions of Negro farmers<lb/>in South.</p><p>"simple principles of <lb/>learning by doing."</p><p><lb break='no'/>Doorsteps<lb/>- <lb/>Their schoolgrounds<lb/>The open air. </p>
      </page>
```

Source text is this:
```
Wheeled Schools - W.J. Muddy
in "Better Crops with Plant
Food." 
The more ignorant a
man is the more
difficult it is to 
get him to learn.

Millions of Negro farmers
in South. 

"simple principles of 
learning by doing."

-
Doorsteps
- 
Their schoolgrounds
The open air. 
```

**Comment by saracarl** [comment]
Code causing the problem is:

```
  if preserve_lb
        if e.attributes['break'] == "no"
          sib = e.previous_sibling
          if sib.kind_of? REXML::Element
            sib.add_text('-')
          else
            sib.value=sib.value+'-'
          end
        end
        e.replace_with(REXML::Element.new('br'))

```
https://github.com/benwbrum/fromthepage/blob/fromthepage.com/app/helpers/abstract_xml_helper.rb#L59

which implies it's the - in between lines.

**Comment by benwbrum** [comment]
In this case, there is no previous sibling -- the newline with a hyphen begins a paragraph.
