### ISSUE TITLE
500 error saving transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2216]
```[2020-12-10T20:35:40.407061 #13245]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2020-12-10T20:35:40.407657 #13245]  INFO -- :   Parameters: {"authenticity_token"=>"874wQlyz3NCbbCkGKMO3tq4E9K+NxdvTMlb778Sjmg
Y+Ydj7/3TE9g57JdbmiWgQG+bNrOmULr80fFyS9nHoZw==", "page_id"=>"1653599", "page"=>{"mark_blank"=>"0", "needs_review"=>"0", "source_te
xt"=>"Vicksburg, Miss.\r\nJuly 24<sup>th</sup> <sub>\"</sub> 1861.\r\n\r\nHis Excellency Jno. J. Pettus\r\n\r\nDear Sir\r\n\r\nI w
rite to ask You if the Proper Arms and equipments can and will be furnished by the State for a Company of Mounted Rifles, should t
he same be <u>organized for State Service</u>!!!\r\n\r\nI write this on behalf of several Gentlement who are now associated togeth
er for the purpose of immediately organizing such a Company.\r\n\r\nI am Respectfully\r\nYour Obt. Sevt.\r\n\r\n\r\n\r\n\r\n"}, "s
ave"=>""}
I, [2020-12-10T20:35:40.417167 #13223]  INFO -- :   Rendered shared/_osd_div.html.slim (Duration: 52.4ms | Allocations: 1817)
I, [2020-12-10T20:35:40.441547 #13223]  INFO -- :   Rendered notes/_notes.html.slim (Duration: 7.0ms | Allocations: 1632)
W, [2020-12-10T20:35:40.442504 #13245]  WARN -- : Can't verify CSRF token authenticity.
I, [2020-12-10T20:35:40.442596 #13223]  INFO -- :   Rendered shared/_collection_footer.html.slim (Duration: 0.2ms | Allocations: 5
0)
I, [2020-12-10T20:35:40.443159 #13223]  INFO -- :   Rendered display/display_page.html.slim within layouts/application (Duration: 
119.5ms | Allocations: 57686)
I, [2020-12-10T20:35:40.444822 #13223]  INFO -- :   Rendered layouts/_mixpanel.erb (Duration: 0.1ms | Allocations: 48)
I, [2020-12-10T20:35:40.445612 #13223]  INFO -- :   Rendered layouts/_fb_pixel.erb (Duration: 0.1ms | Allocations: 48)
I, [2020-12-10T20:35:40.450794 #13223]  INFO -- :   Rendered shared/_breadcrumbs.html.slim (Duration: 0.8ms | Allocations: 144)
I, [2020-12-10T20:35:40.452978 #13223]  INFO -- :   Rendered layouts/_ga.erb (Duration: 0.2ms | Allocations: 48)
I, [2020-12-10T20:35:40.453832 #13223]  INFO -- : [ahoy] Event excluded
I, [2020-12-10T20:35:40.454972 #13223]  INFO -- : Completed 200 OK in 147ms (Views: 76.4ms | ActiveRecord: 57.8ms | Allocations: 6
7169)
I, [2020-12-10T20:35:40.455412 #13223]  INFO -- : Oink Action: display#display_page
I, [2020-12-10T20:35:40.455664 #13223]  INFO -- : Memory usage: 946696 | PID: 13223
I, [2020-12-10T20:35:40.455866 #13223]  INFO -- : Instantiation Breakdown: Total: 9 | Page: 4 | PageBlock: 2 | Work: 1 | Collectio
n: 1 | User: 1
I, [2020-12-10T20:35:40.456062 #13223]  INFO -- : Oink Log Entry Complete
I, [2020-12-10T20:35:40.479053 #13245]  INFO -- : Completed 500  in 71ms (ActiveRecord: 9.7ms | Allocations: 14501)
F, [2020-12-10T20:35:40.495447 #13245] FATAL -- :   
NoMethodError (undefined method `id' for nil:NilClass):
  
app/controllers/transcribe_controller.rb:375:in `log_attempt'
app/controllers/transcribe_controller.rb:406:in `log_transcript_attempt'
app/controllers/transcribe_controller.rb:134:in `save_transcription'
app/controllers/application_controller.rb:36:in `switch_locale'
```

**Comment by benwbrum** [comment]
The transcript saves fine when I attempt it.

**Comment by saracarl** [comment]
The failure seems to be a save transcription failure and the logging doesn't work.  

https://github.com/benwbrum/fromthepage/blob/fromthepage.com/app/controllers/transcribe_controller.rb#L375

the "id" that we can't get from a nil is current_user.id.

**Comment by benwbrum** [comment]
Note that this is the page in question: https://fromthepage.com/cwrgm/cwrgm-public/letter-from-t-w-hollis-to-mississippi-governor-john-j-pettus-july-24-1861/versions/1653599

```
Vicksburg, Miss.
July 24<sup>th</sup> <sub>"</sub> 1861.

His Excellency Jno. J. Pettus

Dear Sir

I write to ask You if the Proper Arms and equipments can and will be furnished by the State for a Company of Mounted Rifles, should the same be <u>organized for State Service</u>!!!

I write this on behalf of several Gentlement who are now associated together for the purpose of immediately organizing such a Company.

I am Respectfully
Your Obt. Sevt.
```

**Comment by saracarl** [comment]
This was caused by the user logging out in another tab.  We're discussing ways to use the "still editing" ping to catch that and throw a message.

**Comment by benwbrum** [comment]
This should have been resolved in the still-editing warnings we added when there is no connectivity or the user has logged out.
