### ISSUE TITLE
500 error exporting table CSV

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2490]
NCDCR is reporting this after they attempt to export a table csv:

```
I, [2021-04-08T09:14:54.345782 #15146]  INFO -- : Completed 500  in 8496ms (ActiveRecord: 720.7ms | Allocations: 4389564)
F, [2021-04-08T09:14:55.266587 #15146] FATAL -- :   
NoMethodError (undefined method `*' for nil:NilClass):
  
app/controllers/concerns/export_service.rb:430:in `block in cell_data'
app/controllers/concerns/export_service.rb:428:in `each'
app/controllers/concerns/export_service.rb:428:in `cell_data'
app/controllers/concerns/export_service.rb:366:in `block (2 levels) in generate_csv'
app/controllers/concerns/export_service.rb:364:in `each'
app/controllers/concerns/export_service.rb:364:in `block in generate_csv'
app/controllers/concerns/export_service.rb:339:in `generate_csv'
app/controllers/concerns/export_service.rb:330:in `block (2 levels) in export_tables_as_csv'
app/controllers/concerns/export_service.rb:329:in `each'
app/controllers/concerns/export_service.rb:329:in `block in export_tables_as_csv'
app/controllers/concerns/export_service.rb:303:in `export_tables_as_csv'
app/controllers/export_controller.rb:75:in `table_csv'
```

They have deleted some pages, so perhaps there are orphan records involved here.

**Comment by benwbrum** [comment]
This does not appear to be a problem with orphan table cell records.

**Comment by benwbrum** [comment]
This issue has been resolved in other code.  (probably #2509)
