### ISSUE TITLE
500 error processing original_metadata into facets

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2636]
Importing [this manifest](https://curio.lib.utexas.edu/assets/DAMS/utblac/utblac_3affb1e7-0e19-4c34-944b-d57313f05482/manifests/2/utblac_3affb1e7-0e19-4c34-944b-d57313f05482.json) from the UT DAMS into the Relaciones Geographicas (which is configured to use facets) produces this exception

```
D, [2021-06-17T16:29:25.508019 #5259] DEBUG -- :   [1m[36mMetadataCoverage Load (0.1ms)[0m  [1m[34mSELECT `metadata_coverages`.* FROM `metadata_coverages` WHERE `metadata_coverages`.`id` = 32 LIMIT 1[0m
I, [2021-06-17T16:29:25.512318 #5259]  INFO -- : Completed 500  in 747ms (ActiveRecord: 113.6ms | Allocations: 383888)
F, [2021-06-17T16:29:25.742908 #5259] FATAL -- :   
NoMethodError (undefined method `match' for {"@value"=>"Spanish", "@language"=>"en"}:Hash):
  
app/models/facet_config.rb:38:in `block (2 levels) in update_work_facet'
app/models/facet_config.rb:27:in `each'
app/models/facet_config.rb:27:in `block in update_work_facet'
app/models/facet_config.rb:26:in `update_work_facet'
app/models/facet_config.rb:61:in `update_facets'
app/models/work.rb:316:in `save_metadata'
app/models/sc_manifest.rb:64:in `convert_with_collection'
app/controllers/sc_collections_controller.rb:196:in `convert_manifest'
app/controllers/application_controller.rb:48:in `switch_locale'
```

**Comment by benwbrum** [comment]
I've duplicated this locally by importing the problem manifest into a collection, enabling facets, then making `Language` the only facet.  It appears that UT is adopting multi-lingual pairs for metadata values, which we don't yet support.

See the problem element in the error message:
```
undefined method `match' for {"@value"=>"Spanish", "@language"=>"en"}:Hash
```
