### ISSUE TITLE
Handle users entering HTML better

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#267]
Rebecca Nesvet reports a problem saving a transcript:
![screenshot from 2015-12-23 08 06 32](https://cloud.githubusercontent.com/assets/199961/11977848/22626ade-a94c-11e5-867a-dded419b3ff2.png)

Further investigation reveals this in the logs:

```
I, [2015-11-22T06:37:54.034784 #21971]  INFO -- : TRANSCRIPTION 2015-11-22 06:37:54 +0000
TRANSCRIPTION   User    ID: 538 Email: ... Display Name: Rebecca Nesvet
TRANSCRIPTION   Collection      ID: 40  Title:The James Malcolm Rymer Collection        Owner Email: ...
TRANSCRIPTION   Work    ID: 136 Title: The String of pearls, or, The barber of Fleet Street; A Domestic Romance (London: Lloyd, 1850)
TRANSCRIPTION   Page    ID: 6682        Position: 107   Title:The String of Pearls (1850), p. 101
TRANSCRIPTION   Source Text:
BEGIN_SOURCE_TEXT
CHAPTER XVIII.

THE MISADVENTURE Of TOBIAS,— THE MAD-HOUSE ON PECKHAM-RYE.
</p>
<p>
Sweeney Todd paused for a moment at the cupboard door, before he made up his mind as to whether he should pounce upon poor Tobias at once, or adopt a more creeping, cautious mode of operation. The latter course was by far the most congenial to his mind, and so he adopted it in a moment or so, and stole quietly from his place of concealment, and with so little noise, that Tobias could not have the least suspicion that any one was in the room but 4iimself. Treading, as if each step might involve some serious consequences, he thus at length got completely behind the chair on which Tobias was sitting, and stood with folded arms, and such a hideous smile upon his face, that they together formed no inapt representation of the <sic>Mephistophiles</sic> of the German drama.
</p>
<p>
"I shall at length," murmured Tobias, " be free from my present dreadful state of mind, by thus accusing Todd. He is a murderer&#8212;of that I have no doubt: it is but a duty of mine to stand forward as his accuser."
</p>
<p>
Sweeney Todd stretched out his two brawny hands, and clutched Tobias by the head, which he turned round till the boy could see him, and then he said&#8212;
</p>
<p>
"Indeed, Tobias ; and did it never strike you that Todd was not so easily to be overcome as you would wish him, eh, Tobias?"
</p>
<p>
The shock of this astonishing and sudden appearance of Sweeney Todd was so great, that for a few moments Tobias was deprived of all power of speech or action, and with his head so strangely twisted as to seem to threaten the destruction of his neck. He glared in the triumphant and malignant countenance of his persecutor, as he would into that of the arch enemy of all mankind, which probably he now began to think the barber really was* If one thing more than another was calculated to delight such a man as Todd, it certainly was to perceive what a dreadful effect his presence had upon Tobias, who remained for about a
minute and a half in this state before he ventured upon uttering a shriek, which, however, when it did come, almost frightened Todd himself. It was one of those cries which can only come from a heart in its utmost agony — a cry which might have heralded the spirit to another world, and proclaimed, ' as it very nearly did
the destruction of the intellect for ever. The barber staggered back a pace or two as he heard it, for it was too terrific even for him, but it was for a very brief period that it had that stunning effect upon him, and then, with a full consciousness of the danger to which it subjected him, he sprang upon poor Tobias as a tiger
might be supposed to do upon a lamb, and clutched him by the throat, exclaiming&#8212;
</p>
<p>
"Such another cry, and it is the last you ever live to utter, although it cover me with difficulties to escape the charge of killing you. Peace! I say, peace!" 
</p>
<p>
This exhortation was quite needless, for Tobias could not have uttered a word, had he been ever so much inclined to do so ; the barber held his throat with such an iron clutch, as if it had been in a vice.
</p>
<p>
"Villain," growled Todd, "villain; so this is the way in which you have dared to disregard my injunctions. Bat no matter, no matter!&#8212;you shall have plenty of leisure to reflect upon what you have done for yourself. Fool ! to think that you could cope with me&#8212;Sweeney Todd! Ha! ha!"
</p>
<p>
He burst into a laugh, so much more hideous, than his ordinary efforts in that way, that, had Tobias heard it#8212;which he did not, for his head had dropped upon his breast, and he had become insensible#8212;it would have terrified him almost as much as Sweeney Todd's sudden appearance had done.
</p>
<p>
" So," muttered the barber, " he has fainted, has he? Dull child, that is all the better. For once in a way, Tobias, I will carry you&#8212;not to oblige you, but to oblige myself. By all that's damnable, it was a lively thought that brought me here to-night, or else I might, by the dawn of the morning, have had some very troublesome inquiries made of me."
<pb n="102/>

END_SOURCE_TEXT


E, [2015-11-22T06:37:54.058385 #21971] ERROR -- : TRANSCRIPTION 2015-11-22 06:37:54 +0000       ERROR   EXCEPTION       #<REXML::ParseException: malformed XML: missing tag start
Line: 4
Position: 4399
Last 80 unconsumed characters:
<pb n="102/><lb/></p>       </page> >
/usr/share/ruby/rexml/parsers/baseparser.rb:372:in `pull_event'
/usr/share/ruby/rexml/parsers/baseparser.rb:183:in `pull'
/usr/share/ruby/rexml/parsers/treeparser.rb:22:in `parse'
/usr/share/ruby/rexml/document.rb:283:in `build'
/usr/share/ruby/rexml/document.rb:43:in `initialize'
/home/fromthepage/deployment/releases/20151115233938/app/models/xml_source_processor.rb:181:in `new'
/home/fromthepage/deployment/releases/20151115233938/app/models/xml_source_processor.rb:181:in `update_links_and_xml'
/home/fromthepage/deployment/releases/20151115233938/app/models/xml_source_processor.rb:85:in `wiki_to_xml'
/home/fromthepage/deployment/releases/20151115233938/app/models/xml_source_processor.rb:70:in `process_source'
/home/fromthepage/.gem/ruby/gems/activesupport-4.1.2/lib/active_support/callbacks.rb:424:in `block in make_lambda'
```

Based on this, the source of the problem was a `</p>` with no corresponding open tag in the transcript.

We should deal more gracefully with users entering HTML or TEI tags like `p` which would ordinarily be handled via wiki-text.  Obviously the error experience needs to be better than the screen of red text Rebecca experienced.  However, perhaps we should suggest users entering tags like `p` or `pb` that these will be generated by the application itself?

**Comment by tbl73** [comment]
An error occurs on saving if the HTML tag isn't properly closed, so I think this has already been fixed.
