### ISSUE TITLE
Error exporting pdf

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2683]
```
I, [2021-07-17T13:50:49.184675 #50484]  INFO -- : Completed 500  in 127ms (ActiveRecord: 11.8ms | Allocations: 18499)
F, [2021-07-17T13:50:49.191692 #50484] FATAL -- :   
Errno::ENOENT (No such file or directory @ rb_sysopen - /home/fromthepage/fromthepage/public/printable/20210717185049/expediente_sobre_los_indios_del_pueblo_guasitzazongo_que_vayan_a_los_oficios_divinos_y_a_recebir_los_santos_sacramentos_al_pueblo_de_tenango_1566_491_20210717185049.pdf):
  
app/controllers/export_controller.rb:40:in `read'
app/controllers/export_controller.rb:40:in `printable'
app/controllers/application_controller.rb:48:in `switch_locale'
```

I wonder if they need to create public/printable?  @benwbrum what do you think?

**Comment by saracarl** [comment]
Exact same error when trying to download a docx

**Comment by saracarl** [comment]
https://fromthepage-t01.lib.utexas.edu/ap2253/early-modern-manuscripts-at-the-benson-latin-american-collection/expediente-sobre-los-indios-del-pueblo-guasitzazongo-que-vayan-a-los-oficios-divinos-y-a-recebir-los-santos-sacramentos-al-pueblo-de-tenango-1566-491/download

**Comment by saracarl** [comment]
Same for facing edition PDFs:

```
I, [2021-07-17T13:50:49.092554 #50484]  INFO -- :   Rendered export/facing_edition.html.erb (Duration: 14.8ms | Allocations: 9026)
I, [2021-07-17T13:50:49.157104 #50484]  INFO -- : pandoc -o /home/fromthepage/fromthepage/public/printable/20210717185049/expediente_sobre_los_indios_del_pueblo_guasitzazongo_que_vayan_a_los_oficios_divinos_y_a_recebir_los_santos_sacramentos_al_pueblo_de_tenango_1566_491_20210717185049.pdf /home/fromthepage/fromthepage/public/printable/20210717185049/expediente_sobre_los_indios_del_pueblo_guasitzazongo_que_vayan_a_los_oficios_divinos_y_a_recebir_los_santos_sacramentos_al_pueblo_de_tenango_1566_491_20210717185049.md --pdf-engine=xelatex --verbose > /home/fromthepage/fromthepage/public/printable/20210717185049/expediente_sobre_los_indios_del_pueblo_guasitzazongo_que_vayan_a_los_oficios_divinos_y_a_recebir_los_santos_sacramentos_al_pueblo_de_tenango_1566_491_20210717185049.log 2>&1
I, [2021-07-17T13:50:49.184675 #50484]  INFO -- : Completed 500  in 127ms (ActiveRecord: 11.8ms | Allocations: 18499)
F, [2021-07-17T13:50:49.191692 #50484] FATAL -- :   
Errno::ENOENT (No such file or directory @ rb_sysopen - /home/fromthepage/fromthepage/public/printable/20210717185049/expediente_sobre_los_indios_del_pueblo_guasitzazongo_que_vayan_a_los_oficios_divinos_y_a_recebir_los_santos_sacramentos_al_pueblo_de_tenango_1566_491_20210717185049.pdf):
```
