### ISSUE TITLE
Preview with  ==="First" Thing===

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2707]
` ==="First" Thing===`  causes problems in "preview"

Thom at MAC

**Comment by saracarl** [comment]
In preview mode, this generates:
```REXML::ParseException - Missing attribute equal: <First>
Line: 3
Position: 178
Last 80 unconsumed characters::
  app/models/xml_source_processor.rb:342:in `update_links_and_xml'
  app/models/xml_source_processor.rb:112:in `wiki_to_xml'
  app/controllers/transcribe_controller.rb:217:in `save_transcription'
  app/controllers/application_controller.rb:48:in `switch_locale'

```
If you save the same transcript, you get:

```
There was an error parsing the mark-up in your transcript. This kind of error often occurs if an angle bracket is missing or if an HTML tag is left open. Check any instances of < or > symbols in your text. (The parser error was: Missing attribute equal: Line: 3 Position: 178 Last 80 unconsumed characters: )
```
