### ISSUE TITLE
500 error uploading subjects with diacritics

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2915]
Colin at Dartmouth reports:

> Happy new year!  I was working on adding some subjects to a collection using the csv upload, and I ran into issues (500 error) when the file contained subjects that contained diacritics.  I was able to upload the attached file piecemeal, eventually realizing that the diacritics in rows 13 and 18 were causing the upload to fail.  I edited the csv to remove the special characters and was able to add them back, once the subjects had been uploaded into FromThePage.  Just an FYI.

[subjects.csv](https://github.com/benwbrum/fromthepage/files/7799172/subjects.csv)

**Comment by benwbrum** [comment]
The problem appears to be with non-UTF-8 encoding:
```
CSV::MalformedCSVError - Invalid byte sequence in UTF-8 in line 13.:
  app/controllers/article_controller.rb:208:in `subject_upload'
  app/controllers/application_controller.rb:48:in `switch_locale'
```

Looking at the sample file shows non-UTF-8
```
benwbrum@sparckjones:~$ file ~/Downloads/subjects.csv 
/home/benwbrum/Downloads/subjects.csv: ISO-8859 text, with CRLF line terminators
```
Verification of the fix should
* test that the upload does not error
* Verify that a subject in the People category has the title `Joseph-Elzéar Bernier`
