### ISSUE TITLE
Work title - rename - sometimes fails

### ISSUE THREAD

**Issue by plutext** [benwbrum/fromthepage#2990]
I'm renaming works where necessary for alphabetical sort.  For example, renaming "85" to "085".

I do this on the Work > Settings tab.

Usually this works fine, but it fails around 10% of the time.  No error message in the UI when you hit "save changes"; it does say "work updated successfully"

But the work title doesn't change in the works list.  And if you try again for that particular work, the behaviour is the same.

So far I can't see a pattern to the failures.

Here are the work titles I've been unable to rename, for what its worth:

```
26_f12

53.

76_4303

81_4403

86_4510

94.

96.

D_195
```

**Comment by benwbrum** [comment]
Jason, do you have access to the log files when this happens?  I'm wondering if an error is being thrown which we're swallowing instead of displaying.

(Incidentally, if you're logged in as an admin user, there is a Logfile tab on the admin dashboard that prevents you from having to ssh in.)

**Comment by plutext** [comment]
Nothing stands out to me at a glance:

```
Oink Action: work#edit
Memory usage: 1401704 | PID: 31576
Instantiation Breakdown: Total: 18 | User: 8 | Collection: 6 | Work: 1 | PageBlock: 1 | Visit: 1 | Ahoy::Event: 1
Oink Log Entry Complete
Started POST "/work/update?id=135" for 58.107.234.187 at 2022-02-08 23:56:11 +0000
Processing by WorkController#update as HTML
  Parameters: {"authenticity_token"=>"/Ba2e9+u0W8nhSoxk1JYZTdM4PlPZJVpvX66m/LZ9PHcWyeeZgq+a16QWgj3dgx9ydmQhv5FKSEoKlcEIImSLg==", "collection_id"=>"wiltshire-1369-7-2-20", "work"=>{"title"=>"096.", "collection_id"=>"4", "slug"=>"96", "identifier"=>"", "pages_are_meaningful"=>"1", "ocr_correction"=>"0", "description"=>"", "transcription_conventions"=>"<p><b>Transcription Conventions</b>\r\n<ul><li><i>Spelling: </i>Use original spelling if possible.</li>\r\n <li><i>Capitalization: </i>Retain original capitalization.</li>\r\n<li><i>Punctuation: </i>Use original punctuation when possible.</li>\r\n<li><i>Line Breaks: </i>Hit <code>Enter</code> once after each line ends.  Two returns indicate a new paragraph, whether indicated by a blank line or by indentation in the original.</li></ul>", "supports_translation"=>"0", "translation_instructions"=>"", "author"=>"", "location_of_composition"=>"", "document_date"=>"", "genre"=>"", "source_location"=>"", "source_collection_name"=>"", "source_box_folder"=>"", "in_scope"=>"1", "editorial_notes"=>"", "physical_description"=>"", "document_history"=>"", "permission_description"=>""}, "button"=>"", "id"=>"135"}
  [1m[36mUser Load (1.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:57:in `current_user'
  [1m[36mCollection Exists? (0.9ms)[0m  [1m[34mSELECT 1 AS one FROM `collections` WHERE `collections`.`slug` = 'wiltshire-1369-7-2-20' LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:168:in `set_friendly_collection'
  [1m[36mCollection Load (0.9ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` WHERE `collections`.`slug` = 'wiltshire-1369-7-2-20' LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:169:in `set_friendly_collection'
  [1m[36mPageBlock Load (0.9ms)[0m  [1m[34mSELECT `page_blocks`.* FROM `page_blocks` WHERE `page_blocks`.`controller` = 'work' AND `page_blocks`.`view` = 'update'[0m
  ↳ app/controllers/application_controller.rb:238:in `load_html_blocks'
  [1m[36mWork Load (0.8ms)[0m  [1m[34mSELECT `works`.* FROM `works` WHERE `works`.`slug` = '135' LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:130:in `update'
  [1m[36mWork Load (1.1ms)[0m  [1m[34mSELECT `works`.* FROM `works` INNER JOIN `friendly_id_slugs` ON `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`sluggable_id` = `works`.`id` WHERE `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`slug` = '135' ORDER BY `friendly_id_slugs`.`id` DESC LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:130:in `update'
  [1m[36mCollection Load (0.9ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` WHERE `collections`.`id` = 4 LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:136:in `update'
  [1m[35m (0.9ms)[0m  [1m[35mBEGIN[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Exists? (1.3ms)[0m  [1m[34mSELECT 1 AS one FROM `works` INNER JOIN `friendly_id_slugs` ON `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`sluggable_id` = `works`.`id` WHERE `works`.`id` != 28 AND (sluggable_id <> 28) AND `works`.`slug` = '96' LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Exists? (1.0ms)[0m  [1m[34mSELECT 1 AS one FROM `works` WHERE `works`.`slug` = BINARY '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' AND `works`.`id` != 28 LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Exists? (1.0ms)[0m  [1m[34mSELECT 1 AS one FROM `works` INNER JOIN `friendly_id_slugs` ON `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`sluggable_id` = `works`.`id` WHERE `works`.`id` != 28 AND (sluggable_id <> 28) AND `works`.`slug` = '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Exists? (1.0ms)[0m  [1m[34mSELECT 1 AS one FROM `works` INNER JOIN `friendly_id_slugs` ON `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`sluggable_id` = `works`.`id` WHERE `works`.`id` != 28 AND (sluggable_id <> 28) AND `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`slug` = '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Update (1.1ms)[0m  [1m[33mUPDATE `works` SET `works`.`slug` = '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' WHERE `works`.`id` = 28[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mFriendlyId::Slug Load (1.0ms)[0m  [1m[34mSELECT `friendly_id_slugs`.* FROM `friendly_id_slugs` WHERE `friendly_id_slugs`.`sluggable_id` = 28 AND `friendly_id_slugs`.`sluggable_type` = 'Work' ORDER BY `friendly_id_slugs`.`id` DESC LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mFriendlyId::Slug Exists? (0.9ms)[0m  [1m[34mSELECT 1 AS one FROM `friendly_id_slugs` WHERE `friendly_id_slugs`.`sluggable_id` = 28 AND `friendly_id_slugs`.`sluggable_type` = 'Work' AND `friendly_id_slugs`.`slug` = '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWork Load (1.2ms)[0m  [1m[34mSELECT `works`.* FROM `works` WHERE `works`.`id` = 28 LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mFriendlyId::Slug Create (1.0ms)[0m  [1m[32mINSERT INTO `friendly_id_slugs` (`slug`, `sluggable_id`, `sluggable_type`, `created_at`) VALUES ('96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6', 28, 'Work', '2022-02-08 23:56:11')[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mWorkStatistic Load (1.0ms)[0m  [1m[34mSELECT `work_statistics`.* FROM `work_statistics` WHERE `work_statistics`.`work_id` = 28 LIMIT 1[0m
  ↳ app/models/work.rb:193:in `update_statistic'
  [1m[35m (1.0ms)[0m  [1m[34mSELECT COUNT(*) AS count_all, `pages`.`status` AS pages_status FROM `pages` WHERE `pages`.`work_id` = 28 GROUP BY `pages`.`status` ORDER BY position[0m
  ↳ app/models/work_statistic.rb:107:in `get_stats_hash'
  [1m[35m (1.0ms)[0m  [1m[34mSELECT COUNT(*) AS count_all, `pages`.`translation_status` AS pages_translation_status FROM `pages` WHERE `pages`.`work_id` = 28 GROUP BY `pages`.`translation_status` ORDER BY position[0m
  ↳ app/models/work_statistic.rb:108:in `get_stats_hash'
  [1m[35m (0.9ms)[0m  [1m[34mSELECT COUNT(*) FROM `pages` WHERE `pages`.`work_id` = 28[0m
  ↳ app/models/work_statistic.rb:109:in `get_stats_hash'
  [1m[35m (1.0ms)[0m  [1m[34mSELECT COUNT(*) FROM `works` WHERE `works`.`collection_id` = 4[0m
  ↳ app/models/collection_statistic.rb:3:in `work_count'
  [1m[36mWork Load (1.7ms)[0m  [1m[34mSELECT `works`.* FROM `works` WHERE `works`.`collection_id` = 4 ORDER BY title[0m
  ↳ app/models/collection_statistic.rb:83:in `map'
  [1m[36mWorkStatistic Load (1.6ms)[0m  [1m[34mSELECT `work_statistics`.* FROM `work_statistics` WHERE `work_statistics`.`work_id` IN (5, 6, 7, 8, 9, 15, 35, 47, 59, 80, 98, 11, 104, 105, 106, 107, 108, 109, 110, 111, 112, 17, 114, 115, 116, 117, 118, 119, 120, 121, 122, 21, 124, 22, 126, 127, 128, 129, 24, 131, 132, 133, 26, 28, 136, 10, 12, 13, 14, 16, 18, 19, 20, 23, 25, 27, 4, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 65, 29, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102, 103, 113, 123, 125, 130, 134, 135, 137)[0m
  ↳ app/models/collection_statistic.rb:83:in `map'
  [1m[35mCACHE  (0.0ms)[0m  [1m[34mSELECT COUNT(*) FROM `works` WHERE `works`.`collection_id` = 4[0m
  ↳ app/models/collection_statistic.rb:3:in `work_count'
  [1m[36mFriendlyId::Slug Load (1.4ms)[0m  [1m[34mSELECT `friendly_id_slugs`.* FROM `friendly_id_slugs` WHERE `friendly_id_slugs`.`sluggable_id` = 4 AND `friendly_id_slugs`.`sluggable_type` = 'Collection' ORDER BY `friendly_id_slugs`.`id` DESC LIMIT 1[0m
  ↳ app/models/collection_statistic.rb:87:in `calculate_complete'
  [1m[36mCategory Exists? (1.2ms)[0m  [1m[34mSELECT 1 AS one FROM `categories` WHERE `categories`.`title` = BINARY 'People' AND `categories`.`collection_id` = 4 AND `categories`.`parent_id` IS NULL LIMIT 1[0m
  ↳ app/models/collection.rb:113:in `create_categories'
  [1m[36mCategory Exists? (1.1ms)[0m  [1m[34mSELECT 1 AS one FROM `categories` WHERE `categories`.`title` = BINARY 'Places' AND `categories`.`collection_id` = 4 AND `categories`.`parent_id` IS NULL LIMIT 1[0m
  ↳ app/models/collection.rb:115:in `create_categories'
  [1m[36mWork Load (1.3ms)[0m  [1m[34mSELECT `works`.* FROM `works` INNER JOIN `work_statistics` ON `work_statistics`.`work_id` = `works`.`id` WHERE `works`.`collection_id` = 4 AND `works`.`next_untranscribed_page_id` IS NOT NULL ORDER BY work_statistics.complete ASC LIMIT 1[0m
  ↳ app/models/collection.rb:205:in `set_next_untranscribed_page'
  [1m[36mPage Load (1.1ms)[0m  [1m[34mSELECT `pages`.* FROM `pages` WHERE `pages`.`id` = 370 LIMIT 1[0m
  ↳ app/models/collection.rb:206:in `set_next_untranscribed_page'
  [1m[36mCollection Update (1.0ms)[0m  [1m[33mUPDATE `collections` SET `collections`.`next_untranscribed_page_id` = 370 WHERE `collections`.`id` = 4[0m
  ↳ app/models/collection.rb:209:in `set_next_untranscribed_page'
  [1m[36mDocumentSet Exists? (0.9ms)[0m  [1m[34mSELECT 1 AS one FROM `document_sets` INNER JOIN `document_sets_works` ON `document_sets`.`id` = `document_sets_works`.`document_set_id` WHERE `document_sets_works`.`work_id` = 28 LIMIT 1[0m
  ↳ app/models/work_statistic.rb:118:in `recalculate_parent_statistics'
  [1m[36mPage Load (1.1ms)[0m  [1m[34mSELECT `pages`.* FROM `pages` WHERE `pages`.`work_id` = 28 AND (`pages`.`status` = 'incomplete' OR `pages`.`status` IS NULL) ORDER BY position ASC LIMIT 1[0m
  ↳ app/models/work.rb:289:in `set_next_untranscribed_page'
  [1m[36mWork Update (0.9ms)[0m  [1m[33mUPDATE `works` SET `works`.`next_untranscribed_page_id` = 260 WHERE `works`.`id` = 28[0m
  ↳ app/models/work.rb:291:in `set_next_untranscribed_page'
  [1m[36mWork Load (1.2ms)[0m  [1m[34mSELECT `works`.* FROM `works` INNER JOIN `work_statistics` ON `work_statistics`.`work_id` = `works`.`id` WHERE `works`.`collection_id` = 4 AND `works`.`next_untranscribed_page_id` IS NOT NULL ORDER BY work_statistics.complete ASC LIMIT 1[0m
  ↳ app/models/collection.rb:205:in `set_next_untranscribed_page'
  [1m[36mPage Load (1.0ms)[0m  [1m[34mSELECT `pages`.* FROM `pages` WHERE `pages`.`id` = 370 LIMIT 1[0m
  ↳ app/models/collection.rb:206:in `set_next_untranscribed_page'
  [1m[36mCollection Update (0.9ms)[0m  [1m[33mUPDATE `collections` SET `collections`.`next_untranscribed_page_id` = 370 WHERE `collections`.`id` = 4[0m
  ↳ app/models/collection.rb:209:in `set_next_untranscribed_page'
  [1m[36mDocumentSet Exists? (0.9ms)[0m  [1m[34mSELECT 1 AS one FROM `document_sets` INNER JOIN `document_sets_works` ON `document_sets`.`id` = `document_sets_works`.`document_set_id` WHERE `document_sets_works`.`work_id` = 28 LIMIT 1[0m
  ↳ app/models/work.rb:281:in `update_next_untranscribed_pages'
  [1m[35m (3.5ms)[0m  [1m[35mCOMMIT[0m
  ↳ app/controllers/work_controller.rb:165:in `update'
  [1m[36mUser Load (1.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1[0m
  ↳ app/controllers/work_controller.rb:167:in `update'
Redirected to http://3.105.64.41:3000/matcham/wiltshire-1369-7-2-20/96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6/edit
  [1m[36mVisit Load (1.0ms)[0m  [1m[34mSELECT `visits`.* FROM `visits` WHERE `visits`.`visit_token` = '82a34f50-0ebb-4492-8a68-6017ed0869ce' ORDER BY `visits`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[35m (0.8ms)[0m  [1m[35mBEGIN[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[36mAhoy::Event Create (0.9ms)[0m  [1m[32mINSERT INTO `ahoy_events` (`visit_id`, `user_id`, `name`, `properties`, `time`) VALUES (678, 2, 'work#update', '{\"collection_id\":4,\"collection_title\":\"Wiltshire-1369-7-2-20 George Jnr family matters 1840s\",\"work_id\":28,\"work_title\":\"096.\"}', '2022-02-08 23:56:11')[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[35m (2.6ms)[0m  [1m[35mCOMMIT[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
Completed 302 Found in 177ms (ActiveRecord: 49.3ms | Allocations: 104079)


Oink Action: work#update
Memory usage: 1401704 | PID: 31576
Instantiation Breakdown: Total: 287 | Work: 138 | WorkStatistic: 135 | FriendlyId::Slug: 3 | Page: 3 | User: 2 | Collection: 2 | Category: 2 | Visit: 1 | Ahoy::Event: 1
Oink Log Entry Complete
Started GET "/matcham/wiltshire-1369-7-2-20/96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6/edit" for 58.107.234.187 at 2022-02-08 23:56:11 +0000
Processing by WorkController#edit as HTML
  Parameters: {"user_slug"=>"matcham", "collection_id"=>"wiltshire-1369-7-2-20", "work_id"=>"96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6"}
  [1m[36mUser Load (1.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:57:in `current_user'
  [1m[36mWork Load (0.9ms)[0m  [1m[34mSELECT `works`.* FROM `works` WHERE `works`.`slug` = '96-3f12e78e-1e76-41a3-ad24-60b2f746e9e6' LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:130:in `load_objects_from_params'
  [1m[36mCollection Load (0.8ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` WHERE `collections`.`id` = 4 LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:131:in `load_objects_from_params'
  [1m[36mCollection Exists? (0.8ms)[0m  [1m[34mSELECT 1 AS one FROM `collections` WHERE `collections`.`slug` = 'wiltshire-1369-7-2-20' LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:168:in `set_friendly_collection'
  [1m[36mCollection Load (1.0ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` WHERE `collections`.`slug` = 'wiltshire-1369-7-2-20' LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:169:in `set_friendly_collection'
  [1m[36mIaWork Load (1.0ms)[0m  [1m[34mSELECT `ia_works`.* FROM `ia_works` WHERE `ia_works`.`work_id` = 28 LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:204:in `update_ia_work_server'
  [1m[36mPageBlock Load (1.1ms)[0m  [1m[34mSELECT `page_blocks`.* FROM `page_blocks` WHERE `page_blocks`.`controller` = 'work' AND `page_blocks`.`view` = 'edit'[0m
  ↳ app/controllers/application_controller.rb:238:in `load_html_blocks'
  Rendering inline template
  Rendered inline template (Duration: 0.4ms | Allocations: 72)
  [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1[0m
  ↳ app/models/user.rb:197:in `like_owner?'
  [1m[36mUser Load (0.8ms)[0m  [1m[34mSELECT `users`.* FROM `users`[0m
  ↳ app/controllers/work_controller.rb:81:in `edit'
  [1m[36mUser Load (0.9ms)[0m  [1m[34mSELECT `users`.* FROM `users` INNER JOIN `transcribe_authorizations` ON `users`.`id` = `transcribe_authorizations`.`user_id` WHERE `transcribe_authorizations`.`work_id` = 28[0m
  ↳ app/controllers/work_controller.rb:81:in `edit'
  [1m[36mCollection Load (0.9ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` INNER JOIN `collection_owners` ON `collections`.`id` = `collection_owners`.`collection_id` WHERE `collection_owners`.`user_id` = 2[0m
  ↳ app/models/user.rb:225:in `collections'
  [1m[36mCollection Load (1.0ms)[0m  [1m[34mSELECT `collections`.* FROM `collections` WHERE `collections`.`owner_user_id` = 2[0m
  ↳ app/models/user.rb:225:in `collections'
  [1m[35m (0.8ms)[0m  [1m[34mSELECT `pages`.`id` FROM `pages` WHERE `pages`.`work_id` = 28 ORDER BY position[0m
  ↳ app/models/work.rb:140:in `articles'
  [1m[36mArticle Load (1.2ms)[0m  [1m[34mSELECT DISTINCT `articles`.* FROM `articles` INNER JOIN `page_article_links` ON `page_article_links`.`article_id` = `articles`.`id` WHERE `page_article_links`.`page_id` IN (260, 261)[0m
  ↳ app/controllers/work_controller.rb:84:in `edit'
  Rendering work/edit.html.slim within layouts/application
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/shared/_work_tabs.html.slim:4
  Rendered shared/_work_tabs.html.slim (Duration: 3.9ms | Allocations: 2758)
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/work/edit.html.slim:140
  Rendered shared/_profile_picture.html.slim (Duration: 0.4ms | Allocations: 233)
  Rendered work/edit.html.slim within layouts/application (Duration: 16.6ms | Allocations: 12547)
  [1m[35m (1.2ms)[0m  [1m[34mSELECT COUNT(*) FROM `collections`[0m
  ↳ app/views/layouts/application.html.slim:48
  Rendered shared/_breadcrumbs.html.slim (Duration: 0.2ms | Allocations: 73)
  [1m[36mVisit Load (1.1ms)[0m  [1m[34mSELECT `visits`.* FROM `visits` WHERE `visits`.`visit_token` = '82a34f50-0ebb-4492-8a68-6017ed0869ce' ORDER BY `visits`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[35m (0.9ms)[0m  [1m[35mBEGIN[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[36mAhoy::Event Create (0.9ms)[0m  [1m[32mINSERT INTO `ahoy_events` (`visit_id`, `user_id`, `name`, `properties`, `time`) VALUES (678, 2, 'work#edit', '{\"collection_id\":4,\"collection_title\":\"Wiltshire-1369-7-2-20 George Jnr family matters 1840s\",\"work_id\":28,\"work_title\":\"096.\"}', '2022-02-08 23:56:12')[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
  [1m[35m (3.4ms)[0m  [1m[35mCOMMIT[0m
  ↳ app/controllers/application_controller.rb:352:in `track_action'
Completed 200 OK in 117ms (Views: 57.6ms | ActiveRecord: 20.6ms | Allocations: 79384)


Oink Action: work#edit
Memory usage: 1401704 | PID: 31576
Instantiation Breakdown: Total: 18 | User: 8 | Collection: 6 | Work: 1 | PageBlock: 1 | Visit: 1 | Ahoy::Event: 1
Oink Log Entry Complete
Started GET "/admin/tail_logfile" for 58.107.234.187 at 2022-02-08 23:56:16 +0000
Processing by AdminController#tail_logfile as HTML
  [1m[36mUser Load (1.2ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:57:in `current_user'
  [1m[36mPageBlock Load (1.0ms)[0m  [1m[34mSELECT `page_blocks`.* FROM `page_blocks` WHERE `page_blocks`.`controller` = 'admin' AND `page_blocks`.`view` = 'tail_logfile'[0m
  ↳ app/controllers/application_controller.rb:238:in `load_html_blocks'
```

**Comment by benwbrum** [comment]
I have not been able to reproduce this.  Would you be comfortable sending a zipped database dump?
