### ISSUE TITLE
i18n-tasks in spec tests

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3059]
With a recent upgrade of the i18n-tasks gem, we got 2 new files and a spec test that checks for message status:

Here's the changes:  https://github.com/benwbrum/fromthepage/pull/3057/commits/5b356d346a47244d7b7ab7aab2ac71037421027f#diff-c1ded81b69dea6a1b03b09ed3a03e8b5a56a9fe604eff2febb6099931ffa6009

This is the sort of results the spec test will produce:
```Failures:
  1) I18n does not have missing keys
     Failure/Error:
       expect(missing_keys).to be_empty,
                               "Missing #{missing_keys.leaves.count} i18n keys, run `i18n-tasks missing' to show them"
     
       Missing 3350 i18n keys, run `i18n-tasks missing' to show them
     # ./spec/i18n_spec.rb:12:in `block (2 levels) in <top (required)>'
  2) I18n does not have unused keys
     Failure/Error:
       expect(unused_keys).to be_empty,
                              "#{unused_keys.leaves.count} unused i18n keys, run `i18n-tasks unused' to show them"
     
       9 unused i18n keys, run `i18n-tasks unused' to show them
     # ./spec/i18n_spec.rb:17:in `block (2 levels) in <top (required)>'
  3) I18n files are normalized
     Failure/Error: expect(non_normalized).to be_empty, error_message
     
       The following files need to be normalized:
         config/locales/en.yml
         config/locales/es.yml
         config/locales/pt.yml
       Please run `i18n-tasks normalize' to fix
     # ./spec/i18n_spec.rb:26:in `block (2 levels) in <top (required)>'
```

For now I'm going to comment out the spec tests, but we should tune the tests to exclude admin tests and update any missing messages at that point and then turn this back on.

**Comment by saracarl** [comment]
See #2152
