### ISSUE TITLE
Transkribus integration

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3167]
To support FromThePage->Transkribus integration we need

- To produce IIIF manifests that don't error when imported into Transkribus
- To produce zip file exports containing folders of files named `0.txt`, `1.txt`, etc. following a zero-indexed order of canvases in a manifest
- To list both of these in the Download tab for the work.
- To fix the bug doing a verbatim transcription export from Laura's mss.

```
onfiguration:
Plaintext Verbatim Page
Created At
Updated At
Zip File
[Download](https://fromthepage.com/bulk_export/1916/download)

Processing Log
** Invoke fromthepage:process_bulk_export (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute fromthepage:process_bulk_export
fetching bulk export with ID=1916
found bulk_export for 
	user=LauraKMorrealeLLC, 
	from collection=Houghton Library
{"id"=>1916,
 "user_id"=>42823,
 "collection_id"=>32000134,
 "status"=>"queued",
 "plaintext_verbatim_page"=>true,
 "plaintext_verbatim_work"=>false,
 "plaintext_emended_page"=>false,
 "plaintext_emended_work"=>false,
 "plaintext_searchable_page"=>false,
 "plaintext_searchable_work"=>false,
 "tei_work"=>false,
 "html_page"=>false,
 "html_work"=>false,
 "subject_csv_collection"=>false,
 "table_csv_collection"=>false,
 "table_csv_work"=>false,
 "created_at"=>Tue, 07 Jun 2022 14:20:46 UTC +00:00,
 "updated_at"=>Tue, 07 Jun 2022 14:20:46 UTC +00:00,
 "work_metadata_csv"=>false,
 "work_id"=>nil,
 "facing_edition_work"=>false,
 "text_pdf_work"=>false,
 "text_docx_work"=>false,
 "static"=>false,
 "document_set_id"=>nil}
		Exporting work	32012938	MS Lat 5: Conradus de Saxonia, Sermons. 
rake aborted!
ArgumentError: Requires a Node, NodeSet or String argument, and cannot accept a NilClass.
(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/nokogiri-1.13.4-x86_64-linux/lib/nokogiri/xml/node.rb:1332:in `coerce'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/nokogiri-1.13.4-x86_64-linux/lib/nokogiri/xml/node.rb:293:in `replace'
/home/fromthepage/deployment/releases/20220601211710/app/models/page.rb:562:in `block in formatted_plaintext'
```

**Comment by benwbrum** [comment]
@thodel reports:


> We still get an error message:
> 
> Note: IIIF manifest is not valid (IIIF Image API 2.1) and therefore cannot be parsed. Rendering resources must have a label and format set.
> at [Source: (StringReader); line: 135, column: 7] (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["rendering"])
> 
> Line 135, Column 7 of the manifest is where the „sequences“ ends.
> I have not that much experience about manifest to see what’s different to other manifests.
> The e-codices manifest – for example – also come up with error messages but the ingest runs through nonetheless.
>
