### ISSUE TITLE
500 errors in quality sampling

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3199]
Laura at Julian Bond reports:

I had to make numerous attempts to get "Quality Sampling" to load. I received a 500 error almost every time I tried to load the feature (possibly because of the large size), so I ultimately tricked it into loading by using the Recent Contributor page like this:
Go to Quality Sampling and receive 500 error.
Go to Review—>Recent Contributor page, click Review next to title; approve page; repeat through a few more titles.
Go back out to Review dashboard and click Quality Sampling. Quality Sampling loads successfully!
Before I found the successful trick, I also logged out and tried sampling in my other collection. I was able to load Quality Sampling in the Social Movements collection, so I wonder if the 500 error had to do with the larger size of my other collection's review data.
Once in Quality Sampling, the "Approve All" button always resulted in a 500 error. But--it turns out--the pages are still approved even with the error. That is:
Go to Quality Sampling-->A user's "Review" button-->"Approve All."
Receive 500 error page.
Go back and re-load Quality Sampling. The user that I had previously approved with the error now shows up as having no items in status Needs Review. The approval worked.

**Comment by benwbrum** [comment]
Looking at logfiles we see:

```
I, [2022-07-10T17:37:25.675577 #18413]  INFO -- : Started GET "/centerfordigitalediting/the-papers-of-julian-bond/quality_
samplings/18" for 64.99.243.217 at 2022-07-10 17:37:25 +0000
I, [2022-07-10T17:37:25.678102 #18413]  INFO -- : Processing by QualitySamplingsController#show as HTML
I, [2022-07-10T17:37:25.678494 #18413]  INFO -- :   Parameters: {"user_slug"=>"centerfordigitalediting", "collection_id"=>
"the-papers-of-julian-bond", "id"=>"18"}



I, [2022-07-10T17:37:26.876121 #18413]  INFO -- :   Rendered quality_samplings/show.html.slim within layouts/application (
Duration: 591.8ms | Allocations: 111554)
I, [2022-07-10T17:37:26.878446 #18413]  INFO -- : Completed 500  in 1199ms (ActiveRecord: 639.6ms | Allocations: 262682)
F, [2022-07-10T17:37:26.901480 #18413] FATAL -- :   
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    34:               =(1.0 - @collection.pages.where(status: Page::COMPLETED_STATUSES).where(:last_editor_user_id => user.id).average(:approval_delta)).truncate(3)*100
    35:               span %
    36:             td
    37:               small(class="#{approval_delta_to_style(page_sampling.mean_approval_delta, @max_approval_delta)}") =approval_delta_to_display(page_sampling.mean_approval_delta, @max_approval_delta)
    38:           -else
    39:             td.acenter =t('.not_applicable')
    40:             td =t('.not_applicable')
  
app/helpers/quality_samplings_helper.rb:10:in `approval_delta_to_quintile'
app/helpers/quality_samplings_helper.rb:7:in `approval_delta_to_style'
app/views/quality_samplings/show.html.slim:37
app/views/quality_samplings/show.html.slim:22:in `each'
app/views/quality_samplings/show.html.slim:22
app/controllers/application_controller.rb:48:in `switch_locale'
```

**Comment by benwbrum** [comment]
```
F, [2022-07-10T17:38:16.077845 #18413] FATAL -- :   
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    34:               =(1.0 - @collection.pages.where(status: Page::COMPLETED_STATUSES).where(:last_editor_user_id => user.id).average(:approval_delta)).truncate(3)*100
    35:               span %
    36:             td
    37:               small(class="#{approval_delta_to_style(page_sampling.mean_approval_delta, @max_approval_delta)}") =approval_delta_to_display(page_sampling.mean_approval_delta, @max_approval_delta)
    38:           -else
    39:             td.acenter =t('.not_applicable')
    40:             td =t('.not_applicable')
  
app/helpers/quality_samplings_helper.rb:10:in `approval_delta_to_quintile'
app/helpers/quality_samplings_helper.rb:7:in `approval_delta_to_style'
app/views/quality_samplings/show.html.slim:37
app/views/quality_samplings/show.html.slim:22:in `each'
app/views/quality_samplings/show.html.slim:22
app/controllers/application_controller.rb:48:in `switch_locale'
```

**Comment by benwbrum** [comment]
```
I, [2022-07-10T18:06:49.900339 #22937]  INFO -- : Started GET "/centerfordigitalediting/the-papers-of-julian-bond/user_contribution_list/scm2fc?quality_sampling_id=18" for 64.99.243.217 at 2022-07-10 18:06:49 +0000
I, [2022-07-10T18:06:49.901081 #22917]  INFO -- :   Rendered article_version/show.html.slim within layouts/application (Duration: 21.5ms | Allocations: 4677)
I, [2022-07-10T18:06:49.903798 #22937]  INFO -- : Processing by CollectionController#user_contribution_list as HTML


I, [2022-07-10T18:06:50.022912 #22937]  INFO -- :   Rendered shared/_collection_tabs.html.slim (Duration: 66.0ms | Allocat
ions: 4547)
I, [2022-07-10T18:06:50.032084 #22937]  INFO -- :   Rendered shared/_review_breadcrumbs.html.slim (Duration: 7.5ms | Alloc
ations: 6505)
I, [2022-07-10T18:06:50.093434 #22937]  INFO -- :   Rendered collection/user_contribution_list.html.slim within layouts/ap
plication (Duration: 147.6ms | Allocations: 24762)
I, [2022-07-10T18:06:50.095492 #22937]  INFO -- : Completed 500  in 191ms (ActiveRecord: 112.7ms | Allocations: 35464)
F, [2022-07-10T18:06:50.148210 #22937] FATAL -- :   
ActionView::Template::Error (nil can't be coerced into Float):
    18:         td.acenter Real Name: #{@user.real_name}
    19:       -if @quality_sampling
    20:         td.acenter Quality Score:
    21:           #{(1.0 - @collection.pages.where(status: Page::COMPLETED_STATUSES).where(:last_editor_user_id => @user.id).average(:approval_delta)).truncate(3)*100}%
    22:         td.aright 
    23:           =link_to 'Approve All', collection_user_review_approve_all_path(quality_sampling_id: @quality_sampling.id), method: :patch, class: 'button'
    24: 
  
app/views/collection/user_contribution_list.html.slim:21:in `-'
app/views/collection/user_contribution_list.html.slim:21
app/controllers/application_controller.rb:48:in `switch_locale'
```
