### ISSUE TITLE
Use fixed osullivan gem.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#325]
From the main "start a project" screen, clicking on Stanford's collection results in an error:

```
undefined method `has_key?' for #<Array:0x007f5f852740c0>
Extracted source (around line #19):

17
18
19
20
21
22




    manifest_json = connection.read
    #manifest_json = TEST_MANIFEST
    service = IIIF::Service.parse(manifest_json)

    sc_manifest = ScManifest.new
    sc_manifest.at_id = service['@id']

Rails.root: /home/benwbrum/dev/products/fromthepage/fromthepage
Application Trace | Framework Trace | Full Trace

app/models/sc_manifest.rb:19:in `manifest_for_at_id'
app/controllers/sc_collections_controller.rb:19:in `explore_manifest'

Request

Parameters:

{"at_id"=>"http://wellcomelibrary.org/iiif/b21780730/manifest",
 "sc_collection_id"=>"3"}
```

**Comment by benwbrum** [comment]
The same error is returned from Biblissima and, e-codices

Chronicling America fails at the same point with a different error:
```
OpenURI::HTTPError (500 Internal Server Error):
  app/models/sc_collection.rb:38:in `collection_for_at_id'
  app/controllers/sc_collections_controller.rb:14:in `explore'
```

**Comment by benwbrum** [comment]
We should update our Gemfile to add `:git => ` with a pointer to the osullivan fork at `benwbrum/osullivan` on the `service_is_array` branch.

**Comment by saracarl** [comment]
Now happening with UCD as well.
