### ISSUE TITLE
can't import v3 manifest

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3346]
This manifest:
https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/manifest.json
Fails with a "Please enter a valid IIIF manifest URL."

**Comment by saracarl** [comment]
we successfully identified it as a v3 manifest, but I don't like how this looks (curly brackets at the end of the title and for the description):

![image](https://user-images.githubusercontent.com/708566/195117184-e6b8eaf3-748c-402d-a421-6d26b78ac232.png)

**Comment by saracarl** [comment]
I didn't notice this on my first attempt to import, but with pry I see this:

```
NoMethodError - undefined method `map' for nil:NilClass:
  app/models/sc_manifest.rb:166:in `normalize_metadata'
  app/models/sc_manifest.rb:117:in `convert_with_collection'
  app/controllers/sc_collections_controller.rb:242:in `convert_manifest'
  app/controllers/application_controller.rb:62:in `switch_locale'
```

**Comment by saracarl** [comment]
Side note -- perhaps we need to address these?
```
```
         @sc_collection = nil # TODO figure out within partOf
          @label = nil # TODO
          @col = nil #3167 
```

**Comment by saracarl** [comment]
When `normalize_metadata` is called (here: https://github.com/benwbrum/fromthepage/blob/development/app/models/sc_manifest.rb#L117), 
it's passed a nil -- in fact a lot of the manifest values are `nil`; possibly related to my previous comment?

```
[3] pry(#<ScManifest>)> self
=> #<ScManifest:0x00007f0ba39057f8> {
                      :id => 25001709,
                 :work_id => nil,
        :sc_collection_id => nil,
                   :sc_id => nil,
                   :label => "AGI_JUSTICIA_741_N3_PIEZA_2",
                :metadata => nil,
       :first_sequence_id => nil,
    :first_sequence_label => nil,
              :created_at => Tue, 11 Oct 2022 14:49:19 UTC +00:00,
              :updated_at => Tue, 11 Oct 2022 14:49:19 UTC +00:00,
                   :at_id => "https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/manifest.json",
           :collection_id => nil,
                 :version => "3"
}
```

**Comment by saracarl** [comment]
We seem to be expecting this:
https://github.com/benwbrum/fromthepage/blob/development/app/models/sc_manifest.rb#L36
to set the rest of those values, but it isn't.

```
[11] pry(#<ScCollectionsController>)> @sc_manifest
=> #<ScManifest:0x000055d9c40c0050> {
                      :id => nil,
                 :work_id => nil,
        :sc_collection_id => nil,
                   :sc_id => nil,
                   :label => "AGI_JUSTICIA_741_N3_PIEZA_2",
                :metadata => nil,
       :first_sequence_id => nil,
    :first_sequence_label => nil,
              :created_at => nil,
              :updated_at => nil,
                   :at_id => "https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/manifest.json",
           :collection_id => nil,
                 :version => "3"
}
```

There is, however, a hash 

```
[14] pry(#<ScCollectionsController>)> @sc_manifest.v3_hash
=> {
    "@context" => [
        [0] "http://www.w3.org/ns/anno.jsonld",
        [1] "http://iiif.io/api/presentation/3/context.json"
    ],
          "id" => "https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/manifest.json",
        "type" => "Manifest",
       "items" => [
        [ 0] {
                "id" => "https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/canvas/p0",
              "type" => "Canvas",
             "items" => [
                [0] {
                       "id" => "https://nbu-manifests.s3.amazonaws.com/AGI_JUSTICIA_741_N3_PIEZA_2/canvas/p0/1",
                     "type" => "AnnotationPage",
                    "items" => [
                        [0] {

```

I think we should just set the values directly in this method:
https://github.com/benwbrum/fromthepage/blob/development/app/models/sc_manifest.rb#L36

But I worry about what that will do for the Yale manifests we wrote this to support.

**Comment by benwbrum** [comment]
Fixed and deployed.
