### ISSUE TITLE
Notes do not appear to save

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3412]
Since yesterday's deployment of the discussion forums functionality (#2820), users who try to create notes do not see their notes save.  The notes are created, but the UI behavior is not correct, as the edit window does not respond correctly.  No controller or view code appears to have changed.

The javascript console shows this error:
```
1868:490 Uncaught TypeError: Cannot read properties of undefined (reading 'responseText')
    at HTMLFormElement.<anonymous> (1868:490:47)
    at HTMLDocument.dispatch (application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:5226:27)
    at elemData.handle (application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:4878:28)
    at Rails.fire (application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:36411:13)
    at Object.complete (application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:36880:20)
    at application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:36466:67
    at xhr.onreadystatechange (application.debug-5dc5edeab820dd73dbf141ee98b33da77cfb8e73ab3d8091df7e90daabed7262.js:36511:20)
```
which is thrown because `xhr` is `null` in this code:
https://github.com/benwbrum/fromthepage/blob/development/app/views/notes/_notes.html.slim#L47-L78

Comparison with previous versions:

### landing page branch:
####Headers
```
Request URL: http://localhost:3000/notes
Request Method: POST
Status Code: 201 Created
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
```
#### Response
```
{"html":"\u003cdiv class=\"user-bubble editable\" id=\"note-32021598\"\u003e\u003ca href=\"/2\"\u003e\n    \u003cdiv class=\"userpic\"\u003e\n      \u003cimg alt=\"Ben W. Brumfield\" src=\"https://secure.gravatar.com/avatar/d34fc3a0018a48156439cccf0c62ee8e?default=blank\u0026secure=true\u0026size=80\" width=\"80\" height=\"80\" /\u003e\n    \u003c/div\u003e\u003c/a\u003e\n  \u003cdiv class=\"user-bubble_content\"\u003e\n    \u003cdiv class=\"user-bubble_actions\"\u003e\n      \u003ca data-note-edit=\"32021598\" title=\"Edit\"\u003e\u003csvg class=\"icon\"\u003e\u003cuse xlink:href=\"/assets/symbols-81ab0e78fb79046c1cc191a19465aca28edf627cc97f33b710d6253ec17514f8.svg#icon-edit\"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/a\u003e\u003ca data-note-delete=\"32021598\" data-confirm=\"Are you sure you want to delete this note?\" title=\"Delete\" data-remote=\"true\" rel=\"nofollow\" data-method=\"delete\" href=\"/notes/32021598\"\u003e\u003csvg class=\"icon\" title=\"Delete\"\u003e\u003cuse xlink:href=\"/assets/symbols-81ab0e78fb79046c1cc191a19465aca28edf627cc97f33b710d6253ec17514f8.svg#icon-remove-sign\"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/a\u003e\n    \u003c/div\u003e\u003ctime datetime=\"2022-12-02T13:36:31Z\"\u003e\n        \u003ca href=\"/2\"\u003eBen W. Brumfield\u003c/a\u003e\u0026nbsp;less than a minute ago\u003c/time\u003e\n    \u003cdiv class=\"user-bubble_note\"\u003e\n      \u003cp\u003etrying on landing page\u003c/p\u003e\n    \u003c/div\u003e\n  \u003c/div\u003e\u003cform class=\"user-bubble_form\" id=\"edit_note_32021598\" action=\"/notes/32021598\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"\u003e\u003cinput type=\"hidden\" name=\"_method\" value=\"patch\" /\u003e\n  \u003cdiv class=\"user-bubble_form_editor\"\u003e\u003ctextarea rows=\"4\" name=\"note[body]\" id=\"note_body\"\u003e\ntrying on landing page\u003c/textarea\u003e\n  \u003c/div\u003e\n  \u003cdiv class=\"user-bubble_form_footer\"\u003e\n    \u003cspan class=\"user-bubble_form_error\"\u003e\u003c/span\u003e\u003ca data-note-edit=\"32021598\" title=\"Edit\"\u003eCancel\u003c/a\u003e\u003cbutton name=\"button\" type=\"submit\"\u003eUpdate\u003c/button\u003e\n  \u003c/div\u003e\u003c/form\u003e\n\u003c/div\u003e"}
```

#### jQuery version
```
jQuery().jquery
'1.12.4'
```

#### Request headers
```
Request URL: http://localhost:3000/notes
Request Method: POST
Status Code: 201 Created
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
```

#### Response
```
{"html":"\u003cdiv class=\"user-bubble editable\" id=\"note-32021599\"\u003e\u003ca href=\"/2\"\u003e\n    \u003cdiv class=\"userpic\"\u003e\n      \u003cimg alt=\"Ben W. Brumfield\" src=\"https://secure.gravatar.com/avatar/d34fc3a0018a48156439cccf0c62ee8e?default=blank\u0026secure=true\u0026size=80\" width=\"80\" height=\"80\" /\u003e\n    \u003c/div\u003e\u003c/a\u003e\n  \u003cdiv class=\"user-bubble_content\"\u003e\n    \u003cdiv class=\"user-bubble_actions\"\u003e\n      \u003ca data-note-edit=\"32021599\" title=\"Edit\"\u003e\u003csvg class=\"icon\"\u003e\u003cuse xlink:href=\"/assets/symbols-81ab0e78fb79046c1cc191a19465aca28edf627cc97f33b710d6253ec17514f8.svg#icon-edit\"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/a\u003e\u003ca data-note-delete=\"32021599\" data-confirm=\"Are you sure you want to delete this note?\" title=\"Delete\" data-remote=\"true\" rel=\"nofollow\" data-method=\"delete\" href=\"/notes/32021599\"\u003e\u003csvg class=\"icon\" title=\"Delete\"\u003e\u003cuse xlink:href=\"/assets/symbols-81ab0e78fb79046c1cc191a19465aca28edf627cc97f33b710d6253ec17514f8.svg#icon-remove-sign\"\u003e\u003c/use\u003e\u003c/svg\u003e\u003c/a\u003e\n    \u003c/div\u003e\u003ctime datetime=\"2022-12-02T13:43:31Z\"\u003e\n        \u003ca href=\"/2\"\u003eBen W. Brumfield\u003c/a\u003e\u0026nbsp;less than a minute ago\u003c/time\u003e\n    \u003cdiv class=\"user-bubble_note\"\u003e\n      \u003cp\u003etrying on development\u003c/p\u003e\n    \u003c/div\u003e\n  \u003c/div\u003e\u003cform class=\"user-bubble_form\" id=\"edit_note_32021599\" action=\"/notes/32021599\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"\u003e\u003cinput type=\"hidden\" name=\"_method\" value=\"patch\" /\u003e\n  \u003cdiv class=\"user-bubble_form_editor\"\u003e\u003ctextarea rows=\"4\" name=\"note[body]\" id=\"note_body\"\u003e\ntrying on development\u003c/textarea\u003e\n  \u003c/div\u003e\n  \u003cdiv class=\"user-bubble_form_footer\"\u003e\n    \u003cspan class=\"user-bubble_form_error\"\u003e\u003c/span\u003e\u003ca data-note-edit=\"32021599\" title=\"Edit\"\u003eCancel\u003c/a\u003e\u003cbutton name=\"button\" type=\"submit\"\u003eUpdate\u003c/button\u003e\n  \u003c/div\u003e\u003c/form\u003e\n\u003c/div\u003e"}
```

#### jQuery version
```
jQuery().jquery
'1.12.4'
```

**Comment by saracarl** [comment]
These responses look identical.  The only thing I can think of is the user-bubble css classes, which we also used in the forums work.
