### ISSUE TITLE
500 error on Wellcome PDF export

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3458]
Hi there, I'm trying to download a PDF cope of Wellcome Collection: Ayscough, Lady (MS1026), however an error message 500 loads when I click the download button. Please could you advise? Many thanks.

**Comment by benwbrum** [comment]
The error in the logs is, 
```

REXML::ParseException - No close tag for /p/p/p
Line: 10
Position: 1155
Last 80 unconsumed characters::
  app/helpers/export_helper.rb:13:in `xml_to_pandoc_md'
  app/views/export/facing_edition.html.erb:16
  app/controllers/concerns/export_service.rb:47:in `export_printable'
  app/controllers/export_controller.rb:31:in `printable'
  app/controllers/application_controller.rb:62:in `switch_locale'
```

**Comment by benwbrum** [comment]
The appears to occur when there are unbalanced tags in the work description:
```
Description: <p>Receits of phisick and chirurgery. <p>There are a few cookery receipts at the end. <p>Inside the cover is written 'The Lady Ayscough Booke Anno Domini 1692'. The first 93 pp. and the 7 pp. of cookery receipts are by the original hand, the remainder is in another nearly contemporary script.<lb/>
```

(Note the unclosed, opened P tags)

**Comment by benwbrum** [comment]
The correct, long-term thing to do is for us to use a WYSIWYG for owner-entered HTML fields like work descriptions here.  In the short term, we should be able to fix the data in place.
