### ISSUE TITLE
static site export fails

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3524]
```
** Execute fromthepage:process_bulk_export
fetching bulk export with ID=2778
found bulk_export for 
	user=Locuscriticus, 
	from collection=Edición y Crítica Textual
{"id"=>2778,
 "user_id"=>445,
 "collection_id"=>25,
```

```
rake aborted!
TypeError: no implicit conversion of nil into String
/home/fromthepage/deployment/releases/20230220020613/app/controllers/concerns/static_site_exporter.rb:232:in `+'
/home/fromthepage/deployment/releases/20230220020613/app/controllers/concerns/static_site_exporter.rb:232:in `write_index_markdown'
/home/fromthepage/deployment/releases/20230220020613/app/controllers/concerns/static_site_exporter.rb:13:in `export_static_site'
```

**Comment by benwbrum** [comment]
More research shows that the problem is the static site export exploding if there is a `nil` `intro_block` for the collection being exported.  We should modify `app/controllers/concerns/static_site_exporter.rb:232` to test for a blank `intro_block` or use more fault-tolerant variable interpolation.

```
# Logfile created on 2026-05-03 20:06:05 +0000 by logger.rb/v1.7.0
Found bulk_export for 
	user=Locuscriticus
	from collection=Edición y Crítica Textual
{"status"=>"queued",
 "id"=>12592,
 "user_id"=>445,
 "collection_id"=>25,
 "plaintext_verbatim_page"=>false,
 "plaintext_verbatim_work"=>false,
 "plaintext_emended_page"=>false,
 "plaintext_emended_work"=>false,
 "plaintext_searchable_page"=>false,
 "plaintext_searchable_work"=>false,
 "tei_work"=>false,
 "html_page"=>false,
 "html_work"=>false,
 "subject_csv_collection"=>false,
 "table_csv_collection"=>false,
 "table_csv_work"=>false,
 "created_at"=>Sun, 03 May 2026 20:06:02.000000000 UTC +00:00,
 "updated_at"=>Sun, 03 May 2026 20:06:02.000000000 UTC +00:00,
 "work_metadata_csv"=>false,
 "work_id"=>nil,
 "facing_edition_work"=>false,
 "text_pdf_work"=>false,
 "text_docx_work"=>false,
 "static"=>true,
 "document_set_id"=>nil,
 "subject_details_csv_collection"=>false,
 "text_only_pdf_work"=>false,
 "organization"=>"by_work",
 "use_uploaded_filename"=>false,
 "plaintext_verbatim_zero_index_page"=>false,
 "owner_mailing_list"=>nil,
 "owner_detailed_activity"=>nil,
 "collection_activity"=>nil,
 "collection_contributors"=>nil,
 "report_arguments"=>{"preserve_linebreaks"=>"0"},
 "notes_csv"=>false,
 "admin_searches"=>nil,
 "page_details_csv_work"=>false,
 "page_details_csv_collection"=>false}

/home/fromthepage/deployment/releases/20260502142149/app/controllers/concerns/static_site_exporter.rb:232:in `+': no implicit conversion of nil into String (TypeError)

    out.write("---\n"+collection.intro_block)
                      ^^^^^^^^^^^^^^^^^^^^^^
	from /home/fromthepage/deployment/releases/20260502142149/app/controllers/concerns/static_site_exporter.rb:232:in `write_index_markdown'
	from /home/fromthepage/deployment/releases/20260502142149/app/controllers/concerns/static_site_exporter.rb:13:in `export_static_site'
	from /home/fromthepage/deployment/releases/20260502142149/app/helpers/export_helper.rb:121:in `write_work_exports'
	from /home/fromthepage/deployment/releases/20260502142149/app/models/bulk_export.rb:154:in `block (2 levels) in export_to_zip'
	from /home/fromthepage/deployment/shared/bundle/ruby/3.3.0/gems/rubyzip-3.2.2/lib/zip/output_stream.rb:60:in `open'
	from /home/fromthepage/deployment/releases/20260502142149/app/models/bulk_export.rb:153:in `block in export_to_zip'
	from /usr/share/rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/tempfile.rb:447:in `create'
	from /home/fromthepage/deployment/releases/20260502142149/app/models/bulk_export.rb:152:in `export_to_zip'
	from /home/fromthepage/deployment/releases/20260502142149/app/interactors/bulk_export/process.rb:15:in `perform'
	from /home/fromthepage/deployment/releases/20260502142149/app/interactors/application_interactor.rb:11:in `call'
	from /home/fromthepage/deployment/releases/20260502142149/lib/tasks/bulk_export.rake:19:in `block (2 levels) in <main>'```
