### ISSUE TITLE
500 on admin/owners & Users pages

### ISSUE THREAD

**Issue by rsmith-bu** [benwbrum/fromthepage#3558]
Log file shows the following when accessing Users tab under admin.
I, [2023-03-20T13:54:56.215730 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190] Started GET "/admin/user_list" for 10.20.124.66 at 2023-03-20 13:54:56 +0000
I, [2023-03-20T13:54:56.217294 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190] Processing by AdminController#user_list as HTML
I, [2023-03-20T13:54:56.228002 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190]   Rendering admin/user_list.html.slim within layouts/application
I, [2023-03-20T13:54:56.231058 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190]   Rendered admin/_header.html.slim (Duration: 2.4ms | Allocations: 1365)
I, [2023-03-20T13:54:56.237301 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190]   Rendered shared/_profile_picture.html.slim (Duration: 2.3ms | Allocations: 1169)
I, [2023-03-20T13:54:56.237995 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190]   Rendered admin/user_list.html.slim within layouts/application (Duration: 9.6ms | Allocations: 5331)
I, [2023-03-20T13:54:56.239135 #835]  INFO -- : [141cc164-5d4b-4830-ac35-9d85b03d5190] Completed 500  in 21ms (ActiveRecord: 6.1ms | Allocations: 11026)
F, [2023-03-20T13:54:56.243976 #835] FATAL -- : [141cc164-5d4b-4830-ac35-9d85b03d5190]   
[141cc164-5d4b-4830-ac35-9d85b03d5190] ActionView::Template::Error (undefined method `escape' for URI:Module):
[141cc164-5d4b-4830-ac35-9d85b03d5190]     5:   -if gravatar_size
[141cc164-5d4b-4830-ac35-9d85b03d5190]     6:     .userpic =gravatar_image_tag user.email, :alt => user_name, :gravatar => { :size => gravatar_size }
[141cc164-5d4b-4830-ac35-9d85b03d5190]     7:   -else
[141cc164-5d4b-4830-ac35-9d85b03d5190]     8:     .userpic =gravatar_image_tag user.email, :alt => user_name
[141cc164-5d4b-4830-ac35-9d85b03d5190]   
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/views/shared/_profile_picture.html.slim:8
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/helpers/application_helper.rb:48:in `profile_picture'
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/views/admin/user_list.html.slim:22
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/views/admin/user_list.html.slim:21
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/views/admin/user_list.html.slim:18
[141cc164-5d4b-4830-ac35-9d85b03d5190] app/controllers/application_controller.rb:62:in `switch_locale'
I, [2023-03-20T13:54:56.263635 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Started GET "/favicon.ico" for 10.20.124.66 at 2023-03-20 13:54:56 +0000
I, [2023-03-20T13:54:56.264860 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Processing by UserController#profile as 
I, [2023-03-20T13:54:56.265180 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392]   Parameters: {"user_id"=>"favicon"}
E, [2023-03-20T13:54:56.274312 #835] ERROR -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Bad record ID exception for params=<ActionController::Parameters {"controller"=>"user", "action"=>"profile", "user_id"=>"favicon", "format"=>"ico"} permitted: false>
E, [2023-03-20T13:54:56.274763 #835] ERROR -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] /var/www/fromthepage/code/app/controllers/application_controller.rb:157:in `load_objects_from_params'
I, [2023-03-20T13:54:56.275252 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Redirected to http://10.30.84.16/404
I, [2023-03-20T13:54:56.275987 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Completed 302 Found in 10ms (ActiveRecord: 4.3ms | Allocations: 5892)
I, [2023-03-20T13:54:56.276475 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Oink Action: user#profile
I, [2023-03-20T13:54:56.276870 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Memory usage: 749548 | PID: 835
I, [2023-03-20T13:54:56.277165 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Instantiation Breakdown: Total: 4 | User: 4
I, [2023-03-20T13:54:56.277462 #835]  INFO -- : [b66ec8d8-3dad-4d5e-97ad-0e17e374e392] Oink Log Entry Complete

Log shows the following when accessing Owners tab in admin.

I, [2023-03-20T13:59:04.737749 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] Started GET "/admin/owner_list" for 10.20.124.66 at 2023-03-20 13:59:04 +0000
I, [2023-03-20T13:59:04.739458 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] Processing by AdminController#owner_list as HTML
I, [2023-03-20T13:59:04.749188 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   Rendering admin/owner_list.html.slim within layouts/application
I, [2023-03-20T13:59:04.763394 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   Rendered admin/_header.html.slim (Duration: 2.7ms | Allocations: 1375)
I, [2023-03-20T13:59:04.772900 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   Rendered shared/_profile_picture.html.slim (Duration: 2.2ms | Allocations: 1171)
I, [2023-03-20T13:59:04.773549 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   Rendered admin/owner_list.html.slim within layouts/application (Duration: 24.0ms | Allocations: 20534)
I, [2023-03-20T13:59:04.774534 #835]  INFO -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] Completed 500  in 35ms (ActiveRecord: 4.6ms | Allocations: 25239)
F, [2023-03-20T13:59:04.779038 #835] FATAL -- : [68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] ActionView::Template::Error (undefined method `escape' for URI:Module):
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]     5:   -if gravatar_size
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]     6:     .userpic =gravatar_image_tag user.email, :alt => user_name, :gravatar => { :size => gravatar_size }
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]     7:   -else
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]     8:     .userpic =gravatar_image_tag user.email, :alt => user_name
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e]   
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/views/shared/_profile_picture.html.slim:8
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/helpers/application_helper.rb:48:in `profile_picture'
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/views/admin/owner_list.html.slim:27
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/views/admin/owner_list.html.slim:26
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/views/admin/owner_list.html.slim:23
[68ae7f6d-bba1-4cb8-81b5-1d31da61dd5e] app/controllers/application_controller.rb:62:in `switch_locale'
I, [2023-03-20T13:59:04.800710 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Started GET "/favicon.ico" for 10.20.124.66 at 2023-03-20 13:59:04 +0000
I, [2023-03-20T13:59:04.802050 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Processing by UserController#profile as 
I, [2023-03-20T13:59:04.802351 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208]   Parameters: {"user_id"=>"favicon"}
E, [2023-03-20T13:59:04.811311 #835] ERROR -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Bad record ID exception for params=<ActionController::Parameters {"controller"=>"user", "action"=>"profile", "user_id"=>"favicon", "format"=>"ico"} permitted: false>
E, [2023-03-20T13:59:04.811738 #835] ERROR -- : [edb26bfb-ba9e-497f-b714-df02beb79208] /var/www/fromthepage/code/app/controllers/application_controller.rb:157:in `load_objects_from_params'
I, [2023-03-20T13:59:04.812219 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Redirected to http://10.30.84.16/404
I, [2023-03-20T13:59:04.812940 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Completed 302 Found in 10ms (ActiveRecord: 3.9ms | Allocations: 5892)
I, [2023-03-20T13:59:04.813405 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Oink Action: user#profile
I, [2023-03-20T13:59:04.813866 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Memory usage: 749548 | PID: 835
I, [2023-03-20T13:59:04.814148 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Instantiation Breakdown: Total: 3 | User: 3
I, [2023-03-20T13:59:04.814404 #835]  INFO -- : [edb26bfb-ba9e-497f-b714-df02beb79208] Oink Log Entry Complete

**Comment by benwbrum** [comment]
This appears to be a duplicate of #2951
