### ISSUE TITLE
Deed performance problems after new indexes

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3664]
After refactoring the indexes on `deeds`, we are now seeing long queries on the notes transaction:

SELECT COUNT(*) FROM `deeds` INNER JOIN `collections` ON `collections`.`id` = `deeds`.`collection_id` WHERE `deeds`.`deed_type` = ? AND (collections.restricted = ?)

The table was retrieved with this index: index_deeds_on_collection_id_and_created_at
You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
Approximately 2002 rows of this table were scanned.

```

/home/fromthepage/deployment/releases/20230525184424/app/views/deed/list.html.slim:39:in `_app_views_deed_list_html_slim__2734091278265961650_494440'
                           /home/fromthepage/deployment/releases/20230525184424/app/controllers/deed_controller.rb:53:in `notes'
```

**Comment by benwbrum** [comment]
Another problematic query:

SELECT COUNT(*) AS count_all, `deeds`.`deed_type` AS deeds_deed_type FROM `deeds` WHERE `deeds`.`collection_id` = ? GROUP BY `deeds`.`deed_type` ORDER BY deeds.created_at DESC

```

                           /home/fromthepage/deployment/releases/20230525184424/app/models/collection_statistic.rb:56:in `get_stats_hash'
                     /home/fromthepage/deployment/releases/20230525184424/app/controllers/statistics_controller.rb:7:in `collection'
                    /home/fromthepage/deployment/releases/20230525184424/app/controllers/application_controller.rb:62:in `switch_locale'
```


The table was retrieved with this index: index_deeds_on_collection_id_and_created_at
A temporary table was created to access this part of the query, which can cause poor performance. This typically happens if the query contains GROUP BY and ORDER BY clauses that list columns differently.
MySQL had to do an extra pass to retrieve the rows in sorted order, which is a cause of poor performance but sometimes unavoidable.
You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
Approximately 495448 rows of this table were scanned.

**Comment by benwbrum** [comment]
Deployed
