### ISSUE TITLE
PDF export returns 500 error

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3699]
ETRC/SFASU reports 

The [problem transcription](http://localhost:3000/asketrc/lssp/rusk/transcribe/32899733) appears to be one ending with an empty horizontal rule:
```

25th, A. D. 1853, at 1:30 o'clock P. M. J. S. Swan, Clerk, County Court, Rusk County.
<hr></hr>
```

This error appears in the logs:
```
F, [2023-07-13T16:18:23.180743 #18696] FATAL -- :   
ActionView::Template::Error (Missing end tag for 'hr' (got 'div')
Line: 1
Position: 2463
Last 80 unconsumed characters:
):
    36: <% end %>
    37: 
    38: ### <%= page.title %>
    39: <%= raw(xml_to_pandoc_md(page.xml_text, @preserve_linebreaks, true)) %>
    40: 
    41: <% if @work.supports_translation && !page.xml_translation.blank?%>
    42: ### <%= page.title %>
  
app/helpers/export_helper.rb:34:in `new'
app/helpers/export_helper.rb:34:in `xml_to_pandoc_md'
app/views/export/facing_edition.html.erb:39
app/views/export/facing_edition.html.erb:24
app/controllers/concerns/export_service.rb:51:in `export_printable'
app/controllers/export_controller.rb:31:in `printable'
```

The page source is correct when it is saved.

The problem line is this
```
    doc = REXML::Document.new("<div>#{html}</div>")
```

at which point the `html` variable contains this, with an unbalanced HR:
```
"<p>The State of Texas,<span class=\"line-break\"> </span>Panola County } Know all men by there presents that I, Abner Herrin, surviving<span class=\"line-break\"> </span>executor of the will of Abner Herrin, deceased, have this day bargained, sold and<span class=\"line-break\"> </span>conveyed and by there presents, as the executor as aforesaid, do bargain, sell,<span class=\"line-break\"> </span>alienate, and convey unto Keziah Field, the wife of William Field, three negro slaves,<span class=\"line-break\"> </span>to wit, Ephraim, a man about forty-seven years of age, Cely, a woman about<span class=\"line-break\"> </span>forty years old, and her child Cordelia, fourteen months of age. [They were] sold by me,<span class=\"line-break\"> </span>as executor of said deceased, on [the] first Tuesday in January 1853 under <span class=\"line-break\"> </span>and by virtue of the will of said testator after having advertised the same,<span class=\"line-break\"> </span>etc. to the said Keziah. Which slaves were at sat sale by the Keziah Field [and]<span class=\"line-break\"> </span>bid off and bought for the sum of eighteen hundred and eighteen, which<span class=\"line-break\"> </span>is to me secured, and is the considerations hereof. To have and hold<span class=\"line-break\"> </span>said slaves to her and her heirs forever. Given under my hand and<span class=\"line-break\"> </span>seal, using the scrawls as such, this, the 28th day of February A. D. 1852. <span class=\"line-break\"> </span>Attest, M. L. Higgins, D. McNair. Abner Herrin {Seal}.<span class=\"line-break\"> </span>The State of Texas,              <span class=\"line-break\"> </span>Panola County } Personally appeared before the undersigned authority<span class=\"line-break\"> </span>Abner Herrin, whose name appears to the within bill of sale, and acknowl<span class=\"line-break\"></span>edged the same to be his act and said that he executed the same<span class=\"line-break\"> </span>for the uses and purposes therein contained.<span class=\"line-break\"> </span>Given under my hand and seal at office this, the 28th<span class=\"line-break\"> </span>day of February 1853. (LS) John Hadley Anderson, Clerk, County Court, Panola County.<span class=\"line-break\"> </span>Endorsed. Abner Herrin deed to William and Keziah Field. Filed for record March<span class=\"line-break\"> </span>25th, A. D. 1853, at 1:30 o'clock P. M. J. S. Swan, Clerk, County Court, Rusk County.<span class=\"line-break\"> </span></p><hr>"
```

The `html` variable is filled by calling ` html = xml_to_html(postprocessed, preserve_lb, flatten_links, collection)`.  At this point the `postprocessed` variable contains this:
```
"<?xml version='1.0' encoding='UTF-8'?>          <page>        <p>The State of Texas,<lb/>Panola County } Know all men by there presents that I, Abner Herrin, surviving<lb/>executor of the will of Abner Herrin, deceased, have this day bargained, sold and<lb/>conveyed and by there presents, as the executor as aforesaid, do bargain, sell,<lb/>alienate, and convey unto Keziah Field, the wife of William Field, three negro slaves,<lb/>to wit, Ephraim, a man about forty-seven years of age, Cely, a woman about<lb/>forty years old, and her child Cordelia, fourteen months of age. [They were] sold by me,<lb/>as executor of said deceased, on [the] first Tuesday in January 1853 under <lb/>and by virtue of the will of said testator after having advertised the same,<lb/>etc. to the said Keziah. Which slaves were at sat sale by the Keziah Field [and]<lb/>bid off and bought for the sum of eighteen hundred and eighteen, which<lb/>is to me secured, and is the considerations hereof. To have and hold<lb/>said slaves to her and her heirs forever. Given under my hand and<lb/>seal, using the scrawls as such, this, the 28th day of February A. D. 1852. <lb/>Attest, M. L. Higgins, D. McNair. Abner Herrin {Seal}.<lb/>The State of Texas,              <lb/>Panola County } Personally appeared before the undersigned authority<lb/>Abner Herrin, whose name appears to the within bill of sale, and acknowl<lb break='no'/>edged the same to be his act and said that he executed the same<lb/>for the uses and purposes therein contained.<lb/>Given under my hand and seal at office this, the 28th<lb/>day of February 1853. (LS) John Hadley Anderson, Clerk, County Court, Panola County.<lb/>Endorsed. Abner Herrin deed to William and Keziah Field. Filed for record March<lb/>25th, A. D. 1853, at 1:30 o'clock P. M. J. S. Swan, Clerk, County Court, Rusk County.<lb/><hr/></p>      </page>"
```

So it looks like `xml_to_html` is changing the correct `<hr/>` tag to the incorrect `<hr>`.

**Comment by benwbrum** [comment]
This problem is duplicated in the page display as well, where the source shows an unbalanced HR tag:
```


Given under my hand and seal at office this, the 28th<br/>
   day of February 1853. (LS) John Hadley Anderson, Clerk, County Court, Panola County.<br/>
   Endorsed. Abner Herrin deed to William and Keziah Field. Filed for record March<br/>
   25th, A. D. 1853, at 1:30 o'clock P. M. J. S. Swan, Clerk, County Court, Rusk County.<br/>
   </p><hr>
   </div>

```
