### ISSUE TITLE
500 error saving field-based page

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3768]
TSLA reports an error saving pages in their new field-based project.

I've reproduced this and gotten the following message in the logs:
```

I, [2023-09-01T17:37:44.054462 #5119]  INFO -- : Started PATCH "/tennessee-state-library-archives/world-war-i-questionnaires-538de53e-892c-4e9d-818f-c1ac4733d212/review/one_off/33478585" for 136.62.254.224 at 2023-09-01 17:37:44 +0000
I, [2023-09-01T17:37:44.056399 #5119]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2023-09-01T17:37:44.056650 #5119]  INFO -- :   Parameters: {"authenticity_token"=>"QH6phxDris78Whqk9+CF1gZd3Vmjv8WJ1WDGx3WKYneVBlX4QSi25XBIzsNoQmmiiJnDBzKq3gY8x2wWQt7GMg==", "page_id"=>"33478585", "flow"=>"", "quality_sampling_id"=>"", "page"=>{"mark_blank"=>"0", "needs_review"=>"0"}, "save_to_incomplete"=>"", "filter-brightness"=>"0", "filter-contrast"=>"0", "filter-threshold"=>"0", "fields"=>{"5816"=>{"County - e.g., Haywood County (Tenn.)"=>""}, "5497"=>{"Name in full "=>{"Last, First, M."=>"Abele, Herbert A."}}, "5498"=>{"Date of birth - Year Month Day - e.g., 1895 November 2"=>""}, "5501"=>{"Where born, Town (if any), and County and State - e.g., Memphis (Tenn.)"=>""}, "5505"=>{"Name of parents - separate with semicolons ; "=>""}, "5506"=>{"Place of their birth - e.g., Memphis (Tenn.)"=>""}, "5510"=>{"Date of entering service - Year Month Day - e.g., 1917 May 11"=>""}, "6076"=>{"Place of entering service - e.g., Memphis (Tenn.)"=>""}, "5507"=>{"Name of nearest kin"=>""}, "5511"=>{"Branch of service"=>""}, "5512"=>{"Company"=>""}, "5513"=>{"Regiment"=>""}, "5514"=>{"Division"=>""}}, "user_slug"=>"tennessee-state-library-archives", "collection_id"=>"world-war-i-questionnaires-538de53e-892c-4e9d-818f-c1ac4733d212"}
I, [2023-09-01T17:37:44.088790 #5119]  INFO -- : Completed 500  in 32ms (ActiveRecord: 13.3ms | Allocations: 17279)
F, [2023-09-01T17:37:44.094916 #5119] FATAL -- :   
NoMethodError (undefined method `scan' for {"Last, First, M."=>"Abele, Herbert A."}:ActiveSupport::HashWithIndifferentAccess):
  
app/models/page.rb:453:in `block (2 levels) in process_fields'
app/models/page.rb:452:in `each'
app/models/page.rb:452:in `block in process_fields'
app/models/page.rb:439:in `each'
app/models/page.rb:439:in `process_fields'
app/controllers/transcribe_controller.rb:132:in `save_transcription'
app/controllers/application_controller.rb:63:in `switch_locale'
```

**Comment by benwbrum** [comment]
The root problem was a field label of `name [with a square brace]`.  The rails framework saw that in the HTTP parameters and converted the parameter label into a hash.  Fortunately there is an easy work-around.

Suggested action:
* Check for square braces on the field configuration screen and show a validation error if project owners create them.

**Comment by WillNigel23** [comment]
#4123 

Added validation on transcription_field label to reject '[] {}'

The other side of things is, I also parameterized field.label when used in name tags. This is to avoid any existing bad data to cause this.

On another note, I titleize the label for display, let me know if this should not be the case
