### ISSUE TITLE
Large/old collection statistics slow performance

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3780]
Researching the queue full outage today, I noticed the collection statistics for a single collection taking 109870ms to respond.

Running this locally at 

#### 29104.8 ms
```
app/models/collection_statistic.rb:64:in `get_stats_hash' 
app/controllers/statistics_controller.rb:7:in `collection' 
app/controllers/application_controller.rb:63:in `switch_locale' 
```
SELECT COUNT(DISTINCT `deeds`.`user_id`) FROM `deeds` WHERE `deeds`.`collection_id` = 234;

#### 188640.7 ms
```
app/models/collection_statistic.rb:11:in `line_count' 
app/models/collection_statistic.rb:70:in `get_stats_hash' 
app/controllers/statistics_controller.rb:7:in `collection' 
app/controllers/application_controller.rb:63:in `switch_locale' 
```
SELECT SUM(line_count) FROM `works` LEFT OUTER JOIN `work_statistics` ON `work_statistics`.`work_id` = `works`.`id` WHERE `works`.`collection_id` = 234;

-- | --

**Comment by benwbrum** [comment]
After creating the following index, the 188s query ran in 49ms:
```sql
create index work_statistic_test on work_statistics (work_id, line_count);
```

We should add this to a migration.
