### ISSUE TITLE
metadata projects: can't leave notes

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3823]
If you try to leave a note on a metadata description page for a work, you get `Error: Internal Server Error`:
![image](https://github.com/benwbrum/fromthepage/assets/708566/40268709-14f6-49ba-9950-5438a3157141)

the error in the log is:
```
I, [2023-10-20T13:17:44.492492 #14519]  INFO -- : Processing by NotesController#create as JS
I, [2023-10-20T13:17:44.492722 #14519]  INFO -- :   Parameters: {"work_id"=>"32059163", "collection_id"=>"nikolais-louis-dance", "note"=>{"body"=>"leaving a note as a test."}, "button"=>""}
I, [2023-10-20T13:17:44.520007 #14519]  INFO -- : Completed 500  in 27ms (ActiveRecord: 12.7ms | Allocations: 12047)
F, [2023-10-20T13:17:44.525156 #14519] FATAL -- :   
NoMethodError (undefined method `notes' for nil:NilClass):
  
app/models/note.rb:32:in `email_users'
app/controllers/notes_controller.rb:19:in `block in create'
app/controllers/notes_controller.rb:16:in `create'
app/controllers/application_controller.rb:63:in `switch_locale'

```

This is because we have no concept of leaving a note on a *work* (which metadata applies to), only on pages.

You can reproduce this in production [on this page.](https://fromthepage.com/ohiouniversitylibraries/nikolais-louis-dance/act-one-murray-louis-dance-company-promo-group-shot-circa-1987/describe.33156551)

**Comment by benwbrum** [comment]
We already have a `note::work` association, so the DB should be set up to handle leaving notes on works.  That said, I believe that this is only used for denormalization, so additional work will be needed to handle displaying notes for a work on the metadata overview/entry pages without also displaying notes left on pages.  We'll also need to conditionalize any place where we render notes and their pages (including the notes export CSV and any notes/deed list).
