### ISSUE TITLE
nil exception on collection#show

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3855]
We're seeing a nil exception and a 500 error when we access this page:   https://fromthepage.com/adah/governor-a-b-moore-administrative-files-and-correspondence-1857-1859

The error in the log file is this:
```
I, [2023-11-27T14:58:48.891889 #7936]  INFO -- : Started GET "/adah/governor-a-b-moore-administrative-files-and-correspondence-1857-1859" for 136.62.254.224 at 2023-11-27 14:58:48 +0000
I, [2023-11-27T14:58:48.893703 #7936]  INFO -- : Processing by CollectionController#show as HTML
I, [2023-11-27T14:58:48.893927 #7936]  INFO -- :   Parameters: {"user_slug"=>"adah", "id"=>"governor-a-b-moore-administrative-files-and-correspondence-1857-1859"}
I, [2023-11-27T14:58:48.899523 #7936]  INFO -- :   Rendering inline template
I, [2023-11-27T14:58:48.900605 #7936]  INFO -- :   Rendered inline template (Duration: 0.8ms | Allocations: 78)
I, [2023-11-27T14:58:48.916084 #7936]  INFO -- : Completed 500  in 22ms (ActiveRecord: 8.9ms | Allocations: 10740)
F, [2023-11-27T14:58:48.920687 #7936] FATAL -- :   
NoMethodError (undefined method `id' for nil:NilClass):
  
app/controllers/collection_controller.rb:176:in `show'
app/controllers/application_controller.rb:63:in `switch_locale'
```

We're seeing a similar error in NewRelic:
```
/home/fromthepage/deployment/releases/20231109191750/app/controllers/collection_controller.rb:180:in `show'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:195:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/home/fromthepage/deployment/releases/20231109191750/app/controllers/application_controller.rb:63:in `switch_locale'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/ahoy_matey-4.1.0/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionview-6.0.3.2/lib/action_view/rendering.rb:39:in `process'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'
<truncated 80 additional frames>
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/ssl.rb:74:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:249:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/railtie.rb:190:in `public_send'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/railtie.rb:190:in `method_missing'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:19:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/middleware.rb:25:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
```

Perhaps the slug is wrong?

**Comment by benwbrum** [comment]
Another problem we're seeing with `adah`:

```
/home/fromthepage/deployment/releases/20231109191750/app/controllers/collection_controller.rb:615:in `needs_review_pages'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:195:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/home/fromthepage/deployment/releases/20231109191750/app/controllers/application_controller.rb:63:in `switch_locale'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/ahoy_matey-4.1.0/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionview-6.0.3.2/lib/action_view/rendering.rb:39:in `process'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'
<truncated 80 additional frames>
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/ssl.rb:74:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:249:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/railtie.rb:190:in `public_send'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/railtie.rb:190:in `method_missing'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:19:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/middleware.rb:25:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
```
