### ISSUE TITLE
Passenger RubyVersionMismatch exception on production

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3974]
When we restart passenger (without restarting apache), we get a ruby version mismatch error.

Here is the error log from the last time this happened (which appeared to be immediately after a log rotation):
```
[ N 2024-02-27 06:25:11.4772 11538/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2024-02-27 06:25:11.4920 11547/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2024-02-27 06:25:11.4920 11547/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2024-02-27 06:25:11.5805 11547/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 11547
[Tue Feb 27 06:25:11.585718 2024] [mpm_event:notice] [pid 1120:tid 139999552117696] AH00489: Apache/2.4.29 (Ubuntu) Phusion_Passenger/6.0.16 OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Feb 27 06:25:11.585738 2024] [core:notice] [pid 1120:tid 139999552117696] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 27 06:25:12.588685 2024] [core:notice] [pid 1120:tid 139999552117696] AH00052: child pid 7985 exit signal Segmentation fault (11)
[Tue Feb 27 06:25:12.588726 2024] [core:notice] [pid 1120:tid 139999552117696] AH00052: child pid 7987 exit signal Segmentation fault (11)
App 11763 output: Error: The application encountered the following error: Your Ruby version is 2.7.1, but your Gemfile specified 2.7.3 (Bundler::RubyVersionMismatch)
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/definition.rb:470:in `validate_runtime!'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler.rb:143:in `setup'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
App 11763 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
App 11763 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `activate_gem'
App 11763 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 11763 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:544:in `running_bundler'
App 11763 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 11763 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
App 11763 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 11763 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 11763 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 11763 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 11763 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2024-02-27 06:25:13.0635 11547/T1f age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/fromthepage/deployment/current: The application encountered the following error: Your Ruby version is 2.7.1, but your Gemfile specified 2.7.3 (Bundler::RubyVersionMismatch)
  Error ID: 3e438ec9
  Error details saved to: /tmp/passenger-error-uP2nqS.html


```

**Comment by benwbrum** [comment]
Our production Apache configuration included `sites-enabled/99-wildcard.conf` which contained a duplicate (old) `PassengerRuby` variable.  Updating the value of this variable appears to have fixed the problem.
