### ISSUE TITLE
TEI export failing

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3984]
From Dartmouth:

> Hello! For the past several weeks I have been having trouble with bulk exports of TEI-XML. The exports result in an error each time. I have tried to do this with our "pre-TEI" set from our Stefansson collection, as well as with our full Edward Mitchell collection.

>Any ideas as to why this is happening, and/or troubleshooting tips?

**Comment by saracarl** [comment]
Reproduction log here:
https://fromthepage.com/bulk_export/5065
Error:
```
rake aborted!
ActionView::Template::Error: wrong number of arguments (given 4, expected 0..1)
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/url_for.rb:170:in `url_for'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/route_set.rb:270:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/route_set.rb:213:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
/home/fromthepage/deployment/releases/20240319192615/app/views/export/tei.html.erb:333:in `block in _app_views_export_tei_html_erb__507087057975917821_287900'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
/home/fromthepage/deployment/releases/20240319192615/app/views/export/tei.html.erb:329:in `_app_views_export_tei_html_erb__507087057975917821_287900'
```

**Comment by saracarl** [comment]
Line that error occurs on:
https://github.com/benwbrum/fromthepage/blob/development/app/views/export/tei.html.erb#L333
