### ISSUE TITLE
Collection statistics performs slowly; should not be crawlable

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4028]
The Collection Statistics screen has one of the slowest average response times in the system, and is probably being crawled.  We should attempt to optimize that screen, and also hide it if users are not logged in.

**Comment by benwbrum** [comment]
The longest query in the collection statistics appears to be this one:
```
Executing: statistics#collection  892.9ms
app/controllers/statistics_controller.rb:30:in `block in build_user_array' app/controllers/statistics_controller.rb:30:in `each' app/controllers/statistics_controller.rb:30:in `build_user_array' app/controllers/statistics_controller.rb:19:in `collection' app/controllers/application_controller.rb:70:in `switch_locale' SELECT `users`.* FROM `users`;
```
