### ISSUE TITLE
500 error in download

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4030]
Royal College of Physicians
 
Message:

I am trying to download the complete transcript of https://fromthepage.com/folger/early-modern-recipe-books/ms-504
but I keep getting the 504 error message.

**Comment by saracarl** [comment]
Found a errant <.... at the end of the description, fixed that.

Then ran into another 500 error:

```
F, [2024-04-09T19:14:01.122826 #2757] FATAL -- :   
ActionView::Template::Error (Missing end tag for 'ul' (got 'p')
Line: 4
Position: 1117
Last 80 unconsumed characters:
):
    15: <% 
    16:   xml_metadata = @work.merge_metadata.map{|e| "#{e['label']}: #{e['value']}"}.join("<lb/>\n")
    17: %>
    18: <%= raw(xml_to_pandoc_md("<p>#{xml_metadata}</p>", true, true, nil, false)) %>
    19: \newpage
    20: <% end %>
    21: 
  
app/helpers/export_helper.rb:13:in `new'
app/helpers/export_helper.rb:13:in `xml_to_pandoc_md'
app/views/export/facing_edition.html.erb:18
app/controllers/concerns/export_service.rb:52:in `export_printable'
app/controllers/export_controller.rb:31:in `printable'
app/controllers/application_controller.rb:64:in `switch_locale'
```

**Comment by saracarl** [comment]
Suggested customer use plaintext description, or better formed html.
