### ISSUE TITLE
500 error reviewing spreadsheet docs

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4039]
I think this is Tom York's 500 error:

> I, [2024-04-16T20:21:00.589635 #17032]  INFO -- : Started PATCH "/indianaarchives/indiana-draft-enrollment-lists-of-1862/review/one_off/33946927" for 68.57.247.167 at 2024-04-16 20:21:00 +0000
> I, [2024-04-16T20:21:00.591290 #17032]  INFO -- : Processing by TranscribeController#save_transcription as HTML
> I, [2024-04-16T20:21:00.591547 #17032]  INFO -- :   Parameters: {"authenticity_token"=>"1QjNg80TqwfdrYiWUWQRSwmhOZ8M2fvVJBLEIwqn9aRcRjo1a4mfGeXP8ComObJ4mxhGTfLbAWoFgOGN76pgoA==", "page_id"=>"33946927", "f
> low"=>"", "quality_sampling_id"=>"", "page"=>{"mark_blank"=>"0", "needs_review"=>"0"}, "save_to_incomplete"=>"", "filter-brightness"=>"0", "filter-contrast"=>"0", "filter-threshold"=>"0", "fields"=>{"4532
> "=>{"County"=>"Posey"}, "4533"=>{"Township"=>"Black"}, "4534"=>{"Commissioner"=>"John A Mann"}, "4555"=>{"Page Number"=>"6"}, "4531"=>{"spreadsheet"=>""}}, "user_slug"=>"indianaarchives", "collection_id"=
> >"indiana-draft-enrollment-lists-of-1862"}
> I, [2024-04-16T20:21:00.610046 #17032]  INFO -- : Completed 500  in 18ms (ActiveRecord: 2.7ms | Allocations: 11364)
> F, [2024-04-16T20:21:00.615223 #17032] FATAL -- :   
> JSON::ParserError (unexpected token at ''):
>   
> app/models/page.rb:399:in `process_spreadsheet'
> app/models/page.rb:457:in `block in process_fields'
> app/models/page.rb:453:in `each'
> app/models/page.rb:453:in `process_fields'
> app/controllers/transcribe_controller.rb:132:in `save_transcription'
> app/controllers/application_controller.rb:64:in `switch_locale'

**Comment by benwbrum** [comment]
We've had some more correspondence with Tom, and it looks like this is what's happening:
* Tom transcribes part of a page
* He hits save
* The page saves redirects to the transcription screen again
* The network is slow, and the image does not load into OSD
* Tom hits "save" again to force the image to reload
My theory is that the HoT control has not fully loaded the transcription data or gone into a "ready" state when Tom hits "Save" the second time.  He's going to try reloading slow screens instead of hitting "save" to test this.
