### ISSUE TITLE
failure in displaying subject article 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#405]
If you create a subject and then try to follow the link on the hover of transcribed text to the article about the subject (or follow the subject links to just read the subject, i.e. http://97.107.141.53/article/show?article_id=1) it fails with the following:

I, [2016-09-30T16:17:55.263766 #22457]  INFO -- : Started GET "/article/show?article_id=1" for 70.112.74.
2 at 2016-09-30 16:17:55 +0000
I, [2016-09-30T16:17:55.265491 #22457]  INFO -- : Processing by ArticleController#show as HTML
I, [2016-09-30T16:17:55.265550 #22457]  INFO -- :   Parameters: {"article_id"=>"1"}
I, [2016-09-30T16:17:55.279921 #22457]  INFO -- :   Rendered article/graph.dot (1.6ms)
I, [2016-09-30T16:17:55.280480 #22457]  INFO -- : Completed 500 Internal Server Error in 15ms
F, [2016-09-30T16:17:55.283067 #22457] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - /home/fromthepage/deployment/releases/20160929155541/public/images/working/dot/1.dot):
  app/controllers/article_controller.rb:156:in `initialize'
  app/controllers/article_controller.rb:156:in `open'
  app/controllers/article_controller.rb:156:in `show'

**Comment by saracarl** [comment]
The solution to this was to make sure you have a /home/fromthepage/deployment/releases/20160929155541/public/images/working/dot/ directory with rw access by the web server.

The next issue you may run into is:
F, [2016-09-30T16:29:10.249851 #22457] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - /home/fromthepage/deployment/releases/20160929155541/public/images/working/dot/1.map):
  app/controllers/article_controller.rb:164:in `read'
  app/controllers/article_controller.rb:164:in `show'


The solution to that is to make sure graphviz is installed.  (apt-get install graphviz)
