### ISSUE TITLE
New Bedford pdf export error

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4073]
> I, [2024-05-01T18:55:05.974793 #3474]  INFO -- : Completed 500  in 466ms (ActiveRecord: 2.1ms | Allocations: 12738)
> F, [2024-05-01T18:55:05.979346 #3474] FATAL -- :   
> ActionView::Template::Error (Missing end tag for 'span' (got 'p')
> Line: 5
> Position: 1318
> Last 80 unconsumed characters:
> ):
>     15: <% 
>     16:   xml_metadata = @work.merge_metadata.map{|e| "#{e['label']}: #{e['value']}"}.join("<lb/>\n")
>     17: %>
>     18: <%= raw(xml_to_pandoc_md("<p>#{xml_metadata}</p>", true, true, nil, false)) %>
>     19: \newpage
>     20: <% end %>
>     21: 
>   
> app/helpers/export_helper.rb:13:in `new'
> app/helpers/export_helper.rb:13:in `xml_to_pandoc_md'
> app/views/export/facing_edition.html.erb:18
> app/controllers/concerns/export_service.rb:52:in `export_printable'
> app/controllers/export_controller.rb:31:in `printable'
> app/controllers/application_controller.rb:64:in `switch_locale'
>

**Comment by saracarl** [comment]
sent to customer:
I looked at the export of the Awashonks.  It's failing because of incomplete/bad html in the description, here:

https://fromthepage.com/nbwm/logbooks-and-journals/kwm-494/edit

Fix that and you should be good to go.
