### ISSUE TITLE
500 error deleting older notes

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4238]
Payton at GRI reports that they are unable to delete older notes.  When I log in as her and try to delete the top notes on [this page](https://fromthepage.com/gri/stendahl-letters-qc/l000324/display/1678501), I see the server return a 500 error.

Looking in the logs, I see this:
```
I, [2024-07-19T01:26:44.694705 #1503028]  INFO -- : Started DELETE "/notes/32056132" for 50.223.147.195 at 2024-07-19 01:26:44 +0000
I, [2024-07-19T01:26:44.697143 #1503028]  INFO -- : Processing by NotesController#destroy as JS
I, [2024-07-19T01:26:44.697506 #1503028]  INFO -- :   Parameters: {"id"=>"32056132"}
I, [2024-07-19T01:26:44.707396 #1503028]  INFO -- : Completed 500  in 10ms (ActiveRecord: 1.7ms | Allocations: 4318)
F, [2024-07-19T01:26:44.710936 #1503028] FATAL -- :   
NoMethodError (undefined method `delete' for nil:NilClass):
  
app/controllers/notes_controller.rb:47:in `destroy'
app/controllers/application_controller.rb:64:in `switch_locale'
```

The [relevant line of code](https://github.com/benwbrum/fromthepage/blob/development/app/controllers/notes_controller.rb#L47) calls `@note.deed.delete`.  Is it possible that some notes don't have deeds?

**Comment by benwbrum** [comment]
Apparently there is no deed associated with this note:
```
2.7.3 :001 > page = Page.find 1678501
 => #<Page id: 1678501, title: "gri_2017_m_38_b105_f06_0072", source_text:... 
2.7.3 :002 > page.notes.count
 => 6 
2.7.3 :003 > page.notes.first
 => #<Note id: 32056132, title: "Line 17: \"Goldwater\" could be Robert Goldwater?", body: "Line 17: \"Goldwater\" could be Robert Goldwater?", user_id: 32016945, collection_id: 1112, work_id: 51875, page_id: 1678501, parent_id: nil, depth: nil, created_at: "2023-10-23 22:22:21.000000000 +0000", updated_at: "2023-10-23 22:22:21.000000000 +0000"> 
2.7.3 :004 > page.notes.first.deed
 => nil 
```

**Comment by benwbrum** [comment]
I have no idea how to reproduce this, unless we create a note then delete the associated deed in the Rails console.  Regardless, we should conditionalize deed deletion so that Payton can delete these notes.

**Comment by benwbrum** [comment]
It turned out that I had some data in my local DB with this problem.  Here's how I found it:

```ruby
note_ids = Note.all.pluck(:id)
notes_in_deeds = Deed.where(deed_type: 'note_add').pluck(:note_id)
deedless_note_ids = note_ids - notes_in_deeds
note_id = deedless_note_ids.last
note = Note.find note_id
File.join(note.collection.owner.slug, note.collection.slug, note.work.slug, 'display', note.page.id.to_s)
```
