### ISSUE TITLE
missing activity emails

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4247]
University of South Dakota has not received any overnight activity emails since June 28th.

I thought this was related to the "recent activity" feed not being updated, but according to Ben it wasn't, and we deployed that fix and the problem is still occurring.

I see recent activity in a number of their collections.
![image](https://github.com/user-attachments/assets/ca3fcb75-6dbf-44d9-a89e-a74ceca2f5d9)

And I see some emails going to them, but not activity emails:
![image](https://github.com/user-attachments/assets/a4c05760-950e-4347-acb0-6b8d592b7373)

And activity emails are generally going out to others:
![image](https://github.com/user-attachments/assets/cb3f28eb-f1ac-4be4-a34b-972d295186f1)

Their profile settings are correct:
![image](https://github.com/user-attachments/assets/2edcbe34-c56c-402e-9b48-de96451dd138)

**Comment by saracarl** [comment]
Ok, this was not caused by the missing deeds in the activity feed -- that was a UI caching problem.

Investigating the rake task logs, I found quite a few of these:

> /usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
> /usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
> /usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:541: warning: previous definition of Socket was here
> rake aborted!
> Postmark::InactiveRecipientError: You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: umdcrowdsourcery@umd.edu. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/http_client.rb:78:in `handle_response'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/http_client.rb:92:in `block in do_request'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/http_client.rb:91:in `synchronize'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/http_client.rb:91:in `do_request'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/http_client.rb:32:in `post'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/api_client.rb:38:in `block (2 levels) in deliver_message'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/client.rb:58:in `take_response_of'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/api_client.rb:38:in `block in deliver_message'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/client.rb:39:in `with_retries'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/api_client.rb:37:in `deliver_message'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/postmark-1.25.1/lib/postmark/handlers/mail.rb:14:in `deliver!'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/mail-2.8.1/lib/mail/message.rb:269:in `deliver!'
> /home/fromthepage/deployment/releases/20240722200359/lib/tasks/send_owner_emails.rake:12:in `block (3 levels) in <main>'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
> /home/fromthepage/deployment/releases/20240722200359/lib/tasks/send_owner_emails.rake:8:in `block (2 levels) in <main>'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
> /home/fromthepage/deployment/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
> Tasks: TOP => fromthepage:collection_stats_by_owner
> (See full trace by running task with --trace)

so I think we need to do something like:

```
       rescue Postmark::InvalidMessageError
                puts "An exception was raised while trying to notify. However this was rescued."
                return true
        end
```

probably around here:  https://github.com/benwbrum/fromthepage/blob/a4a075e7c42990821f509c361c8d0fef43f35014/lib/tasks/send_owner_emails.rake#L12
