### ISSUE TITLE
gsub 500 on page display

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4319]
Found the following error:
```
I, [2024-09-09T16:55:55.081238 #3197987]  INFO -- : Started GET "/display/display_page?page_id=913063" for 60.185.205.85 at 2024-09-09 16:55:55 +0000
I, [2024-09-09T16:55:55.083381 #3197961]  INFO -- : Processing by CollectionController#show as */*
I, [2024-09-09T16:55:55.083390 #3197987]  INFO -- : Processing by DisplayController#display_page as HTML
I, [2024-09-09T16:55:55.083604 #3197987]  INFO -- :   Parameters: {"page_id"=>"913063"}



I, [2024-09-09T16:55:55.122791 #3197987]  INFO -- : Completed 500  in 39ms (ActiveRecord: 3.0ms | Allocations: 80922)
I, [2024-09-09T16:55:55.123243 #3198088]  INFO -- :   Rendered inline template (Duration: 0.7ms | Allocations: 76)
F, [2024-09-09T16:55:55.127836 #3197987] FATAL -- :   
ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
    53:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
    54:   }]
    55: 
    56: -description = xml_to_html(@page.xml_text)
    57: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
    58: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} #{t('.page')}" : "#{t('.page')} #{selected_tab.downcase}"
    59: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
```

**Comment by benwbrum** [comment]
This is a problem in `display_page` rendering the `xml_text` for this particular page.  We need to get the page source and the XML text to reproduce it.

**Comment by saracarl** [comment]
page to investigate:  /dartmouthlibrary/wrangelisland/stefansson-wrangel-09-15-011/display/32404450

**Comment by benwbrum** [comment]
Another one: page_id=34043802

**Comment by benwbrum** [comment]
This also occurs for the page version tab:
```
I, [2024-09-09T16:47:25.968541 #3197961]  INFO -- : Started GET "/page_version/show?page_version_id=19866" for 49.89.86.242 at 2024-09-09 16:47:25 +0000
I, [2024-09-09T16:47:25.970944 #3197961]  INFO -- : Processing by PageVersionController#show as HTML
I, [2024-09-09T16:47:25.971154 #3197961]  INFO -- :   Parameters: {"page_version_id"=>"19866"}
I, [2024-09-09T16:47:26.064828 #3197961]  INFO -- :   Rendered page_version/show.html.slim within layouts/application (Duration: 74.6ms | Allocations: 142510)
I, [2024-09-09T16:47:26.065289 #3197961]  INFO -- :   Rendered layout layouts/application.html.slim (Duration: 75.3ms | Allocations: 143213)
I, [2024-09-09T16:47:26.066066 #3197961]  INFO -- : Completed 500  in 95ms (ActiveRecord: 6.0ms | Allocations: 151097)
I, [2024-09-09T16:47:26.069053 #3197877]  INFO -- :   Rendered layout layouts/application.html.slim (Duration: 25.4ms | Allocations: 19776)
F, [2024-09-09T16:47:26.071679 #3197961] FATAL -- :   
ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
    53:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
    54:   }]
    55: 
    56: -description = xml_to_html(@page.xml_text)
    57: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
    58: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} #{t('.page')}" : "#{t('.page')} #{selected_tab.downcase}"
    59: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
  
app/helpers/abstract_xml_helper.rb:286:in `block (2 levels) in xml_to_html'
app/helpers/abstract_xml_helper.rb:285:in `block in xml_to_html'
app/helpers/abstract_xml_helper.rb:284:in `each'
app/helpers/abstract_xml_helper.rb:284:in `xml_to_html'
app/views/shared/_page_tabs.html.slim:56
app/views/page_version/show.html.slim:1
app/controllers/application_controller.rb:64:in `switch_locale'
```

**Comment by benwbrum** [comment]
And another page version:
```

I, [2024-09-09T16:47:29.909544 #3197907]  INFO -- : Started GET "/page_version/show?page_version_id=2035106" for 180.127.72.183 at 2024-09-09 16:47:29 +0000
I, [2024-09-09T16:47:29.909849 #3197877]  INFO -- : Completed 200 OK in 48ms (Views: 26.0ms | ActiveRecord: 5.9ms | Allocations: 38317)
I, [2024-09-09T16:47:29.910124 #3197877]  INFO -- : Oink Action: article_version#list
I, [2024-09-09T16:47:29.910309 #3197877]  INFO -- : Memory usage: 2428584 | PID: 3197877
I, [2024-09-09T16:47:29.910455 #3197877]  INFO -- : Instantiation Breakdown: Total: 25 | User: 8 | ArticleVersion: 7 | PageBlock: 3 | Article: 2 | Collection: 2 | Visit: 1 | DocumentSet: 1 | Ahoy::Event: 1
I, [2024-09-09T16:47:29.910637 #3197877]  INFO -- : Oink Log Entry Complete
I, [2024-09-09T16:47:29.911741 #3197907]  INFO -- : Processing by PageVersionController#show as HTML
I, [2024-09-09T16:47:29.911937 #3197907]  INFO -- :   Parameters: {"page_version_id"=>"2035106"}
I, [2024-09-09T16:47:29.939161 #3197877]  INFO -- : Started GET "/article_version/show?article_version_id=32088313" for 114.98.189.79 at 2024-09-09 16:47:29 +0000
I, [2024-09-09T16:47:29.941394 #3197877]  INFO -- : Processing by ArticleVersionController#show as HTML
I, [2024-09-09T16:47:29.941643 #3197877]  INFO -- :   Parameters: {"article_version_id"=>"32088313"}
I, [2024-09-09T16:47:29.948212 #3197907]  INFO -- :   Rendered page_version/show.html.slim within layouts/application (Duration: 20.9ms | Allocations: 53022)
I, [2024-09-09T16:47:29.948674 #3197907]  INFO -- :   Rendered layout layouts/application.html.slim (Duration: 21.7ms | Allocations: 53725)
I, [2024-09-09T16:47:29.949400 #3197907]  INFO -- : Completed 500  in 37ms (ActiveRecord: 3.9ms | Allocations: 61642)
I, [2024-09-09T16:47:29.950927 #3197961]  INFO -- :   Rendered display/display_page.html.slim within layouts/application (Duration: 67.8ms | Allocations: 176118)
F, [2024-09-09T16:47:29.954548 #3197907] FATAL -- :   
ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
    53:     :path => "#{collection_edit_page_path(@collection.owner, @collection, @work, @page.id)}",
    54:   }]
    55: 
    56: -description = xml_to_html(@page.xml_text)
    57: -selected_tab = tabs.find { |tab| tab[:selected] == selected }[:name] rescue ""
    58: -tab_title = ([3,6].include? selected) ? "#{selected_tab.downcase} #{t('.page')}" : "#{t('.page')} #{selected_tab.downcase}"
    59: -page_title = @collection.present? ? "#{@page.title} (#{@collection.title}, #{@work.title})" : "#{@page.title} (#{@work.title})"
  
app/helpers/abstract_xml_helper.rb:286:in `block (2 levels) in xml_to_html'
app/helpers/abstract_xml_helper.rb:285:in `block in xml_to_html'
app/helpers/abstract_xml_helper.rb:284:in `each'
app/helpers/abstract_xml_helper.rb:284:in `xml_to_html'
app/views/shared/_page_tabs.html.slim:56
app/views/page_version/show.html.slim:1
app/controllers/application_controller.rb:64:in `switch_locale'
```

**Comment by benwbrum** [comment]
# Source and XML text for problem pages
## 32404450
```
2.7.3 :001 > page = Page.find 32404450
 => #<Page id: 32404450, title: "stefansson-wrangel-09-15-011-001", source... 
2.7.3 :002 > print page.source_text
THE WESTERN UNION TELEGRAPH COMPANY

PLACE <hi rend="underline"><add>[[Milwaukee (Wisc.)|MILWAUKEE, WIS]]</add></hi> DATE <hi rend="underline"><add><date when="1924-02-26">Feb. 26,1924</date></add></hi>

RECIEVED FROM <hi rend="underline"><add>[[Stefansson, Vilhjalmur, 1879-1962|V. Stefansson]]</add></hi>
<hi rend="underline"><add>Two Hundred -</add></hi> DOLLARS, TO BE PAID TO
<hi rend="underline"><add>[[Fletcher, Inglis, 1879-1969|Mrs. John Fletcher]]</add></hi> AT <hi rend="underline"><add>Formosa Apts.</add></hi>
<hi rend="underline"><add>[[Hollywood (Los Angeles, Calif.)|Hollywood Cal.]]</add></hi>. SUBJECT TO THE TERMS AND CONDI-
TIONS OF MONEY TRANSFER ORDER OF THIS DATE.

<hi rend="underline"><add>F. B. Travis.</add></hi>
<add>Per V. F.</add>

CHARGES PAID $<hi rend="underline"><add>2.40</add></hi> => nil 
2.7.3 :003 > print page.xml_text
<?xml version='1.0' encoding='UTF-8'?>    
      <page>
        <p>THE WESTERN UNION TELEGRAPH COMPANY</p><p>PLACE <hi rend='underline'><add><link link_id='37528280' target_id='32041801' target_title='Milwaukee (Wisc.)'>MILWAUKEE, WIS</link></add></hi> DATE <hi rend='underline'><add><date when='1924-02-26'>Feb. 26,1924</date></add></hi></p><p>RECIEVED FROM <hi rend='underline'><add><link link_id='37528281' target_id='32010887' target_title='Stefansson, Vilhjalmur, 1879-1962'>V. Stefansson</link></add></hi><lb/><hi rend='underline'><add>Two Hundred -</add></hi> DOLLARS, TO BE PAID TO<lb/><hi rend='underline'><add><link link_id='37528282' target_id='32042992' target_title='Fletcher, Inglis, 1879-1969'>Mrs. John Fletcher</link></add></hi> AT <hi rend='underline'><add>Formosa Apts.</add></hi><lb/><hi rend='underline'><add><link link_id='37528283' target_id='32042130' target_title='Hollywood (Los Angeles, Calif.)'>Hollywood Cal.</link></add></hi>. SUBJECT TO THE TERMS AND CONDI<lb break='no'/>TIONS OF MONEY TRANSFER ORDER OF THIS DATE.</p><p><hi rend='underline'><add>F. B. Travis.</add></hi><lb/><add>Per V. F.</add></p><p>CHARGES PAID $<hi rend='underline'><add>2.40</add></hi></p>
      </page>
```

## 34043802
```
2.7.3 :004 > page = Page.find 34043802
 => #<Page id: 34043802, title: "18", source_text: "The State of Alabama   }   Circuit Court,\r\nShelby ...", base_image: "/home/fromthepage/deployment/releases/202404092043...", base_width: 2290, b... 
2.7.3 :005 > print page.source_text
The State of Alabama   }   Circuit Court,
Shelby County.               }   Spring Term 1861
The Grand Jury of said County charge that before the finding of this Indictment.
John W Florey unlawfully and with intense afore-
thought killed Charles a slave belonging to Edward
Florey by cutting him with a knife or 
by  divers wounds and bruises inflicted with 
a piece or pieces of timber, or by shooting
him with a gun or with a pistol




against the peace and dignity of the State of Alabama
                                                   W. H. Moore  
                                                   Solicitor for the 3d Judicial Circuit of Alabama

<hi rend="str">120</hi>
<hi rend="str">3</hi>
<hi rend="underline"></hi>
<hi rend="str">420</hi>

280                                                  <hi rend="str">1140</hi>
<hi rend="underline">730</hi>                                                   <hi rend="str">1010</hi>
1010                                                 <hi rend="str">1.30</hi> => nil 
2.7.3 :006 > print page.xml_text
<?xml version='1.0' encoding='UTF-8'?>    
      <page>
        <p>The State of Alabama   }   Circuit Court,<lb/>Shelby County.               }   Spring Term 1861<lb/>The Grand Jury of said County charge that before the finding of this Indictment.<lb/>John W Florey unlawfully and with intense afore<lb break='no'/>thought killed Charles a slave belonging to Edward<lb/>Florey by cutting him with a knife or <lb/>by  divers wounds and bruises inflicted with <lb/>a piece or pieces of timber, or by shooting<lb/>him with a gun or with a pistol</p><p>against the peace and dignity of the State of Alabama<lb/>W. H. Moore  <lb/>Solicitor for the 3d Judicial Circuit of Alabama</p><p><hi rend='str'>120</hi><lb/><hi rend='str'>3</hi><lb/><hi rend='underline'/><lb/><hi rend='str'>420</hi></p><p>280                                                  <hi rend='str'>1140</hi><lb/><hi rend='underline'>730</hi>                                                   <hi rend='str'>1010</hi><lb/>1010                                                 <hi rend='str'>1.30</hi></p>
      </page>
```

## Page Version 19866
```
2.7.3 :007 > page_version = PageVersion.find 19866
 => #<PageVersion id: 19866, title: "S2 Page 56", transcription: "Collector: [[Joseph Grinnell|Grinnell]] - [[1925]]...", xml_transcription: "<?xml version='1.0' encoding='ISO-8859-15'?>    \n ...",... 
2.7.3 :008 > page = page_version.page
 => #<Page id: 4317, title: "S2 Page 56", source_text: "Collector: [[Joseph Grinnell|Grinnell]] - [[1925]]...", base_image: "/home/fromthepage/fromthepage/releases/20130531212...", base_width: 3920,... 
2.7.3 :009 > print page.source_text
Collector: [[Joseph Grinnell|Grinnell]] - [[1925]] 
Location: <u>[[Mineral]]</u>, 4800 ft.
Date: <u>[[1925-06-29|June 29]]</u>
Page Number: 2509

[[Hermit Thrush]] nests, with young, previously found,
these latter being off the edges of the [[bog]] on either
side, while the [[Swainson's Thrush (ustulatus)|Russet-back]]s is [sic] <u>in</u> the [[bog]].

<u>[[Willow Flycatcher|Traill Flycatcher]]'s</u> nest just found by [[Hilda Grinnell|Mrs. G.]];
in [[willow]] [[bog]] only about 100 yards from the other one
found today. Rim only 750 mm. above ground; nest in
rather open low thicket, of lush leafage, but surrounded
by taller growth of [[willow]] and [[alder]]; supported on
slanting [[willow]] stem, with other twigs and leafage.
<u>Taken</u> (3/4) along with [female symbol] parent. Male birds keep
out of sight in [[willow]]s; heard to sing in usual
fashion. Eggs perfectly fresh.

Saw full fledged young <u>[[MacGillivray's Warbler|Tolmie Warbler]]</u> in the
[[willow]]s.

<a href="http://arctos.database.museum/guid/MVZ:Bird:45904">6271</a> <u>[[Swainson's Thrush (ustulatus)|Russet-backed Thrush]]</u> [female symbol] 29.5 g. With set 1/4 (see <a href="http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&page_id=4316">p. 2508</a>);

<a href="http://arctos.database.museum/guid/MVZ:Bird:45905">6272</a> <u>[[Sierra Hermit Thrush]]</u> [male symbol] ju. 24.0 g. From brood found
on [[1925-06-20|June 20]] (see <a href="http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&page_id=4268">p. 2463</a>). As I touched the nest, the four
youngsters, even tho seemingly so undeveloped, decamped
in as many directions with cries which brot [sic] the
distracted mother. Each went over and under logs
and bush with amazing celerity; the nest was forsaken
for good - the safest procedure to the average, I 
suppose, in the long run. I found also that
the other nest of this species (see <a href="http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&page_id=4288">p. 2482</a>) had been
left by the brood (of about same age) - save for
one dead and partly skeletonized, by ants, in
the bottom of the nest. => nil 
2.7.3 :010 > print page.xml_text
<?xml version='1.0' encoding='UTF-8'?>    
      <page>
        <p>Collector: <link link_id='150209' target_id='8699' target_title='Joseph Grinnell'>Grinnell</link> - <link link_id='150210' target_id='10005' target_title='1925'>1925</link> <lb/> Location: <u><link link_id='150211' target_id='8694' target_title='Mineral'>Mineral</link></u>, 4800 ft.<lb/> Date: <u><link link_id='150212' target_id='10295' target_title='1925-06-29'>June 29</link></u><lb/> Page Number: 2509<lb/></p><p> <link link_id='150213' target_id='9807' target_title='Hermit Thrush'>Hermit Thrush</link> nests, with young, previously found,<lb/> these latter being off the edges of the <link link_id='150214' target_id='10157' target_title='bog'>bog</link> on either<lb/> side, while the <link link_id='150215' target_id='10297' target_title='Swainson&apos;s Thrush (ustulatus)'>Russet-back</link>s is [sic] <u>in</u> the <link link_id='150216' target_id='10157' target_title='bog'>bog</link>.<lb/></p><p> <u><link link_id='150217' target_id='9850' target_title='Willow Flycatcher'>Traill Flycatcher</link>'s</u> nest just found by <link link_id='150218' target_id='8951' target_title='Hilda Grinnell'>Mrs. G.</link>;<lb/> in <link link_id='150219' target_id='9854' target_title='willow'>willow</link> <link link_id='150220' target_id='10157' target_title='bog'>bog</link> only about 100 yards from the other one<lb/> found today. Rim only 750 mm. above ground; nest in<lb/> rather open low thicket, of lush leafage, but surrounded<lb/> by taller growth of <link link_id='150221' target_id='9854' target_title='willow'>willow</link> and <link link_id='150222' target_id='10199' target_title='alder'>alder</link>; supported on<lb/> slanting <link link_id='150223' target_id='9854' target_title='willow'>willow</link> stem, with other twigs and leafage.<lb/> <u>Taken</u> (3/4) along with [female symbol] parent. Male birds keep<lb/> out of sight in <link link_id='150224' target_id='9854' target_title='willow'>willow</link>s; heard to sing in usual<lb/> fashion. Eggs perfectly fresh.<lb/></p><p> Saw full fledged young <u><link link_id='150225' target_id='10203' target_title='MacGillivray&apos;s Warbler'>Tolmie Warbler</link></u> in the<lb/> <link link_id='150226' target_id='9854' target_title='willow'>willow</link>s.<lb/></p><p> <a href='http://arctos.database.museum/guid/MVZ:Bird:45904'>6271</a> <u><link link_id='150227' target_id='10297' target_title='Swainson&apos;s Thrush (ustulatus)'>Russet-backed Thrush</link></u> [female symbol] 29.5 g. With set 1/4 (see <a href='http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&amp;page_id=4316'>p. 2508</a>);<lb/></p><p> <a href='http://arctos.database.museum/guid/MVZ:Bird:45905'>6272</a> <u><link link_id='150228' target_id='9799' target_title='Sierra Hermit Thrush'>Sierra Hermit Thrush</link></u> [male symbol] ju. 24.0 g. From brood found<lb/> on <link link_id='150229' target_id='9991' target_title='1925-06-20'>June 20</link> (see <a href='http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&amp;page_id=4268'>p. 2463</a>). As I touched the nest, the four<lb/> youngsters, even tho seemingly so undeveloped, decamped<lb/> in as many directions with cries which brot [sic] the<lb/> distracted mother. Each went over and under logs<lb/> and bush with amazing celerity; the nest was forsaken<lb/> for good - the safest procedure to the average, I <lb/> suppose, in the long run. I found also that<lb/> the other nest of this species (see <a href='http://beta.fromthepage.com/display/display_page?ol=p_nav_prev&amp;page_id=4288'>p. 2482</a>) had been<lb/> left by the brood (of about same age) - save for<lb/> one dead and partly skeletonized, by ants, in<lb/> the bottom of the nest.</p>
      </page>
```
