### ISSUE TITLE
500 error for new mobile user email

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4320]
From the log files:
```
I, [2024-09-09T16:47:37.041514 #3198088]  INFO -- : Processing by CollectionController#new_mobile_user as */*
I, [2024-09-09T16:47:37.041830 #3198088]  INFO -- :   Parameters: {"collection_id"=>"32000299"}
I, [2024-09-09T16:47:37.042906 #3198088]  INFO -- : [ahoy] Visit excluded
I, [2024-09-09T16:47:37.054750 #3198088]  INFO -- : Redirected to https://fromthepage.com/dashboard
I, [2024-09-09T16:47:37.057246 #3198088]  INFO -- : Completed 500  in 15ms (ActiveRecord: 2.4ms | Allocations: 6604)
F, [2024-09-09T16:47:37.062039 #3198088] FATAL -- :   
NoMethodError (undefined method `like_owner?' for nil:NilClass):
  
app/controllers/collection_controller.rb:663:in `authorized?'
app/controllers/application_controller.rb:64:in `switch_locale'
```

**Comment by WillNigel23** [comment]
This may be because collection with id `32000299` does not exist. When did this happen? Did a user click back after deleting a collection?

**Comment by benwbrum** [comment]
Looking at the most recent production log, I see this:
```
I, [2024-10-28T00:10:56.334080 #3852072]  INFO -- : Started GET "/collection/32000850/new_mobile_user" for 43.156.12.8 at 2024-10-28 00:10:56 +0000
I, [2024-10-28T00:10:56.336462 #3852072]  INFO -- : Processing by CollectionController#new_mobile_user as */*
I, [2024-10-28T00:10:56.336686 #3852072]  INFO -- :   Parameters: {"collection_id"=>"32000850"}
I, [2024-10-28T00:10:56.353663 #3852072]  INFO -- : Redirected to https://www.fromthepage.com/dashboard
I, [2024-10-28T00:10:56.355684 #3852072]  INFO -- : Completed 500  in 19ms (ActiveRecord: 4.0ms | Allocations: 8983)
F, [2024-10-28T00:10:56.360135 #3852072] FATAL -- :   
NoMethodError (undefined method `like_owner?' for nil:NilClass):
  
app/controllers/collection_controller.rb:663:in `authorized?'
app/controllers/application_controller.rb:78:in `switch_locale'
app/controllers/application_controller.rb:27:in `check_deleted_articles'


I, [2024-10-28T00:33:12.914314 #3852072]  INFO -- : Started GET "/collection/916/new_mobile_user" for 20.171.206.214 at 2024-10-28 00:33:12 +0000
I, [2024-10-28T00:33:12.916599 #3852072]  INFO -- : Processing by CollectionController#new_mobile_user as */*
I, [2024-10-28T00:33:12.916777 #3852072]  INFO -- :   Parameters: {"collection_id"=>"916"}
I, [2024-10-28T00:33:12.931174 #3852072]  INFO -- : Redirected to https://fromthepage.com/dashboard
I, [2024-10-28T00:33:12.932926 #3852072]  INFO -- : Completed 500  in 16ms (ActiveRecord: 3.4ms | Allocations: 8750)
F, [2024-10-28T00:33:12.936914 #3852072] FATAL -- :   
NoMethodError (undefined method `like_owner?' for nil:NilClass):
  
app/controllers/collection_controller.rb:663:in `authorized?'
app/controllers/application_controller.rb:78:in `switch_locale'
app/controllers/application_controller.rb:27:in `check_deleted_articles'


I, [2024-10-28T00:36:12.798288 #3852020]  INFO -- : Started GET "/collection/804/new_mobile_user" for 17.241.219.137 at 2024-10-28 00:36:12 +0000
I, [2024-10-28T00:36:12.800657 #3852020]  INFO -- : Processing by CollectionController#new_mobile_user as HTML
I, [2024-10-28T00:36:12.800838 #3852020]  INFO -- :   Parameters: {"collection_id"=>"804"}
I, [2024-10-28T00:36:12.801835 #3852020]  INFO -- : [ahoy] Visit excluded
I, [2024-10-28T00:36:12.807733 #3852072]  INFO -- : Started GET "/mountauburncemetery/mount-auburn-cemetery-letterpress-copying-books/2005-062-016/transcribe/1066795" for 111.225.148.154 at 2024-10-28 00:36:12 +0000
I, [2024-10-28T00:36:12.810173 #3852020]  INFO -- : Redirected to https://fromthepage.com/dashboard
I, [2024-10-28T00:36:12.811966 #3852020]  INFO -- : Completed 500  in 11ms (ActiveRecord: 2.0ms | Allocations: 6563)
F, [2024-10-28T00:36:12.815632 #3852020] FATAL -- :   
NoMethodError (undefined method `like_owner?' for nil:NilClass):
  
app/controllers/collection_controller.rb:663:in `authorized?'
app/controllers/application_controller.rb:78:in `switch_locale'





I, [2024-10-28T00:45:09.525550 #3852020]  INFO -- : Started GET "/collection/951/new_mobile_user" for 129.226.92.236 at 2024-10-28 00:45:09 +0000
I, [2024-10-28T00:45:09.527911 #3852020]  INFO -- : Processing by CollectionController#new_mobile_user as */*
I, [2024-10-28T00:45:09.528111 #3852020]  INFO -- :   Parameters: {"collection_id"=>"951"}
I, [2024-10-28T00:45:09.542082 #3852020]  INFO -- : Redirected to https://www.fromthepage.com/dashboard
I, [2024-10-28T00:45:09.543930 #3852020]  INFO -- : Completed 500  in 16ms (ActiveRecord: 3.0ms | Allocations: 8358)
F, [2024-10-28T00:45:09.547976 #3852020] FATAL -- :   
NoMethodError (undefined method `like_owner?' for nil:NilClass):
  
app/controllers/collection_controller.rb:663:in `authorized?'


```

So it's still happening

**Comment by WillNigel23** [comment]
the issue is this:
  def authorized?
    unless user_signed_in?
      ajax_redirect_to dashboard_path
    end
    
    # does not return

    # this gets executed

    if @collection &&  !current_user.like_owner?(@collection)
      ajax_redirect_to dashboard_path
    end
  end
ajax_redirect_to dashboard_path is not returning, meaning it executes the code below. And thus, the like_owner method does not exist for nil
Maybe this is the result of a bad merge, where we have 2 def authorized? function in collection_controller (and actually multiple private declaration too)

This should be fixed by #4382

**Comment by benwbrum** [comment]
Closed by #4382
