### ISSUE TITLE
ingestor hangs when an empty zipfile is uploaded

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4350]
LVA attempted to upload a 22 byte zipfile this morning, but rather than sending them an error, the document upload just stayed in the Processing state.

We should handle this better.

**Comment by WillNigel23** [comment]
Can I please have the logs here?

**Comment by benwbrum** [comment]
Processing log:
```
fetching upload with ID=32026654
found document_upload for 
	user=LVA, 
	target collection=Woodland Cemetery Interment Cards, Dungee-Gray, 1920-1973., 
	file=/uploads/document_upload/file/32026654/Box_15.zip
creating temp directory /tmp/fromthepage_uploads/32026654
copying /home/fromthepage/deployment/releases/20240920211105/public/uploads/document_upload/file/32026654/* to /tmp/fromthepage_uploads/32026654
unzip_tree(/tmp/fromthepage_uploads/32026654)
	unzip_tree considering /tmp/fromthepage_uploads/32026654/Box_15.zip
Found zipfile /tmp/fromthepage_uploads/32026654/Box_15.zip
Calling unzip_file(/tmp/fromthepage_uploads/32026654/Box_15.zip, /tmp/fromthepage_uploads/32026654/Box_15)
upzip_file(/tmp/fromthepage_uploads/32026654/Box_15.zip)
unzip_tree(/tmp/fromthepage_uploads/32026654/Box_15)
Errno::ENOENT: No such file or directory @ rb_file_s_stat - /tmp/fromthepage_uploads/32026654/Box_15
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:923:in `stat'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:923:in `symbolic_modes_to_i'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:972:in `fu_mode'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:1038:in `block (2 levels) in chmod_R'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:1493:in `preorder_traverse'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:1036:in `block in chmod_R'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:1035:in `each'
/usr/share/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/fileutils.rb:1035:in `chmod_R'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:91:in `unzip_tree'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:87:in `block in unzip_tree'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:75:in `each'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:75:in `unzip_tree'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:54:in `process_batch'
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:32:in `block (2 levels) in <main>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `block in execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `each'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/fromthepage/deployment/releases/20240920211105/app/interactors/rake_interactor.rb:24:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:213:in `block in with_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:224:in `run_around_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:211:in `with_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:142:in `run!'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:115:in `run'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:50:in `tap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:50:in `call'
/home/fromthepage/deployment/releases/20240920211105/app/jobs/document_upload/process_job.rb:6:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:48:in `block in perform_now'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:76:in `block in run_in_trace'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer.rb:74:in `block in trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer_helpers.rb:37:in `block in trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer_helpers.rb:37:in `trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer.rb:72:in `trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:74:in `run_in_trace'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:61:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:31:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `block in tag_logger'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:37:in `tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `tag_logger'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:47:in `perform_now'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:25:in `block in execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:72:in `block in wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:71:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:23:in `execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
```

[Box_15.zip](https://github.com/user-attachments/files/17135680/Box_15.zip)
