### ISSUE TITLE
DocumentUpload staying in queued status

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4358]
Recently, two document uploads have remained in `queued` status, which means that either our job system is not picking them up, or some error is happening between record creation and changing their status to `processing`.  Both of these are PDF uploads of the same PDF

```
2.7.3 :001 > du = DocumentUpload.find 32026890
 => #<DocumentUpload id: 32026890, user_id: 32027176, collection_id: 0, file: "Corsarios__Ingleses_y_franceses_.pdf"... 
2.7.3 :002 > du.status
 => "queued" 
2.7.3 :003 > du
 => #<DocumentUpload id: 32026890, user_id: 32027176, collection_id: 0, file: "Corsarios__Ingleses_y_franceses_.pdf", created_at: "2024-09-30 05:16:40.000000000 +0000", updated_at: "2024-09-30 05:16:40.000000000 +0000", status: "queued", preserve_titles: false, ocr: false> 
2.7.3 :004 > pp du.attributes
{"id"=>32026890,
 "user_id"=>32027176,
 "collection_id"=>0,
 "file"=>"Corsarios__Ingleses_y_franceses_.pdf",
 "created_at"=>Mon, 30 Sep 2024 05:16:40.000000000 UTC +00:00,
 "updated_at"=>Mon, 30 Sep 2024 05:16:40.000000000 UTC +00:00,
 "status"=>"queued",
 "preserve_titles"=>false,
 "ocr"=>false}
 => {"id"=>32026890, "user_id"=>32027176, "collection_id"=>0, "file"=>"Corsarios__Ingleses_y_franceses_.pdf", "created_at"=>Mon, 30 Sep 2024 05:16:40.000000000 UTC +00:00, "updated_at"=>Mon, 30 Sep 2024 05:16:40.000000000 UTC +00:00, "status"=>"queued", "preserve_titles"=>false, "ocr"=>false} 
2.7.3 :005 > DocumentUpload.pluck(:status).tally
 => {"queued"=>110, "finished"=>38969, "new"=>6, "processing"=>604, "error"=>5} 
2.7.3 :006 > DocumentUpload.where(created_at: [Date.new(2024,9,1)..]).pluck(:status).tally
 => {"finished"=>981, "processing"=>8, "queued"=>13} 
2.7.3 :007 > DocumentUpload.where(created_at: [Date.new(2024,9,28)..]).pluck(:status).tally
 => {"finished"=>84, "queued"=>2} 
2.7.3 :008 > DocumentUpload.where(created_at: [Date.new(2024,9,28)..]).where(status: 'queued').to_a
 => [#<DocumentUpload id: 32026890, user_id: 32027176, collection_id: 0, file: "Corsarios__Ingleses_y_franceses_.pdf", created_at: "2024-09-30 05:16:40.000000000 +0000", updated_at: "2024-09-30 05:16:40.000000000 +0000", status: "queued", preserve_titles: false, ocr: false>, #<DocumentUpload id: 32026891, user_id: 32027176, collection_id: 0, file: "Corsarios__Ingleses_y_franceses_.pdf", created_at: "2024-09-30 05:17:32.000000000 +0000", updated_at: "2024-09-30 05:17:32.000000000 +0000", status: "queued", preserve_titles: true, ocr: false>] 
2.7.3 :009 > 
```

I'm attaching the PDF.  The only thing I see unusual about it is that its filename ends with an underscore
[Corsarios__Ingleses_y_franceses_.pdf](https://github.com/user-attachments/files/17189784/Corsarios__Ingleses_y_franceses_.pdf)

**Comment by benwbrum** [comment]
Here is the logfile that reports an error:
```
fetching upload with ID=32026890
NoMethodError: undefined method `title' for nil:NilClass
/home/fromthepage/deployment/releases/20240920211105/lib/tasks/ingestor.rake:27:in `block (2 levels) in <main>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `block in execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `each'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/fromthepage/deployment/releases/20240920211105/app/interactors/rake_interactor.rb:24:in `call'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:213:in `block in with_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:224:in `run_around_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor/hooks.rb:211:in `with_hooks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:142:in `run!'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:115:in `run'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:50:in `tap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/interactor-3.1.2/lib/interactor.rb:50:in `call'
/home/fromthepage/deployment/releases/20240920211105/app/jobs/document_upload/process_job.rb:6:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:48:in `block in perform_now'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:76:in `block in run_in_trace'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer.rb:74:in `block in trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer_helpers.rb:37:in `block in trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer_helpers.rb:37:in `trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/method_tracer.rb:72:in `trace_execution_scoped'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:74:in `run_in_trace'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:61:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `block in instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:31:in `instrument'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `block in tag_logger'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:37:in `tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `tagged'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `tag_logger'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:47:in `perform_now'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:25:in `block in execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:72:in `block in wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:71:in `wrap'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:23:in `execute'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/activejob-6.1.7.6/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/home/fromthepage/deployment/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.13.0/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'

```

**Comment by bencomp** [comment]
Could it be that the collection that the file is being uploaded to has no title? Or that it's not linked to a collection? The line that raises the error prints the title of the collection:
https://github.com/benwbrum/fromthepage/blob/337b29aea556b20056fbf7a46e047da7757b95cb/lib/tasks/ingestor.rake#L27

If there is no collection, I could see this error being raised.

**Comment by benwbrum** [comment]
Let's avoid uploading a document without a target collection.

**Comment by benwbrum** [comment]
Duplicate of #3200
