### ISSUE TITLE
500 Internal Server Error on editor tab for user with no recent activity

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#436]
When a user who hasn't recently done anything on the server tries to get to the editor tab, they get a 500 Internal Server error.  This shows up in the logfile:
   NoMethodError (undefined method `id' for nil:NilClass): app/controllers/dashboard_controller.rb:114:in `recent_work' app/controllers/dashboard_controller.rb:94:in `watchlist'

**Comment by tbl73** [comment]
Fixed with pull request #438.
