### ISSUE TITLE
500 error on IIIF manifest "width must be a positive integer"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4364]
This manifest:

https://fromthepage.com/iiif/32137402/manifest

is failing to load with a 500 error.  

Here's the error in the logs:
```
I, [2024-10-01T14:35:23.839227 #3403510]  INFO -- : Started GET "/iiif/32137402/manifest" for 136.62.254.224 at 2024-10-01 14:35:23 +0000
I, [2024-10-01T14:35:23.841494 #3403510]  INFO -- : Processing by IiifController#manifest as HTML
I, [2024-10-01T14:35:23.841691 #3403510]  INFO -- :   Parameters: {"id"=>"32137402"}
I, [2024-10-01T14:35:23.877170 #3403510]  INFO -- : Completed 500  in 35ms (ActiveRecord: 7.2ms | Allocations: 25305)
F, [2024-10-01T14:35:23.883271 #3403510] FATAL -- :   
IIIF::Presentation::IllegalValueError (width must be a positive Integer.):
  
app/controllers/iiif_controller.rb:729:in `canvas_from_iiif_page'
app/controllers/iiif_controller.rb:613:in `block in iiif_sequence_from_work_id'
app/controllers/iiif_controller.rb:611:in `iiif_sequence_from_work_id'
app/controllers/iiif_controller.rb:245:in `manifest'
app/controllers/application_controller.rb:64:in `switch_locale'

```

coming from here:  https://github.com/search?q=repo%3Abenwbrum%2Ffromthepage%20canvas_from_iiif_page&type=code

which implies that the width isn't a positive integer.

**Comment by saracarl** [comment]
The bad width is a "null" that came from the original manifest:
https://core-data-cloud-production-955ccda75add.herokuapp.com//core_data/public/v1/works/a7dd1994-96ff-4738-97e4-edd41cb4484d/manifests/40ca260d-ea06-4ac2-bcc4-13f62fc585a0

![image](https://github.com/user-attachments/assets/7db31454-14c8-4c87-a43d-87277dbf9bc0)

The original image is here:
https://iiif.archivengine.com/iiif/3/fipv9xpf2sf6k96vc51spyb34jvc;1/full/max/0/default.jpg
and it looks like the canvas should be 2677x3733

**Comment by saracarl** [comment]
Fix in prod:
```
2.7.0 :003 > page = Page.find 34282982
 => #<Page id: 34282982, title: "GMRV_004275085_IMG_0640.jpg", source_text: "The town of Fernando de Taos\r\n13th day of August, ...", base_image: nil, base_width: nil, base_height: nil, shrink_fact... 
2.7.0 :004 > canvas = page.sc_canvas
 => #<ScCanvas id: 25570082, sc_id: nil, sc_manifest_id: 25035047, page_id: 34282982, sc_canvas_id: "https://iiif-cloud-production.herokuapp.com/public...", sc_canvas_label: "GMRV_004275085_IMG_0640... 
2.7.0 :005 > canvas.height=3733
 => 3733 
2.7.0 :006 > canvas.width=2677
 => 2677 
2.7.0 :007 > canvas.save!
```
