### ISSUE TITLE
email for contributor_stats timing out

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#493]

**Comment by saracarl** [comment]
[fromthepage@fromthepage current]$ rake fromthepage:contributor_stats[16,saracarl@gmail.com]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
rake aborted!
Net::OpenTimeout: execution expired
/home/fromthepage/deployment/shared/bundle/ruby/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/fromthepage/deployment/shared/bundle/ruby/gems/mail-2.5.4/lib/mail/message.rb:248:in `deliver!'
/home/fromthepage/deployment/releases/20161207152841/lib/tasks/contributor_stats.rake:15:in `block (2 levels) in <top (required)>'
/home/fromthepage/.gem/ruby/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => fromthepage:contributor_stats
