### ISSUE TITLE
Moved server image files failing resize/rotate

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#684]
The image path is hardcoded somewhere to where they were.  We need them to be where they are now.

F, [2017-06-26T11:47:38.319227 #35749] FATAL -- : 
Magick::ImageMagickError (unable to open image `/var/www/html/fromthepage/public/images/working/65/55_Page_008.jpg': No such file or directory @ blob.c/OpenBlob/2480):
  app/controllers/page_controller.rb:131:in `new'
  app/controllers/page_controller.rb:131:in `set_dimensions'
  app/controllers/page_controller.rb:47:in `enlarge'

F, [2017-06-26T11:42:51.473073 #35749] FATAL -- : 
Magick::ImageMagickError (unable to open image `/var/www/html/fromthepage/public/images/working/65/55_Page_008.jpg': No such file or directory @ blob.c/OpenBlob/2480):
  lib/image_helper.rb:141:in `new'
  lib/image_helper.rb:141:in `rotate_file'
  app/controllers/page_controller.rb:32:in `block in rotate'
  app/controllers/page_controller.rb:31:in `upto'
  app/controllers/page_controller.rb:31:in `rotate'

**Comment by saracarl** [comment]
Fixed the paths to the old pages.  It may require a shift-reload in the browser to see the rotated image, but it is working now.

@benwbrum has some additional thoughts on fixing the caching/reload issue.
