### ISSUE TITLE
RegexpError (premature end of char-class: /\b[form\b/i):

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#687]
I, [2017-06-26T12:02:45.267932 #35749]  INFO -- : Started PATCH "/transcribe/save_transcription" for 74.209.34.102 at 2017-06-26 12:02:45 -0400
I, [2017-06-26T12:02:45.271168 #35749]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2017-06-26T12:02:45.271422 #35749]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "page_id"=>"1919", "page"=>{"mark_blank"=>"0", "needs_review"=>"0", "source_text"=>"3/20/74\r\n12-2--80\r\n\r\n                                  Philip K. Dick\r\n                                  408 E Civic Center\r\n                                  #301\r\n                                  Santa Ana\r\n                                  Calif 92701\r\n                                  (714)836-6367\r\n\r\n\r\n                THE DIALECTIC:\r\n         God against Satan, + God's\r\n       final victory foretold + shown\r\n\r\n\r\n               Philip K. Dick\r\n\r\n                An EXEGESIS\r\n\r\n\r\n\r\n            Apologia pro mea vita"}, "autolink"=>""}
W, [2017-06-26T12:02:45.357021 #35749]  WARN -- : WARNING: Can't mass-assign protected attributes for Page: mark_blank, needs_review
	app/controllers/transcribe_controller.rb:70:in `save_transcription'
I, [2017-06-26T12:02:45.512632 #35749]  INFO -- : Completed 500 Internal Server Error in 241ms
F, [2017-06-26T12:02:45.517433 #35749] FATAL -- : 
RegexpError (premature end of char-class: /\b[form\b/i):
  app/controllers/abstract_xml_controller.rb:29:in `initialize'
  app/controllers/abstract_xml_controller.rb:29:in `new'
  app/controllers/abstract_xml_controller.rb:29:in `block in autolink'
  app/controllers/abstract_xml_controller.rb:28:in `each'
  app/controllers/abstract_xml_controller.rb:28:in `autolink'
  app/controllers/transcribe_controller.rb:149:in `save_transcription'

**Comment by saracarl** [comment]
This was caused by a subject with the verbatim text "[form" which was causing problems in the matching when autolinking on page http://zebrapedia.psu.edu/transcribe/display_page?page_id=1919

I deleted the subject for "[form" and removed the link that referred to it -- it was only one page:
http://zebrapedia.psu.edu/display/display_page?page_id=1930

(search for [form] near the bottom).

Which leaves the outstanding problem of "do you want to link [form]?"  The current code does not allow for triple [[[ ]]] around words, and will give you a warning and not save it.

I then go back to page
http://zebrapedia.psu.edu/transcribe/display_page?page_id=1919

And try to autolink and save.  I get a similar error, but this time with the verbatim "[PKD"  :

W, [2017-07-14T08:41:53.917575 #61746]  WARN -- : WARNING: Can't mass-assign protected attributes for Page: mark_blank, needs_review
	app/controllers/transcribe_controller.rb:70:in `save_transcription'
I, [2017-07-14T08:41:53.986132 #61746]  INFO -- : Completed 500 Internal Server Error in 120ms
F, [2017-07-14T08:41:53.988275 #61746] FATAL -- : 
RegexpError (premature end of char-class: /\b[PKD\b/i):
  app/controllers/abstract_xml_controller.rb:29:in `initialize'
  app/controllers/abstract_xml_controller.rb:29:in `new'
  app/controllers/abstract_xml_controller.rb:29:in `block in autolink'
  app/controllers/abstract_xml_controller.rb:28:in `each'
  app/controllers/abstract_xml_controller.rb:28:in `aisutolink'
  app/controllers/transcribe_controller.rb:149:in `save_transcription'

This came from a linked "[PKD" on this page:
http://zebrapedia.psu.edu/transcribe/display_page?page_id=1690
which was not actually even an actual transcription, but a note about some text on the page.  I moved it to "notes" and took out the brackets:
 [[[PKD]] writes in *German*].

After this I went back to our failing autolinking page ( http://zebrapedia.psu.edu/transcribe/display_page?page_id=1919 ) and was able to cleanly autolink and save it.  

This should be resolved.  The new code no longer lets you save verbatim text with brackets in it.
