### ISSUE TITLE
Autolink breaks if verbatim text has regex special characters

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#76]
If the page_article_links table is seeded with data containing open braces, autolink will fail.  We need to regex-escape the strings used by autolink before we test the text.

```
mysql> select display_text from page_article_links where display_text like '%[%';
+-----------------------------------+
| display_text                      |
+-----------------------------------+
| whea[t] land                      |
| Suiter[?] Blair                   |
| Dr [?aton]                        |
| S[eu?]la[r?] Hayley               |
| Board[?] and Tennie[?]
<lb/>Dews |
| Old man Sam C[a?]llens            |
| Miss Ursal[?] Lewis               |
| Mrs. McLau[gh]lin                 |
| Antonio Lopez de S.A. [?          |
| Mrs [Preston?                     |
| Laguna [Mathre?                   |
| [Wright] [Flycatcher              |
| Traill] [Flycatcher               |
| Hammond (?) [sic] Flycatcher      |
| [Song] [Sparrow                   |
| [Hammond] [Flycatcher             |
| [Thomomys] [monticola             |
| [Calaveras] [Warbler              |
| [Thomomys] [monticola             |
| [Sorex] [v.] [amoenus             |
| [Thomomys] [monticola             |
+-----------------------------------+
21 rows in set (0.03 sec)

mysql> exit
Bye
```

Error log output:

```
Processing TranscribeController#save_transcription (for 209.163.168.194 at 2014-10-15 13:31:00) [POST]
  Parameters: {"autolink"=>"Autolink", "authenticity_token"=>"SACEM5M2bSEQe00Ebkmpg0Ozory3Az6Iyz8LQBWC4cs=", "page_id"=>"4410", "page"=>{"source_text"=>"Collector: Grinnell - 1925\r\nLocation: San Jose, 2500 ft., Lat. 31 degrees\r\nDate: October 19, 1925\r\nPage Number: 2597\r\n\r\nEarly this morning I saw a Pigeon Hawk fly \r\nover the ranch. It was stockier that (sic) a Sparrow Hawk,\r\nsomewhat broader wings, and decidedly darker in\r\ngeneral color effect. Also I saw a Lewis\r\nWoodpecker fly from post to post along a pasture\r\nfence. Tonight I again heard a Poor-will and \r\na Screech Owl.\r\n6560 San Lucas Flycatcher (female sign) im. 10.8g. Shot in live oak\r\n6561 Rock Wren (male sign) ad. 17.4g. Shot off of granite boulder.\r\n6562 Spotted Towhee (male sign) ad. 38.6g. Shot from small oak.\r\n6563 Calif. Jay (female sign) ad. 75.0g. Shot from small oak.\r\n   Oct. 20\r\n   Besides the following 4 mammals saved, my 22 \r\nmouse and rat traps brot only a Peromyscus\r\nmaniculatus, (male sign), discarded, under a sage-bush.\r\n6564 Ammospermophilus (female sign) 91.5g. 223x69x38x4. In rat-trap on open hill-top.\r\n6565 Dipodomys (male sign) 50.0g. 267x151x40x13. In rat-trap on open hill-top.\r\n6566 Dipodomys (female sign) 51.2g. 273x161x41.5x11.5. In rat-trap on open hill-top.\r\n6567 Dipodomys (male sign) 63.2. 286x171x40x12. In rat-trap on open hill-top.\r\n  Before breakfast, 5:30-6:45, I went up the valley\r\nlooking for rabbits; none seen. Saw, and downed, a\r\nCooper Hawk, but failed to find it in the dense\r\nbrush. Later, 8-12, Lamb and I went up on\r\nthe mesa and across the anastre (?) ravine where\r\nthe live oaks are to get jays - which we did.\r\nWe only heard the Shrike, and barely glimpsed\r\n a Black-tailed Gnatcatcher. Other birds about as\r\nyesterday over the same route, save that I\r\n\r\n", "status"=>""}}

RegexpError (premature end of regular expression: /\b[Sorex] [v.] [amoenus\b/):
  app/controllers/abstract_xml_controller.rb:26:in `initialize'
  app/controllers/abstract_xml_controller.rb:26:in `new'
  app/controllers/abstract_xml_controller.rb:26:in `autolink'
  app/controllers/abstract_xml_controller.rb:25:in `each'
  app/controllers/abstract_xml_controller.rb:25:in `autolink'
  app/controllers/transcribe_controller.rb:50:in `save_transcription'
```

**Comment by tbl73** [comment]
This seems related to the bug in #473, where we changed the save action so that it won't save unless the double braces are properly closed.  I'm not exactly sure how this plays into that change?

**Comment by benwbrum** [comment]
Yep -- they're duplicates!  Closing this one.
